### ISSUE TITLE
Cursor is indented in PS Core

### ISSUE THREAD

**Issue by mtman** [JanDeDobbeleer/oh-my-posh2#102]
I have followed the steps and ended up with the indented cursor:

(Clean ConEmu config with Meslo)

![image](https://user-images.githubusercontent.com/15874394/42128266-e2a83e5a-7ca7-11e8-8e64-0f88d7ab1a4f.png)

I have no clue how to add the theme, but that's only for colors if I understand the guide.

Versions:
Powershell Core 6.0.2
PSReadLine 2.0.0
posh-git 0.7.3
oh-my-posh 2.0.207
ConEmu 180626 preview

Microsoft.PowerShell_profile.ps1:
```
Import-Module posh-git
Import-Module oh-my-posh
Set-Theme paradox
```

**Comment by mvmcjr** [comment]
+1
