### ISSUE TITLE
Hyper Terminal

### ISSUE THREAD

**Issue by aissasell** [JanDeDobbeleer/oh-my-posh2#104]
In fact in matter of view and design, Hyper Terminal is better than ConEmu. And i just wanted to inform that i tried ohmyposh with Hyper Terminal, its working verry well. You just need to set the correct font in config file.
![screenshot_1](https://user-images.githubusercontent.com/17217604/42367609-b45e779a-80fc-11e8-8bc2-8151c29c1141.png)
The only one issue i got by runing it in Hyper is that when i use the Symfony web server and then i try to split the window i get an error. So what i do is that i split the window first and then i run the web server and i continue the work in the other part of the splited tab which also can be splited.
I hope this helps.

**Comment by JanDeDobbeleer** [comment]
I don't seem to see an error (or issue) on the provided screenshot. Is it due to me needing coffee (could be) or can you point me in the right direction?

**Comment by JanDeDobbeleer** [comment]
No feedback so I'm closing this one. Feel free to reopen with more information.
