### ISSUE TITLE
README: Add information about selected font and missing characters

### ISSUE THREAD

**Issue by kentcb** [JanDeDobbeleer/oh-my-posh2#109]
Hi,

Just trying this out and found that my branch character (and others) aren't rendering correctly:

![image](https://user-images.githubusercontent.com/1901832/45788671-5b386c80-bcbf-11e8-8c02-3e076f5cc847.png)

Obviously some kind of Unicode problem, but I'm not sure exactly what. I tried switching fonts a couple times, but they all do the same thing.

Any ideas?

Update: it's gotten weirder. Sometimes the glyphs appear, sometimes not:

![image](https://user-images.githubusercontent.com/1901832/45792383-db1b0280-bcd0-11e8-9c94-acdb5b05ea1b.png)

**Comment by xphaul** [comment]
@kentcb 
- you can download this repo https://github.com/powerline/fonts
- click the install file which contain the command that install the fonts inside the repo
- run the code inside the file on a powershell that's running on as admin
- after installing, go to the properties of powershell > font . select Dejavu sans mono (this font resolved the weird characters for me) , or select other font that suits you

hope this helps

**Comment by kentcb** [comment]
Thanks @xpaul - that did indeed fix the problem. I guess I didn't realise that this would restrict the set of fonts I could use. It might be nice to have that in the README.

**Comment by JanDeDobbeleer** [comment]
Yup, fonts can have an impact on this. I'll add it to the README.
