### ISSUE TITLE
Display get/location/pushd/popd stack count

### ISSUE THREAD

**Issue by fraxen** [JanDeDobbeleer/oh-my-posh2#113]
Hi,
I am just a modest beginner in posh, but I am trying to re-use some snippets I found to display a "+" for each location in the pushd/popd stack...

Snatched this somewhere:
```$Stack = "+" * (Get-Location -Stack).count```

But I can't get to work in a theme!
As a test I tried to modify the line that displays the current directory in the Agnoster theme:
```$prompt += Write-Prompt -Object "$(Get-ShortPath -dir $pwd)$((Get-Location -Stack).Count)" -ForegroundColor $sl.Colors.PromptForegroundColor -BackgroundColor $sl.Colors.PromptBackgroundColor```

- the count in this test is always 0!

**Comment by JanDeDobbeleer** [comment]
Hey @fraxen, I get the same results in my tests. Reading through the documentation doesn't bruing clarity other than my assumption that there's another default stack created when you're setting the prompt causing it to always be 0 due to 1 item in the stack. I'm happy to have someone else have a go at this one ;-)

**Comment by krokofant** [comment]
I've done something similar while adapting the Agnoster theme:
![image](https://user-images.githubusercontent.com/5908498/57035479-70607b00-6c52-11e9-96bb-e7ba5731b164.png)

To get an array of all folders up to a repository root (could be set to something else though)
https://github.com/krokofant/lovely-powershell/blob/fff89c97ca42204e8f5b323399c152622d1d7f4f/PoshThemes/Hitchens.psm1#L19-L27
```powershell
    function Get-FoldersToRepoRoot {
        $repoPath = Join-Path -Resolve $status.GitDir "\..\"
        $folders = @(); $current = (Get-Item .);
        while ((Join-Path $current.FullName "").Contains($repoPath)) {
            $folders += $current.Name; $current = $current.Parent
        };
        [array]::Reverse($folders)
        $folders
    }
```

Adding a separator for each parent folder:
https://github.com/krokofant/lovely-powershell/blob/fff89c97ca42204e8f5b323399c152622d1d7f4f/PoshThemes/Hitchens.psm1#L65
```powershell
$prefix = & {
  if ($folders.Count -gt 2) { (".." + $sl.PromptSymbols.PathSeparator)*($folders.Count-1) }
  else { $sl.PromptSymbols.PathSeparator }
}
```

**Comment by jleechpe** [comment]
I can't figure out a way to get the stack count to work purely by adding code to the theme or to `oh-my-posh`, however the following did work for me:

Microsoft.PowerShell_profile.ps1
```powershell
$getLoc = {Get-Location -Stack}
```

theme.psm1
```powershell
$stackCount = (&$getLoc).count
```

And then adding `$stackCount` to the appropriate location of your prompt.  Scoping a variable in profile that can call `Get-Location -Stack` keeps the call in the appropriate scope, while even forcing a different stack name is still localized to the module (be it `oh-my-posh` or the theme itself)

**Comment by JanDeDobbeleer** [comment]
@jleechpe given that this is rather annoying to add as functionality to oh-my-posh, is it OK if I add this to the README?

**Comment by jleechpe** [comment]
That sounds fine to me.

**Comment by jleechpe** [comment]
That sounds fine to me.
