### ISSUE TITLE
[PowerShell 6] Themes loaded from older PowerShell directory

### ISSUE THREAD

**Issue by AridTag** [JanDeDobbeleer/oh-my-posh2#114]
In PowerShell 6 the default user profile path is Documents\PowerShell

Previous it is Documents\WindowsPowerShell

Themes are not recognized if placed under Documents\PowerShell\PoshThemes but are recognized under Documents\WindowsPowerShell\PoshThemes

**Comment by AridTag** [comment]
I just noticed that there is a $ThemeSettings property for this, that I could have my profile script change. I do think it should default to the correct thing for the environment though.

**Comment by JanDeDobbeleer** [comment]
I had a look at available variables but can't seem to find one that specifies this location (at least not on 5.1). If you have more information, please let me know.

**Comment by wsmelton** [comment]
You can potentially use something like this:

```powershell
if ($PSEdition -eq 'Core') {
    $themeRoot = "$([System.Environment]::GetFolderPath("mydocuments"))\PowerShell\PoshThemes"
} else {
    $path = "$([System.Environment]::GetFolderPath("mydocuments"))\WindowsPowerShell\PoshThemes"
```

**Comment by Berrysoft** [comment]
@JanDeDobbeleer The variable is at the 4th line of `defaults.ps1`.

**Comment by krokofant** [comment]
@JanDeDobbeleer I created a PR to implement this (#137)
