### ISSUE TITLE
Prompt fails to return after using Tab key function Complete

### ISSUE THREAD

**Issue by erichiller** [JanDeDobbeleer/oh-my-posh2#116]
I am not sure how similar this is to #77 , but it seems to be. Using the PSReadline Key handler for Tab of `Complete`. On pressing <tab><tab> the prompt is not set again. See below:

```
PS C:\WINDOWS\System32> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.17134.228
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17134.228
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1


PS C:\WINDOWS\System32> import-module oh-my-posh ; get-module oh-my-posh

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     2.0.230    oh-my-posh                          {Get-ComputerName, Get-Drive, Get-FullPath, Get-ShortPath...}


 ehiller@SM-EHILLER1  C\..\System32  get-module psreadline
 ehiller@SM-EHILLER1  C\..\System32  import-module psreadline
 ehiller@SM-EHILLER1  C\..\System32  get-module psreadline

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     2.0.0      psreadline                          {Get-PSReadLineKeyHandler, Get-PSReadLineOption, Remove-PS...


 ehiller@SM-EHILLER1  C\..\System32  get-module posh-git

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     1.0.0      posh-git                            {Add-PoshGitToProfile, Add-SshKey, Expand-GitCommand, Form...


 ehiller@SM-EHILLER1  C\..\System32  Set-PSReadLineKeyHandler -Key Tab -Function Complete
 ehiller@SM-EHILLER1  C\..\System32  Get-He
Get-HealthFault  Get-Help
PS>Get-He
```

It is this command where I press <tab><tab> in the above ` ehiller@SM-EHILLER1  C\..\System32  Get-He<tab><tab>`

This was with a blank powershell window, no profile, only the above commands were run in the window.

Here is the graphical output:
![image](https://user-images.githubusercontent.com/5379325/48316667-a7a37880-e59b-11e8-9a8c-3bd02a178ecb.png)

Commenting out the body in `oh-my-posh` - `Set-Prompt` and inserting a basic function that just writes a string results in the proper functionality. See:

```


function edh-prompt { "goo" }

<#
        .SYNOPSIS
        Generates the prompt before each line in the console
#>
function Set-Prompt {
    # Import-Module $sl.CurrentThemeLocation -Force

    # [ScriptBlock]$Prompt = {
    #     $lastCommandFailed = $global:error.Count -gt $sl.ErrorCount
    #     $sl.ErrorCount = $global:error.Count

    #     #Start the vanilla posh-git when in a vanilla window, else: go nuts
    #     if(Test-IsVanillaWindow) {
    #         Write-Host -Object ($pwd.ProviderPath) -NoNewline
    #         Write-VcsStatus
    #         return '> '
    #     }

    #     Reset-CursorPosition
    #     Write-Theme -lastCommandFailed $lastCommandFailed
    #     return ' '
    # }



    # Set-Item -Path Function:prompt -Value $Prompt -Force
    Set-Item -Path Function:prompt -Value edh-prompt -Force
}
```

Run:
```
PS C:\WINDOWS\System32> import-module oh-my-posh
goo
gooSet-PSReadLineKeyHandler -Key Tab -Function Complete
gooGet-He
Get-HealthFault  Get-Help
gooGet-He
```

Run, output:
![image](https://user-images.githubusercontent.com/5379325/48316743-8ee79280-e59c-11e8-8956-4e3ec645fb7a.png)

**Also note that if I keep the _same_ write-string-only function and set it as my Write-Theme, with the original code in oh-my-posh the <tab> Complete does _not_ work, just as if it were for a more complex Write-Theme**

Also, the proper function of Complete can be had by modifying `Set-Prompt` like this: (of course this does not allow for $lastCommandFailed or other parameters to be passed in.

```

function Set-Prompt {
    Import-Module $sl.CurrentThemeLocation -Force

    # [ScriptBlock]$Prompt = {
    #     $lastCommandFailed = $global:error.Count -gt $sl.ErrorCount
    #     $sl.ErrorCount = $global:error.Count

    #     #Start the vanilla posh-git when in a vanilla window, else: go nuts
    #     if(Test-IsVanillaWindow) {
    #         Write-Host -Object ($pwd.ProviderPath) -NoNewline
    #         Write-VcsStatus
    #         return '> '
    #     }

    #     Reset-CursorPosition
    #     Write-Theme -lastCommandFailed $lastCommandFailed
    #     return ' '
    # }



    # Set-Item -Path Function:prompt -Value $Prompt -Force
    Set-Item -Path Function:prompt -Value Write-Theme -Force
}
```

**Comment by JanDeDobbeleer** [comment]
@erichiller can you check if the changes in #121 fix this? Should be available today.

**Comment by erichiller** [comment]
@JanDeDobbeleer - Just had time to test this.

It no longer is going all the way back to `PS>` but the characters aren't rendered properly. Example:
![image](https://user-images.githubusercontent.com/5379325/52178201-3b8e7600-2780-11e9-9ee3-61c14f118acf.png)
 results in:
![image](https://user-images.githubusercontent.com/5379325/52178200-316c7780-2780-11e9-8d38-2271f72a2ed5.png)

This is after using _any_ autotab completion.

Simply executing a command displays it as it should be:
![image](https://user-images.githubusercontent.com/5379325/52178217-5cef6200-2780-11e9-9b21-9f9f424f538c.png)

**Comment by daniel-chambers** [comment]
Hmm, I don't observe that behaviour:

![image](https://user-images.githubusercontent.com/1214352/52184375-8682b900-2866-11e9-980f-bb81b7ea4f31.png)

Perhaps it's a PSReadline version thing, since PSReadline is printing the prompt after a autocomplete tab? My version is PSReadline 2.0.0-beta3 in PowerShell Core 6.1.1. It also seems to be working okay with PSReadline 2.0.0-beta2 in Windows PowerShell 5.1.17763.134 (Windows 10 1809).

**Comment by erichiller** [comment]
Apparently the machine having issues was running psreadline beta 1. I upgraded just now and it seems to have fixed it. Thank you.

**Comment by JanDeDobbeleer** [comment]
Good to know. I'll close this one 🙏🏻
