### ISSUE TITLE
Weird symbols showing up after installation

### ISSUE THREAD

**Issue by swapneeldatta** [JanDeDobbeleer/oh-my-posh2#118]
After installation as per the docs and restarting my shell, it looks something like this.

![capture](https://user-images.githubusercontent.com/29889675/48463315-9eb3e080-e801-11e8-9aca-c98a1b177c88.PNG)

**Comment by DJPoland** [comment]
I fixed the issue by using [this](https://github.com/ryanoasis/nerd-fonts/blob/master/patched-fonts/Meslo/M/complete/Meslo%20LG%20M%20Regular%20Nerd%20Font%20Complete%20Mono.otf) font in ConEmu. Also in the ConEmu settings, make sure **Alternative font** is deselected in General->Fonts.

**Comment by JanDeDobbeleer** [comment]
Yes, this is indeed a font issue :-)

**Comment by VigneshNagendran** [comment]
I am still facing this issue. I deselected Alternative Fonts. Need help

**Comment by nwykes** [comment]
> I am still facing this issue. I deselected Alternative Fonts. Need help

Did you install a powerline font as instructed in the Readme and have it selected in your terminal?
