### ISSUE TITLE
Create a chocolatey installer

### ISSUE THREAD

**Issue by laurentkempe** [JanDeDobbeleer/oh-my-posh2#122]
It would be super nice to be able to install oh-my-posh using Chocolatey, like it is possible for [posh-git](https://github.com/dahlbyk/posh-git/tree/master/chocolatey)! 
Then I could add it to my [Cacao machine install script](https://github.com/laurentkempe/Cacao/blob/master/PrepareMyCacao.ps1#L81)

**Comment by digitalcoyote** [comment]
Any progress on this? I have a chocolatey AU package repo (automatically updates the package when it detects a new release). I'd be willing to setup the package and maintain it (I can also add this project's maintainer(s) as maintainers so that they can push manually if needed).

**Comment by digitalcoyote** [comment]
I've got a package ready, but I didn't want to push it in case someone else was already working on one (looks like no update since July though). ~~I'll hold off for a bit. If someone is working on one that better meets the needs of users than mine, just let me know and I'll add them as a maintainer and turn off my auo-updater for it so their package can be pushed instead.~~

I pushed an initial package so it could be reviewed and published. I can make a maintainer of this project the maintainer on Chocolatey if someone wants to publish a package with a different install script later. 

~~https://chocolatey.org/packages/oh-my-posh/0.2.1~~ incorrect link
https://chocolatey.org/packages/oh-my-posh/2.0.311

**Comment by JanDeDobbeleer** [comment]
It seems to be blocked due to automatic testing, you can publish this if you want, I don't mind not having to maintain it. Let's then make sure to add it to the README here. However, it might be interesting to ask people if they want to install Conemu or not (didn't check if it does).

**Comment by laurentkempe** [comment]
> However, it might be interesting to ask people if they want to install Conemu or not (didn't check if it does).

Do you mean while installing oh-my-posh?
If you mean that, then I hope we have a way to install it without asking, cause I want to have my system installed unattended!

**Comment by JanDeDobbeleer** [comment]
I thought it also installed ConEmu, might hwve misread that.

**Comment by laurentkempe** [comment]
I see now what you talked about, the description of the chocolatey package, in the previous link, is the one of Conemu, which is wrong! It should be the description of oh-my-posh

**Comment by digitalcoyote** [comment]
Srry that link was a self-rejected version of the package. I've updated it to the current one in moderation. ConEmu is currently listed as a chocolatey dependency. If it's not wanted in the package, I can remove it as a dependency.

**Comment by laurentkempe** [comment]
@digitalcoyote I would prefer not to have it as a dependency cause it is not needed to run oh-my-posh. People might prefer to use the new Windows Terminal for example.

**Comment by JanDeDobbeleer** [comment]
I agree with @laurentkempe , we should focus on making oh-my-posh available. Optionally we can ask people if they want to install ConEmu, but in all fairness nowadays there's more than option so chances are they're already using something that's available.

**Comment by digitalcoyote** [comment]
I pushed up a new version with the conemu requirement removed, and it looks like it's been approved.

**Comment by JanDeDobbeleer** [comment]
What are the next steps for this? It's still a manual process, should I include it here so we can update at the same time we push to the gallery?

**Comment by digitalcoyote** [comment]
I have it setup to check the releases page twice daily. If it detects a newer version than is currently on Chocolatey, it pushes a new package for that version.

**Comment by JanDeDobbeleer** [comment]
Cool. Might be good to update the README here in that case.

**Comment by digitalcoyote** [comment]
Oversight on my part, I thought I'd already made a PR for the readme, but it looks like I skipped it for some reason. I'll try to pull something together when I get back on my laptop.

**Comment by laurentkempe** [comment]
> I have it setup to check the releases page twice daily. If it detects a newer version than is currently on Chocolatey, it pushes a new package for that version.

Good! Otherwise I have setup a Azure DevOps release pipeline which you could copy to push to Chocolatey at each release! Let me know if you are interested.

**Comment by JanDeDobbeleer** [comment]
Available.
