### ISSUE TITLE
Hook for ConEmu working directory

### ISSUE THREAD

**Issue by farzadmf** [JanDeDobbeleer/oh-my-posh2#126]
Hi,

First of all, thank you for the great work.

There's one issue that I'm facing: according to [this link](https://conemu.github.io/en/ShellWorkDir.html), in order for ConEmu to be able to track you current working directory, you have to do some manipulation to the prompt, and if you look at [the example for `posh-git`](https://conemu.github.io/en/ShellWorkDir.html#PowerShellPoshGit), you can see that the `posh-git` module exposes an external variable that you can "run" to get the desired prompt created by `posh-git`, and then add things required by ConEmu.

It would be nice for this module to expose such a variable (or function) that you can call, which would return the prompt, because for me, if I want to change my prompt to `oh-my-posh`, I lose the ability to open new splits in the current directory.

Thank you

**Comment by calizarr** [comment]
I am also experiencing the same issue except in cmder (1.3.11) which uses ConEmu in the background.

**Comment by farzadmf** [comment]
@calizarr since I didn't hear from anyone here, I ended up manually changing the file in the `oh-my-posh` module on my local computer, and now it's working for me

**Comment by calizarr** [comment]
@farzadmf do you happen to have the changes you made available if you're willing to share?

**Comment by farzadmf** [comment]
Sure @calizarr why not, I modified the `Set-Prompt` function in `oh-my-posh.psm1` file (around line `40`) to be something like this:
```powershell
$prompt = (Write-Theme -lastCommandFailed $lastCommandFailed)
$loc = Get-Location

if ($env:ConEmuANSI -eq "ON")
{
  $prompt += "$([char]27)]9;12$([char]7)"
  if ($loc.Provider.Name -eq "FileSystem")
  {
    $prompt += "$([char]27)]9;9;`"$($loc.Path)`"$([char]7)"
  }
}

$prompt
```
I hope that helps
