### ISSUE TITLE
Lightning Bolt Causes Cursor Displacement

### ISSUE THREAD

**Issue by dapperdandev** [JanDeDobbeleer/oh-my-posh2#127]
It appears the lightning bolt emoji displaces the cursor. This confirmed in the agnoster theme. You can see from the gif that as I hit backspace, the character two-spaces back from the cursor gets deleted.

## Terminals
- VS Code Integrated Terminal
- Hyper.js / Powershell

![helloworld](https://user-images.githubusercontent.com/13296622/52447220-5f89e880-2aed-11e9-8a73-8793c493130d.gif)

## Workaround:
If the lightning bolt isn't a deal-breaker, comment out or edit:
```powershell
    #check for elevated prompt
    If (Test-Administrator) {
        $prompt += Write-Prompt -Object "$($sl.PromptSymbols.ElevatedSymbol) " -ForegroundColor $sl.Colors.AdminIconForegroundColor -BackgroundColor $sl.Colors.SessionInfoBackgroundColor
    }
```
 `Agnoster.psm1`

**Comment by nwykes** [comment]
I'm not able to reproduce this one.  Please list out the versions of oh-my-posh, powershell, poshgit, psreadline you're using.

**Comment by dapperdandev** [comment]
Sure thing.

posh-git: 0.7.3
oh-my-posh: 2.0.245
PowerShell: 5.1.17763.134
PSReadLine: 2.0.0
Hyper: 2.1.2

After doing some more testing, it seems isolated to using Hyper. I don't notice the problem in Cmder/Conemu. I opened a similar issue on Hyper's repo. I'm not sure if this should be considered an issue as "Hyper renders oh-my-posh themes incorrectly" or "oh-my-posh themes don't work correctly in Hyper".

**Comment by nwykes** [comment]
I'll reinstall hyper and powershell 5 and see if I get the same issue.  side note, I moved from hyper to Terminus a while back and have had a lot less issues.

**Comment by dapperdandev** [comment]
@nwykes Thanks for the sidenote. I'll check Terminus out. Looks nice.

**Comment by dapperdandev** [comment]
@nwykes I'd say your right. That literally took about 5 minutes to setup. And no displaced cursor.

**Comment by dapperdandev** [comment]
Dang. This issue is also present in the vs code terminal

**Comment by nwykes** [comment]
I'm seeing weirdness as well in vscode terminal when running as admin, which I normally don't do so hadn't noticed before.  My behavior is slightly different than your gif, spaces are doubled.

I'll see if I can figure anything out.

**Comment by JanDeDobbeleer** [comment]
This is not an issue with oh-my-posh so I'm going to close it.
