### ISSUE TITLE
Can't change username

### ISSUE THREAD

**Issue by dakom** [JanDeDobbeleer/oh-my-posh2#128]
I add `$DefaultUser = 'dakom'` to my $PROFILE but it has no effect...

**Comment by nwykes** [comment]
$DefaultUser doesn't change your user name.  If it is set to your username you're logged in as, then the username@computer will be hidden from the prompt in themes that support it.

What behavior are you hoping to achieve?

**Comment by dakom** [comment]
Oh... I'd like to have a unicode symbol instead of that.

So I guess step 1 would be to hide the default- but then how do I add a new custom string?

**Comment by nwykes** [comment]
You might have to create a custom theme to do what you're looking for.  

Copy an existing one that's close to what you're looking for to the directory indicated by $ThemeSettings.MyThemesLocation, change the name, and modify as desired. 

Then `Set-Theme mynewtheme`

**Comment by dakom** [comment]
Feel free to close - duplicating the theme and playing with it there works perfectly :)
