### ISSUE TITLE
Cmder text color

### ISSUE THREAD

**Issue by dakom** [JanDeDobbeleer/oh-my-posh2#129]
The regular text when running powershell through Cmder seems to be stuck on blue... 

![image](https://user-images.githubusercontent.com/6406986/52775187-bb052a80-3047-11e9-8fc1-fe582787187e.png)

For the sake of comparison, here's running in regular powershell (ligatures and things don't work... not sure how to fix that?)

![image](https://user-images.githubusercontent.com/6406986/52775255-e5ef7e80-3047-11e9-8d53-d7a9c9ee52f6.png)

**Comment by dakom** [comment]
e.g. I want the regular text to be white-ish but it's blue...

**Comment by mikesigs** [comment]
I am having a similar problem, but mine is with background color staying blue, not foreground. Haven't solved it yet.

Also, for PowerShell to show the ligatures you need to change the font it uses to a PowerLine font.

**Comment by mikesigs** [comment]
My issue seems to be something to do with my custom theme. If I have `Set-Theme mytheme` in my powershell profile it messes up the background color. But if I don't set the theme in the profile, but rather wait til the prompt loads and then call `Set-Theme mytheme` manually, it does not mess up the background color.

**Comment by mikesigs** [comment]
I've got a few new discoveries, and a simple theme to reproduce the issue.

It appears that the first call to `Write-Prompt` (that produce a non-empty output) is determining the default background for the rest of the prompt.

Steps to reproduce:
1) Create a new theme called `bug.psm1` in the directory specified by `$ThemeSettings.MyThemesLocation`
2) Copy the following contents into `bug.psm1`

```powershell
function Write-Theme {
    param(
        [bool]
        $lastCommandFailed,
        [string]
        $with
    )

    # Set the BackgroundColor of the first call to Write-Prompt
    $prompt = Write-Prompt -Object "BOOM" -BackgroundColor ([ConsoleColor]::Magenta)
    # Setting a different BackgoundColor will change it for the " > ", but not the rest of the prompt input
    $prompt = Write-Prompt -Object " > " -BackgroundColor ([ConsoleColor]::Black)
    $prompt += ' '
    $prompt
}
```

3) Add a call to `Set-Theme bug` into your PowerShell profile.
4) Open a new Cmder window and type a command, e.g. `ls`
5) You should see that the background color of `ls` (and all the following output) is dark blue

![image](https://user-images.githubusercontent.com/811177/53123306-fc00b180-3515-11e9-9571-841be56c78f5.png)


I did find a strange workaround. If you change your PowerShell profile to set the theme with the `-Verbose` flag, i.e. `Set-Theme bug -Verbose` then the background issue goes away!

**Comment by APErebus** [comment]
Oh man, I was wondering how to solve this one. Been annoying the hell out of me ever since I updated to Windows 10 1903.

I get the same behavior in Powershell & Powershell Core and I can confirm adding `-Verbose` fixes it 😕

**Comment by JanDeDobbeleer** [comment]
This has to be a bug in Cmder as I can't reproduce this in ConEmu.

![image](https://user-images.githubusercontent.com/2492783/60962277-31177000-a30e-11e9-98b0-9b4545a24dad.png)

**Comment by gluons** [comment]
**Workaround:**

For me, I'm using PowerShell task with `-NoLogo`.  
After I remove `-NoLogo`, my text color back to normal.

**Comment by gluons** [comment]
ConEmu text color is also broken for me if I use `-NoLogo`. I'm using Windows version 1903.

![ภาพ](https://user-images.githubusercontent.com/4688092/64189080-d299e880-ce9d-11e9-895b-093fd274b038.png)

**Comment by gluons** [comment]
I found more way to solve my problem.  
For my case, I use Cmder task with command `*PowerShell -ExecutionPolicy Bypass -NoLogo` (Run PowerShell as admin). I use **Paradox** theme.

I found out that if I remove (or comment out) this line of `Paradox.psm1` file, wrong color problem solved. (Workaround)

https://github.com/JanDeDobbeleer/oh-my-posh/blob/ddc47274a311d563c2cbb9404d870f9fbd11779a/Themes/Paradox.psm1#L20-L22

```diff
If (Test-Administrator) {
-    $prompt += Write-Prompt -Object "$($sl.PromptSymbols.ElevatedSymbol) " -ForegroundColor $sl.Colors.AdminIconForegroundColor -BackgroundColor $sl.Colors.SessionInfoBackgroundColor
}
```

---

**Before:**
![ภาพ](https://user-images.githubusercontent.com/4688092/64266036-223fe900-cf5e-11e9-832d-a22c6836c91c.png)

**After:**
![ภาพ](https://user-images.githubusercontent.com/4688092/64266107-3c79c700-cf5e-11e9-85c3-ee8dd821fb33.png)

---

@JanDeDobbeleer Do you face this problem now? Could you investigate this problem with current info that I found?

**Comment by JanDeDobbeleer** [comment]
I have no idea why this would occur as `-NoLogo` only hides the copyright banner at startup. Nothing else. On my Mac I'm unable to reproduce this (although that's running` pwsh`). Can you check if this also occurs on PowerShell Core?

**Comment by dorseytm** [comment]
I think the issue I'm having may be related to this issue.  See the screenshot below:

![image](https://user-images.githubusercontent.com/1766357/78044856-33f63d00-7343-11ea-810b-b8032a5a2bc5.png)

I've been unable to find a way to change the foreground color so I can get the rest of the prompt to show when using this Solarized Light theme.

**Comment by christanaka** [comment]
Windows 10 1909
ConEmu 200713
oh-my-posh 2.0.465
Agnoster Theme

```powershell
# My $PROFILE
Import-Module posh-git
Import-Module oh-my-posh

Set-Theme Agnoster
$DefaultUser = $env:USERNAME
```

In a normal console all text has a background color.
![Capture](https://user-images.githubusercontent.com/2514771/90429957-da897300-e083-11ea-926f-d07b13114283.PNG)

In an admin/elevated console the background issue is fixed, but the text color is wrong in some (not all) cases.

In this case only the path text color is wrong.
![case1](https://user-images.githubusercontent.com/2514771/90430186-3c49dd00-e084-11ea-9355-f1c3e3618736.PNG)

In this case only the output text color is wrong.
![case2](https://user-images.githubusercontent.com/2514771/90430346-83d06900-e084-11ea-858b-c61019c9aa25.PNG)

The ConEmu `-NoLogo` switch has no effect on any of the colors.
Removing the line that sets the `$DefaultUser` from my `$PROFILE` fixes all color bugs completely for normal consoles, but not for admin consoles. (Probably the same issue from https://github.com/JanDeDobbeleer/oh-my-posh/issues/201)
Adding the `-Verbose` flag to `Set-Theme` fixes the background color bug, but also adds the text color bug for normal consoles.

**Comment by christanaka** [comment]
Just tested in PowerShell 7 and the issue is fixed. Previously I was using PowerShell 5.1.

**Comment by gluons** [comment]
![ภาพ](https://user-images.githubusercontent.com/4688092/95739270-c1ccc080-0cb4-11eb-96cb-2063433b20a7.png)

![ภาพ](https://user-images.githubusercontent.com/4688092/95739715-7961d280-0cb5-11eb-894d-7fbbf9a20d37.png)

![ภาพ](https://user-images.githubusercontent.com/4688092/95739877-b332d900-0cb5-11eb-8670-6d0bfb34b78a.png)

It still doen't work on my PowerShell 7. All texts are yellow.

---

`$PSVersionTable`:
```
Name                           Value
----                           -----
PSVersion                      7.0.3
PSEdition                      Core
GitCommitId                    7.0.3
OS                             Microsoft Windows 10.0.19041
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

---

Could you reopen this issue? Or I should create new issue instead?

**Comment by JanDeDobbeleer** [comment]
@gluons that's for 2, the fix is in V3 😉

**Comment by gluons** [comment]
OK. Thank you. v3 is amazing.  
I'll keep an eye on v3. 😘

**Comment by yugawara** [comment]
I found a solution (at least this removed the bug for me :-) )- 
Put the set-theme line inside this function, in $PROFILE.
```ps1
function prompt {Set-Theme Paradox}
```

**Comment by JanDeDobbeleer** [comment]
> Put the set-theme line inside this function

@yugawara that makes no sense at all. `Set-Theme` also calls the prompt function...

**Comment by yugawara** [comment]
@JanDeDobbeleer
I noticed that this problem did not happen if I set-theme manually after the Cmder Poweshell started, so I was looking for a way to delay Set-Theme as long as possible.   So I thought, how about putting it inside the prompt function?   Anyway, I went to sleep as soon as I found this so I will check again today that this indeed worked 😄

**Comment by yugawara** [comment]
Yes, I rebooted my computer just now and it still works.

When Cmder starts (my default is set to Powershell), the first prompt is
'''
PS>
'''
But all the subsequent prompts will be the pretty prompt as set by the theme 😄

**Comment by JanDeDobbeleer** [comment]
@yugawara do you have the same issue on V3?

**Comment by yugawara** [comment]
Hi,
Sorry, I have not tried V3 yet ( I tried to install it but either I couldn't' figure out how to do it or ran out of time😅)

**Comment by yugawara** [comment]
Another comment - it turns out that this bug appeared only with CMDER terminal.

This workaround is not necessary with the latest version of Windows Terminal Preview that I have just tried.

I was forced to use CMDER originally due to the corporate Windows 10 build version that I had no control over 😅
