### ISSUE TITLE
Multiline text pasting

### ISSUE THREAD

**Issue by dotps1** [JanDeDobbeleer/oh-my-posh2#13]
I know this probably is not your fault, and is probably an issue of ConEmu, but I thought I would start here.  Pasting multiline text in the shell seems just horrible, doesn't honor any line breaks so it of course will not run.  would this be a setting of ConEmu or oh-my-posh?

**Comment by JanDeDobbeleer** [comment]
Should be a setting in ConEmu as I can paste across multiple lines.

**Comment by JanDeDobbeleer** [comment]
Btw, check the Gitter channel if you feel like chatting about this: https://gitter.im/oh-my-posh/general
