### ISSUE TITLE
Strange pointer position in some themes with vscode

### ISSUE THREAD

**Issue by sigmarising** [JanDeDobbeleer/oh-my-posh2#132]
![gif](https://user-images.githubusercontent.com/25470568/54584813-53316d80-4a53-11e9-97e0-a7c73deb6efe.gif)

As we can see from the gif, when I use the agnoster theme, the position of the pointer seems very strange, it left some white space after the character I typed.

This "space between pointer and character" phenomenon appear in below themes:
* agnoster (many space there, especially when I type the whitspace)
* Avit(one space there)
* Fish(oh my god)
* PowerLine

The Pointer is normal in below themes:
* Darkblood
* Honukai
* Paradox
* robbyrussell
* Sorin
* tehrob

[cap.zip](https://github.com/JanDeDobbeleer/oh-my-posh/files/2981882/cap.zip)
You can see more in this video.

My enviroment:
```shell
sigmarising D\..\test git: master ≢ +1 ~0 -0 ! ❯❯❯ $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.1.3
PSEdition                      Core
GitCommitId                    6.1.3
OS                             Microsoft Windows 10.0.17763
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0


sigmarising D\..\test git: master ≢ +1 ~0 -0 ! ❯❯❯ Get-InstalledModule

Version              Name                                Repository           Description
-------              ----                                ----------           -----------
2.0.249              oh-my-posh                          PSGallery            Theming capabilities for the PowerShell prompt in ConEmu
0.7.3                posh-git                            PSGallery            Provides prompt with Git status summary information and tab completion for Git commands, parameters, remotes and branch n...
2.0.0-beta3          PSReadLine                          PSGallery            Great command line editing in the PowerShell console host
```

**Comment by AlexanderJLiu** [comment]
@sigmarising  Issue #93 may help you.

**Comment by sigmarising** [comment]
@AlexanderJLiu I update the posh-git to the latest preview version, but the problem is still here.

These days I find an issus closed in vscode Repository.
It seems that my problem will be handled when the CONPTY released on windows 10 1903.
https://github.com/Microsoft/vscode/issues/67789#issuecomment-478310396

When the new windows10 is released, I will try whether this will be fixed by conpty.

**Comment by JanDeDobbeleer** [comment]
I'll leave this open until there's more information on this one.

**Comment by sigmarising** [comment]
I update to the new Windows10 1903 which add the conpty support. The conpty is supported by the vscode. And when I switch from winpty to conpty in vscode, everything works fine! No more strange pointer position!

![1](https://user-images.githubusercontent.com/25470568/58217487-97800900-7d35-11e9-88e9-16d35c44b662.gif)

This issue maybe a bug in the old winpty, switching to the new conpty can handle this problem.
