### ISSUE TITLE
Icons not showing up correctly for Powershell Core

### ISSUE THREAD

**Issue by Arbelac** [JanDeDobbeleer/oh-my-posh2#133]
Hi,

As you can see below screenshot I am unable display theme icons. 

https://imgur.com/a/rMfy4E4

Thanks in advance,

**Comment by nwykes** [comment]
Looks like you're not using a powerline font.  Please see the prerequisites in the readme.

**Comment by anderl80** [comment]
I have the same issue.. I have installed Powerline Fonts, however it is not displaying correctly in PowerShell, as well in Windows terminal.

**Comment by amirkabiri** [comment]
same problem too

**Comment by reisdev** [comment]
Same for me! Powerline fonts updated. Icons still not showing

**Comment by nwykes** [comment]
you probably want to open a new issue since this was closed over a year ago.

I can say though that there is no issue running powershell core.

**Comment by shubhsk88** [comment]
same problem happening for me as well

https://prnt.sc/td5o0o

**Comment by rescenic** [comment]
[**@shubhsk88**](https://github.com/shubhsk88) commented on [Jul 7, 2020, 12:23 PM GMT+7](https://github.com/JanDeDobbeleer/oh-my-posh/issues/133#issuecomment-654608884 "2020-07-07T05:23:11Z - Replied by Github Reply Comments"):
> same problem happening for me as well
> 
> [https://prnt.sc/td5o0o](https://prnt.sc/td5o0o)

@shubhsk88 Try using Nerd Fonts: https://www.nerdfonts.com/font-downloads

**Comment by ashikur11** [comment]
same problem as well :( 
![image](https://user-images.githubusercontent.com/11086908/87247119-9ba84200-c473-11ea-8ae9-4a1042cb4d12.png)
