### ISSUE TITLE
the space in the filenames

### ISSUE THREAD

**Issue by 3x00** [JanDeDobbeleer/oh-my-posh2#135]
how to 'cd' the dir which it has space in the dir_name?
if I use 'cd' like this : cd "Program Files"   it works well,but I can't use the tab to completing the path.

**Comment by JanDeDobbeleer** [comment]
Hi @3x00 this as such has nothing to do with oh-my-posh, if you want this functionality you can add the following to your `$PROFILE`:

`Set-PSReadlineKeyHandler -Key Tab -Function MenuComplete`
