### ISSUE TITLE
MyThemesLocation is broken on *nix.

### ISSUE THREAD

**Issue by sizur** [JanDeDobbeleer/oh-my-posh2#139]
$Global:ThemeSettings.MyThemesLocation doesn't use the [System.IO.Path]::DirectorySeparatorChar and is a hardcoded string in Windows path format that doesn't resolve on *nix platforms.

(Resolve-Path ~\some\path) will fix the path format.  If it doesn't exist, [void](New-Item -ItemType Directory -Force $Global:ThemeSettings.MyThemesLocation) will fix that.

Maybe $IsWindows should be switched on for a more sensible default path on both, Windows and non-Windows platforms.

**Comment by JanDeDobbeleer** [comment]
Fixed in the latest release.
