### ISSUE TITLE
Theme is not applied until running Show-Themes

### ISSUE THREAD

**Issue by kelchm** [JanDeDobbeleer/oh-my-posh2#14]
I'm probably missing something obvious here, but the theme I configured using `Set-Theme` is not applied within a new terminal session until I run `Show-Themes`.  Any ideas on what the issue may be?

**Comment by JanDeDobbeleer** [comment]
I'll have a look asap. I don't think I've seen that before but I'll try to reproduce it.

**Comment by Liquidmantis** [comment]
I haven't seen that either.  I'm calling Set-Theme in my user profile after importing oh-my-posh, then assigning new colors to $themeSettings.

**Comment by JanDeDobbeleer** [comment]
I tried to see what might cause this but can't find a way that results to this.

My configuration ($PROFILE):

```
Import-Module -Name posh-git -ErrorAction SilentlyContinue
Import-Module oh-my-posh
Set-Theme -name 'avit'
```

When I open a new window in ConEmu, it's always set to Avit.
The only thing Show-Themes does is list what's in the folder.
It doesn't even make much sense as the only function that can override the current theme is Set-Theme which will import the theme and override the Write-Theme function used in the prompt. As that one is used in Start-Up and Set-Theme, it can only be called from there.

Can you share your $PROFILE? I'd really love to be able to explain this :-)
You can easily cp this using `Get-Content $PROFILE | clip`
