### ISSUE TITLE
 Extra letter when using anaconda

### ISSUE THREAD

**Issue by ghost** [JanDeDobbeleer/oh-my-posh2#140]
Like this
![image](https://user-images.githubusercontent.com/8176393/56428023-8b48fc00-62f0-11e9-8503-7d6bb8c8cb9a.png)
How to remove the letter in font of `django` ?

**Comment by JanDeDobbeleer** [comment]
Interesting, does the virtual env use the name `  django`? I can strip it before using the actual value.

**Comment by ghost** [comment]
Yes. I use this command to create env
```
conda create -n django python=3.7
```

System language: Simplified-Chinese
System Version: 17763.437

**Comment by JanDeDobbeleer** [comment]
Wait, now that I'm a bit more awake, this is probably the `VirtualEnvSymbol` that isn't set.
Try running the following and verify the output again:

```powershell
PS:> $ThemeSettings.PromptSymbols.VirtualEnvSymbol = "ENV"
```

**Comment by ghost** [comment]
like this ![image](https://user-images.githubusercontent.com/8176393/61015741-8069a900-a3bf-11e9-83a5-47939959e4de.png) ?

**Comment by JanDeDobbeleer** [comment]
Yes. Thanks! So, normally there's a gear icon instead of ENV, which for some reason is empty in your setup. If you add the icon of your choice, the initial space (which is actually the one between the icon and the env name) will be gone.

**Comment by ghost** [comment]
Thank you.

**Comment by ManuZhu0728** [comment]
> Yes. Thanks! So, normally there's a gear icon instead of ENV, which for some reason is empty in your setup. If you add the icon of your choice, the initial space (which is actually the one between the icon and the env name) will be gone.

Sir how can I add an icon btw? My system language is also simplified Chinese and after the command it shows `ENV`, but I prefer an icon. Thank you sir
![image](https://user-images.githubusercontent.com/62131027/79228700-7b78df00-7e94-11ea-80b3-d4b6cc8ceb85.png)

**Comment by j178** [comment]
@lbcz-tian Change to a nerd font(I'm using `JetbrainsMono NF`), and it'll look like this:
![image](https://user-images.githubusercontent.com/10510431/80860626-8a84cd00-8c9b-11ea-8976-7e2308896261.png)

**Comment by ManuZhu0728** [comment]
@JanDeDobbeleer wow thanks😆that looks much better than ENV😂
