### ISSUE TITLE
Cannot display VirtualEnvSymbol

### ISSUE THREAD

**Issue by whimian** [JanDeDobbeleer/oh-my-posh2#142]
Cannont dispaly VirtualEnvSymbol with font "DejaVu Mono for Powerline".

**Comment by JanDeDobbeleer** [comment]
Hey @whimian, in that case you need to select a different icon. I assume it displays the square with the question mark in it? You can select a new icon by settings the `$ThemeSettings.PromptSymbols.VirtualEnvSymbol` variable in your `$PROFILE`

**Comment by whimian** [comment]
Thank you for the reply. @JanDeDobbeleer  I'm just wondering what the default look like.

**Comment by bqstony** [comment]
@whimian: if someone has the same problem... my solution to fix the font problem is descripted well in the video from scott: https://docs.microsoft.com/en-us/windows/terminal/tutorials/powerline-setup 
I use now the fond `Cascadia Code PL`
