### ISSUE TITLE
SSH + tmux breaks theme colors

### ISSUE THREAD

**Issue by mhall** [JanDeDobbeleer/oh-my-posh2#147]
I am using oh-my-posh with the Agnoster theme:

![103241](https://user-images.githubusercontent.com/15344417/57082989-d0443980-6cc5-11e9-8271-febd4f96a39a.png)

After connecting to a Unix server over ssh (using the native Win32-OpenSSH client) and running tmux on the remote server, when I close the ssh connection all oh-my-posh coloring is lost and I have to restart my terminal to get back to a properly-looking prompt:

![101941](https://user-images.githubusercontent.com/15344417/57083103-05e92280-6cc6-11e9-8c93-2edd731a97bb.png)

tmux is definitely involved in this issue -- if I do not use it (on the remote server), proper oh-my-posh coloring persists after closing ssh. The screenshots above are from Hyper but I verified the same problem occurs in a normal PowerShell window. I also tried the beta version of posh-git as suggested in another issue but that did not have any effect.

To reproduce:

- `ssh <server>`
- `tmux attach`
- `<Enter>~.`

and note that oh-my-posh colors are gone as shown in the second screenshot above. Any suggestions on how I might remedy this?

**Comment by krokofant** [comment]
I'm curious if you run `Set-Theme Agnoster` after the connection is closed, are the correct theme colors applied?

**Comment by mhall** [comment]
Just tried that, and unfortunately not -- the prompt remains the same after `Set-Theme Agnoster`.

**Comment by JanDeDobbeleer** [comment]
Can you do me a favor and check if this also occurs on ConEmu? I fear there isn't much I can do if tmux overwrites your console's colors.

**Comment by JanDeDobbeleer** [comment]
Closing due to no response.

**Comment by mhall** [comment]
@JanDeDobbeleer I did not see your original request for more info. My apologies. I just tested on ConEmu and the same issue occurs there.
