### ISSUE TITLE
Branch name not displaying.

### ISSUE THREAD

**Issue by deadwards90** [JanDeDobbeleer/oh-my-posh2#148]
![image](https://user-images.githubusercontent.com/9741849/57434606-38999a80-7233-11e9-82b0-b446cce43106.png)

As above, branch name is just not there.

Currently looks like this when opening it up, and it happens on multiple terminal emulators (ConEmu, FluentTerminal and plain Powershell).

If I remove oh-my-posh then it shows in posh-git correctly.

Any ideas? This is on my work machine, works fine at home so I think it's something I've done but no idea what.

**Comment by JanDeDobbeleer** [comment]
Let's see if we can debug this.
The module gets the branch name from posh-git's `Get-VCSStatus`, if you use that function directly in your PowerShell console it will display the branch name like in this sample:

```shell
PS:> Get-VCSStatus

Working      : {}
Branch       : master
Index        : {}
Upstream     : origin/master
RepoName     : oh-my-posh
HasUntracked : False
BehindBy     : 0
UpstreamGone : False
HasWorking   : False
StashCount   : 0
AheadBy      : 0
GitDir       : C:\Users\jan\Git\oh-my-posh\.git
HasIndex     : False
```
After receiving this information, the branch name is formatted by the following function:

```powershell
function Format-BranchName {
    param(
        [string]
        $branchName
    )

    if($spg.BranchNameLimit -gt 0 -and $branchName.Length -gt $spg.BranchNameLimit) {
        $branchName = ' {0}{1} ' -f $branchName.Substring(0, $spg.BranchNameLimit), $spg.TruncatedBranchSuffix
    }
    return " $branchName "
}
```
Where `$spg` is a pointer to `$GitPromptSettings` from `posh-git`, the output of that one could also come in handy to see what the function above will do.

**Comment by deadwards90** [comment]
Well this is weird.

I basically get the `git status` output when I run `Get-VCSStatus`

**Comment by JanDeDobbeleer** [comment]
@dantheman999301  In the `Get-VCSStatus` object?

**Comment by JanDeDobbeleer** [comment]
Can you run `get-command get-vcsstatus`?

**Comment by deadwards90** [comment]
```
❯ get-command get-vcsstatus

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Function        Get-VCSStatus                                      2.0.263    oh-my-posh
```

When I run `Get-VCSStatus`  on a git repo on master...

```
❯ Get-VCSStatus
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
```

Going to guess I've screwed something up here!

**Comment by JanDeDobbeleer** [comment]
Interesting, I'm puzzled. Might need to add some debug functionality for this one.

EDIT: Actually, I'm going to have a look at what the posh-git command does and if there's a trigger to display that raw information.

**Comment by JanDeDobbeleer** [comment]
@dantheman999301 alright, can you set `$GitPromptSettings.Debug = $true` and run `Get-VCSStatus` again?
I'm also interested to see what `Get-GitStatus` produces.

**Comment by deadwards90** [comment]
![image](https://user-images.githubusercontent.com/9741849/60974246-aa6c8e00-a321-11e9-9feb-ff5fb6509fb5.png)

Even stranger.

**Comment by JanDeDobbeleer** [comment]
Cool. We're getting closer though. I suspect something overrides `Get-GitStatus`. That one should come from `posh-git` but as I do not see any debug output, I suspect that's the culprit. Can you call `get-command Get-GitStatus` to see if it's actually from `posh-git` or not?

**Comment by deadwards90** [comment]
You are 100% correct and I just found it deep in my profile. I was overriding it so I could alias `git status` to `gst`.

After all of that!

Thanks for your help

**Comment by JanDeDobbeleer** [comment]
It was a lovely ride, we all learned something today :-)
