### ISSUE TITLE
Add separator between branch status and pending changes in prompt

### ISSUE THREAD

**Issue by thomaslevesque** [JanDeDobbeleer/oh-my-posh2#149]
Currently, the branch status (wether the branch is behind / ahead of upstream or up to date) is shown close to the "pending changes" status, without a separator. It makes things a little confusing:

> my-branch ↑1 ↓1 ~1 -0 !

On the other hand, there's a clear separation between staged and unstaged changes:

> my-branch ≣ +0 ~1 -0 | ~2 -0 !

(it could probably be even better, e.g. a different color, as in the default posh-git prompt, but it's another issue)

I suggest introducing a separator between branch status and pending changes to make the prompt more readable. The whole thing (with unsynced commits, staged and unstaged changes) would look like this:

> my-branch ↑1 ↓1 | +0 ~1 -0 | ~2 -0 !

**Comment by thomaslevesque** [comment]
Thanks @JanDeDobbeleer!

**Comment by JanDeDobbeleer** [comment]
Sorry it took so long, I need to show more love on a regular basis but it ain't easy combining life and everything :-)

**Comment by thomaslevesque** [comment]
No need to apologize, I know what it's like ;)
