### ISSUE TITLE
character cannot be displayed

### ISSUE THREAD

**Issue by czhang03** [JanDeDobbeleer/oh-my-posh2#15]
I have installed the latest version of windows 10 and latest version of Powerline fonts, and I am using `Meslo LG M for Powerline` like you did in the readme.

It seems like 2 of the characters cannot be displayed:
![capture](https://cloud.githubusercontent.com/assets/10100995/18025018/5de66816-6be9-11e6-9b68-117cdb6ab02f.PNG)

they are `BranchUntrackedSymbol` and `BranchIdenticalStatusToSymbol` what do I need to change for this to work?

**Comment by czhang03** [comment]
it seems like only 2262 and 2263 is missing:

![capture](https://cloud.githubusercontent.com/assets/10100995/18025062/78b8d820-6beb-11e6-9c88-9fdaa5b33aaa.PNG)

**Comment by JanDeDobbeleer** [comment]
That's strange, maybe something changed in the last version of the fonts. I'll check asap and update with the (hopefully new) chars.

**Comment by JanDeDobbeleer** [comment]
It's actually quite weird as the fonts have not been updated and my output does show them.

![image](https://cloud.githubusercontent.com/assets/2492783/18026310/71eef9a0-6c42-11e6-9467-a64fbcb377d8.png)

But maybe the ConEmu settings may have something to do with it.
These are mine, can you check and adjust where needed?

![image](https://cloud.githubusercontent.com/assets/2492783/18026315/9480a220-6c42-11e6-8cb0-51155e87cf76.png)

Keep me posted!

**Comment by czhang03** [comment]
Our setting are exactly the same... even for the font size...

I am looking in to the character map to see what goes wrong.

**Comment by czhang03** [comment]
hum... I looked into the character map... and it did show them:

![capture](https://cloud.githubusercontent.com/assets/10100995/18026383/ee9a4174-6c12-11e6-84ca-131da112389d.PNG)
![capture1](https://cloud.githubusercontent.com/assets/10100995/18026387/ff3efc72-6c12-11e6-959a-da1048abbfab.PNG)

it may related to conemu version or powershell output encoding or stuff. I will try to upgrade to the latest version of conemu and try again.

**Comment by czhang03** [comment]
okay, this problem is solved by upgrading to the latest version of conemu and set the `Font Charset` to `ansi`.

Thanks man.

**Comment by atruskie** [comment]
Just leaving a note for anyone else who comes across this:

I needed to disable the `Alternative font (pseudogrpahics, CJK, etc.)` checkbox to get the missing symbols to work.
