### ISSUE TITLE
Breaks posh-git file completion

### ISSUE THREAD

**Issue by Porges** [JanDeDobbeleer/oh-my-posh2#16]
There should be something like this before (or after) printing the prompt. 

```
$Global:GitStatus = Get-GitStatus
```

Without this, the file statuses are never updated in posh-git and so autocompletion for files (e.g. "git add ....") doesn't work.

e.g. try:

```
echo foo > foo
git add <TAB>
```

This should complete to foo automatically.

**Comment by JanDeDobbeleer** [comment]
Good find. I hardly ever add files manually so I didn't notice this yet. I'll see if I can fix this this evening.

**Comment by Porges** [comment]
Thanks!

**Comment by JanDeDobbeleer** [comment]
Yw!
