### ISSUE TITLE
Support for Windows Terminal?

### ISSUE THREAD

**Issue by thomaslevesque** [JanDeDobbeleer/oh-my-posh2#162]
I know that the project description states that oh-my-posh is only for ConEmu, but it mostly works in [Windows Terminal](https://github.com/microsoft/terminal) as well. Is this something you intend to support?

I'm using it on 2 different machines. Here are the main issues I'm seeing:
- Oh-my-posh doesn't set the console title (might be related to #159; it used to work when I set `$WindowTitleSupported` to true, but the relevant code has been removed)
- On one of my machines, the font (Meslo LG M Regular for Powerline) doesn't render correctly and there's some padding between the characters, not sure why (probably an issue with Windows Terminal itself, since oh-my-posh doesn't handle rendering)

**Comment by deadwards90** [comment]
Your second point is definitely a Windows Terminal bug related to fonts which should be fixed in upcoming versions. If currently only works nicely with Powerline fonts that are completely monospaced.

**Comment by thoemmi** [comment]
I've also noticed that oh-my-posh does not update the title when using ConEmu or Windows Terminal. However, as far as I can see it's **not** related to #159. Last year the window title handling was re-written in https://github.com/dahlbyk/posh-git/pull/597, and I guess this broke oh-my-posh.

**Comment by thomaslevesque** [comment]
Another issue I noticed in Windows Terminal, but not in ConEmu: `$LASTEXITCODE` always returns 0, and `$?` always returns True, whether the previous command succeeded or failed.

It's at least partly due to Windows Terminal (the behavior is normal in ConEmu), and partly due to oh-my-posh (the behavior is normal if I don't use oh-my-posh).

This might be related to #170, although that one also happens in ConEmu

(I'm reporting this here rather than opening a specific issue, since Windows Terminal isn't officially supported)
