### ISSUE TITLE
Adding Custom Colors

### ISSUE THREAD

**Issue by arnydo** [JanDeDobbeleer/oh-my-posh2#164]
What is the process for setting a custom color that is not a console color?

For example, how would I properly set the following if I am not using one of the available console colors?

```
$sl.Colors.PromptForegroundColor = "#FFFFFF"
```

Thank you.

**Comment by JanDeDobbeleer** [comment]
That's white right? You can't do that yet as far as I'm aware. PowerShell only supports standard colors (see [here](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/write-host?view=powershell-6#parameters))
