### ISSUE TITLE
How do I use the Failed Command Indication?

### ISSUE THREAD

**Issue by Kvoo** [JanDeDobbeleer/oh-my-posh2#166]
A coworker of mine told me it works, but I just can't get wrong commands to show up red. How do i configure this?

**Comment by JanDeDobbeleer** [comment]
You shouldn't have to configure it. It works out of the box although it was noticed that if you happen to use Windows Terminal, it can get wonky (seems fixed now).

**Comment by JanDeDobbeleer** [comment]
No response. Nothing but ❤️ though.
