### ISSUE TITLE
Hides last exit code in vanilla windows

### ISSUE THREAD

**Issue by Porges** [JanDeDobbeleer/oh-my-posh2#17]
In "vanilla" windows, LASTEXITCODE is hidden:

```
> powershell.exe -Command "Exit 123"
> echo $LASTEXITCODE
True
```

This should output 123.

**Comment by JanDeDobbeleer** [comment]
Easily fixable, the piece of code which causes that is still from PS-Config I think. I'll fix it this evening if all goes well.

**Comment by Porges** [comment]
Thanks!

**Comment by JanDeDobbeleer** [comment]
Yw!
