### ISSUE TITLE
With PowerShell Core, oh-my-posh always shows an error icon in the prompt

### ISSUE THREAD

**Issue by thomaslevesque** [JanDeDobbeleer/oh-my-posh2#170]
With PowerShell Core, the prompt always shows the error icon (red cross), whether or not there was the previous command failed (even if I entered an empty command).

![image](https://user-images.githubusercontent.com/1864281/65705220-4b005d80-e088-11e9-95d6-974a78f9df77.png)

**Comment by xasx** [comment]
I cannot reproduce that with PowerShell 7.0.0-preview.5
under Fedora Linux 30

What's your system/pwsh version?

**Comment by thomaslevesque** [comment]
@xasx

```
❯ $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.2.3
PSEdition                      Core
GitCommitId                    6.2.3
OS                             Microsoft Windows 10.0.18362
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

I guess it could be a Window-specific issue, or maybe it was fixed in pwsh 7. Anyway, I reproduced it on my work an home PCs.

**Comment by nwykes** [comment]
I haven't seen this issue on any version of powershell core from the betas through 6.2.3 and 7.0 previews.  What version of oh-my-posh are you running?

**Comment by thomaslevesque** [comment]
> What version of oh-my-posh are you running?

oh-my-posh: 2.0.311
posh-git: 0.7.3

**Comment by JanDeDobbeleer** [comment]
I can't reproduce this one, can you check what `$error` displays, maybe something is wrong elsewhere or in the config.

**Comment by thomaslevesque** [comment]
I had missed this requirement in the README:

> In case you're running this on PS Core, make sure to also install version 2.0.0-beta1 of PSReadLine

I had an older version of PSReadLine. After updating it, I no longer see the error.

Sorry about the noise.

**Comment by JanDeDobbeleer** [comment]
No worries, thanks for replying!
