### ISSUE TITLE
In VS Code integrated terminal, the cursor is offset.

### ISSUE THREAD

**Issue by crmckenzie** [JanDeDobbeleer/oh-my-posh2#172]
In the VS Code Integrated Terminal, the cursor is weirdly offset. In the below screenshot, the cursor is all the way to the left yet it shows up to the right of the left-most character. 

The theme is Agnoster. Any idea why?

![image](https://user-images.githubusercontent.com/947569/66084550-c4ce9600-e523-11e9-80b1-efea0c8c2ef6.png)

**Comment by JanDeDobbeleer** [comment]
I'm running the insider build and don't see that when adding oh-my-posh to the integrated terminal. Can you update/check if the latest vscode build resolves this?

**Comment by JanDeDobbeleer** [comment]
No response. Nothing but ❤️ though.
