### ISSUE TITLE
How to manage background colors?

### ISSUE THREAD

**Issue by AnthonyMastrean** [JanDeDobbeleer/oh-my-posh2#173]
What's the preferred method for managing the default console background? It seems like the themes only manage the background of text that they print. I end up with a lot of visual conflicts with the default Noble Blue.

![image](https://user-images.githubusercontent.com/217842/67221779-0b643180-f3fa-11e9-8357-49641f53947b.png)

**Comment by JanDeDobbeleer** [comment]
You need to change that in the color settings of your terminal. The backgrounds oh-my-posh sets are indeed only for the prompt parts, it can't change the console colors.
