### ISSUE TITLE
Support for NerdFont icons in prompt

### ISSUE THREAD

**Issue by xasx** [JanDeDobbeleer/oh-my-posh2#176]
With the awesome NerdFonts project https://www.nerdfonts.com/
we have the opportunity to use lovely icons from a broader set.

I'd love to see an option for oh-my-posh to pull in these icon font glyphs (Powerline is in there, too).

For zsh, one of the most famous prompts with NF support is powerlevel9k https://p9k.org/ (or 10k)
For fish, NF is supported through oh-my-fish's bobthefish https://github.com/oh-my-fish/theme-bobthefish

What do you think, is it worth the effort? We all like beautiful prompts.

**Comment by xasx** [comment]
Okay, after reading through your readme again, I understand that it is a matter of creating a new theme, so I feel like asking for a theme. Maybe I find some time to create one myself and file a PR, let's see :wave:

**Comment by xasx** [comment]
For example,

```powershell
$ThemeSettings.GitSymbols.BranchSymbol=[char]::ConvertFromUtf32(0xF418)
```
![Bildschirmfoto von 2019-10-24 10-03-55](https://user-images.githubusercontent.com/1582730/67465554-adc42500-f645-11e9-8c9b-ba42379c998b.png)

**Comment by JanDeDobbeleer** [comment]
You can use `$ThemeSettings.GitSymbols.BranchSymbol=[char]::ConvertFromUtf32(0xF418)` in your `$PROFILE` to override all icons (I think all of them, yes). Have a look at https://github.com/JanDeDobbeleer/oh-my-posh/blob/master/defaults.ps1 for all possible modifications.
