### ISSUE TITLE
Line wrapping prompt shows "color stripe"

### ISSUE THREAD

**Issue by tillig** [JanDeDobbeleer/oh-my-posh2#177]
I've extended the Paradox theme to add some info. Depending on the current path, this may cause the prompt to wrap to the next line, which is fine.

However, I have noticed that:
- Once it wraps to a second line AND
- The terminal has to scroll because the current line has hit the bottom of the screen

...then there is a "stripe" that fills what should be empty space.

Here's PowerShell Core in the Windows Terminal app:

![PowerShell Core in Windows Terminal](https://user-images.githubusercontent.com/1156571/67522517-bfb3c100-f661-11e9-98bc-3a314d4f3045.jpg)

Here's standard PowerShell in its native console:

![Standard PowerShell](https://user-images.githubusercontent.com/1156571/67522562-cf330a00-f661-11e9-8a0d-8a7f7d61dbd1.jpg)

It's possible to reproduce this with the default Paradox theme.

```powershell
Set-Theme Paradox
Set-Location C:\
New-Item -ItemType Directory -Name "repro"
Set-Location C:\repro
@(1..10) | %{ $name = "really-long-dir-$_"; New-Item -ItemType Directory -Name $name | Out-Null; Set-Location $name }
```

That will put you in a really deep directory that will cause the line to wrap. Now hit "Enter" until the prompt is at the bottom of the console window. You'll end up getting something like this:

![Line wrapping of really long dirname](https://user-images.githubusercontent.com/1156571/67523335-559c1b80-f663-11e9-9113-fc2232d48857.jpg)

It doesn't appear to matter if the time shows up or not, so I don't think it has to do with the `Set-CursorForRightBlockWrite` method.

I also noticed that the "fill color" in that stripe is whatever the color is at the end of the _previous_ line. Let's say the prompt is two lines long, wrapped. The first line ends with cyan, then the second line has another segment that's green. The fill color will be cyan - you'll see this in my earlier screen shots.

That leads me to believe that when the line wraps off the screen, it does something like:
- Clear the next line using the current background and foreground color
- Reset the cursor to the beginning of the line
- Allow the prompt to continue

Just guessing, but that's how it _seems_.

Unclear if that's something which can be handled here or if there's something we need to file against PowerShell itself. Maybe something like a `Clear-ToEndOfLine` method that could be run after the final item `>` is written out? I dunno.

**Comment by tillig** [comment]
I may have found a workaround using this block of code after I write out the main prompt but BEFORE doing any of the right-hand-side timestamp bit:

```powershell
# Remove all the escape codes so we can see how long the prompt really is.
$cleanPrompt = $prompt -replace '(\x9B|\x1B\[)[0-?]*[ -\/]*[@-~]',''
# The amount of room to clear is the width of the screen minus however much wrapped.
$toClear = $host.UI.RawUI.BufferSize.Width - ($cleanPrompt.Length % $host.UI.RawUI.BufferSize.Width)
# Write spaces to clear the remainder of the line unless the prompt
# is EXACTLY the width of the line.
if ($toClear -ne $host.UI.RawUI.BufferSize.Width) {
  $prompt += Write-Prompt -Object (" " * $toClear) -ForegroundColor $host.UI.RawUI.ForegroundColor -BackgroundColor $host.UI.RawUI.BackgroundColor
}
```

**Comment by georgefeakes** [comment]
I'm getting this issue and the above snippet doesn't seem to have any effect for me. Any thoughts?

**Comment by tillig** [comment]
Nope. [That's the exact bit of code I'm using right now](https://github.com/tillig/PowerShellProfile/blob/7b9a98cbb9b7f48d50af1f25fa4bb05c942861ee/PoshThemes/Illig.psm1#L179) and it works fine on MacOS and Windows, on PowerShell (original) and PowerShell Core.

I'd guess one of two things is happening:

1. You didn't put the code in the right spot in the theme. [You can see in my personal theme where it is](https://github.com/tillig/PowerShellProfile/blob/7b9a98cbb9b7f48d50af1f25fa4bb05c942861ee/PoshThemes/Illig.psm1#L179) and maybe that will help. [The repo here in has my whole PowerShell profile.](https://github.com/tillig/PowerShellProfile)
2. There's something up with the host. Note the use of `$host.UI.RawUI` in the snippet. Different hosts may report differently. You may see this in other areas, too, like commands that display progress bars. The host in the new Windows Terminal program is not the same as the one you see in the VS Code "Integrated Console" terminal window, which is not the same as an embedded host in Visual Studio.

However, I unfortunately don't have the time or ability to help you debug it any further. It took me quite some time to figure out the solution that works for me, which also seems to work across the shells and operating systems I'm using, so if it's not working for you... then maybe you need to start doing some debugging. For me, there was a lot of "Console.WriteLine" style debugging, but you have to write to a FILE or it will mess up the prompt and not be helpful. Debugging prompt stuff is painful.

**Comment by georgefeakes** [comment]
After having a bit of a play around and making sure the snippet was added in the correct place (it was) the issue seems to be caused by the fact the `cleanPrompt` length is always 0. I don't seem to be able to retrieve the text that has already been written to the prompt. Essentially the replace line is replacing an already empty string.

I have tested writing `" " * $host.UI.RawUI.BufferSize.Width` which removed the background colour issue but obviously ended up with extra characters being inserted.

**Comment by georgefeakes** [comment]
Managed to find a workaround that worked for me using the current cursor position instead of getting the text that has been line wrapped.

Here is the snippet:
`$toClear = $host.UI.RawUI.BufferSize.Width - $host.UI.RawUI.CursorPosition.X`
`$prompt += Write-Prompt -Object (" " * $toClear)`

**Comment by JanDeDobbeleer** [comment]
This shouldn't happen anymore in V3, can you confirm? https://ohmyposh.dev

**Comment by tillig** [comment]
I haven't been able to verify the fix due to JanDeDobbeleer/oh-my-posh3#61. Perhaps @georgefeakes might have better luck.

**Comment by tillig** [comment]
OK, just tried verifying this and it does _not_ appear to be fixed in v3.

<img width="1093" alt="V2 vs V3" src="https://user-images.githubusercontent.com/1156571/95905271-7ca89d00-0d4d-11eb-95a4-7d84af86cbdc.png">

It's a little confusing since I have both v2 and v3 in play here.

The one with the "really long line" shows line wrapping in v3 - note the end of the prompt seems to resume the background color from the really long line - the color of the end of the previous line.

The second one is actually just v2 doing its thing.

Here's the theme JSON I was using to test:

<details>
<summary>Big long JSON file, click to expand.</summary>

```json
{
  "blocks": [
    {
      "alignment": "left",
      "segments": [
        {
          "foreground": "#ff8080",
          "invert_powerline": false,
          "leading_diamond": "",
          "powerline_symbol": "",
          "properties": {
            "always_enabled": false,
            "display_exit_code": true,
            "error_color": "#e91e63",
            "postfix": "]",
            "prefix": "[⌧ EXIT"
          },
          "style": "powerline",
          "trailing_diamond": "",
          "type": "exit"
        },
        {
          "background": "#ffe9aa",
          "foreground": "#100e23",
          "invert_powerline": false,
          "leading_diamond": "",
          "powerline_symbol": "",
          "properties": {
            "root_icon": "☠"
          },
          "style": "powerline",
          "trailing_diamond": "",
          "type": "root"
        },
        {
          "background": "#000000",
          "foreground": "#ffffff",
          "invert_powerline": false,
          "leading_diamond": "",
          "powerline_symbol": "",
          "properties": {
            "postfix": " ",
            "user_info_separator": "@"
          },
          "style": "powerline",
          "trailing_diamond": "",
          "type": "session"
        },
        {
          "background": "#0000c0",
          "foreground": "#ffffff",
          "invert_powerline": false,
          "leading_diamond": "",
          "powerline_symbol": "",
          "properties": {
            "prefix": "  ",
            "style": "short"
          },
          "style": "powerline",
          "trailing_diamond": "",
          "type": "path"
        },
        {
          "background": "#00ffff",
          "foreground": "#000000",
          "invert_powerline": false,
          "leading_diamond": "",
          "powerline_symbol": "",
          "properties": {
            "command": "o=$(dotnet --version 2>/dev/null); X=$?; if [ $X -eq 0 ]; then { echo $o; exit 0; }; elif [ $X -eq 145 ]; then { echo \"[unsupported global.json]\"; exit 0; }; else exit 1; fi",
            "prefix": "  ",
            "shell": "bash"
          },
          "style": "powerline",
          "type": "command"
        },
        {
          "background": "#ebcc34",
          "foreground": "#000000",
          "invert_powerline": false,
          "leading_diamond": "",
          "powerline_symbol": "",
          "properties": {
            "text": "This is a really long line that should cause things to wrap and might not end nicely."
          },
          "style": "powerline",
          "type": "text"
        },
        {
          "background": "#00cc00",
          "foreground": "#000000",
          "powerline_symbol": "",
          "properties": {
            "bitbucket_icon": "",
            "branch_ahead_icon": "↑",
            "branch_behind_icon": "↓",
            "branch_icon": "",
            "branch_identical_icon": "≡",
            "cherry_pick_icon": " ",
            "commit_icon": " ",
            "display_stash_count": true,
            "display_upstream_icon": true,
            "git_icon": "",
            "github_icon": "",
            "gitlab_icon": "",
            "local_staged_icon": "",
            "local_working_icon": "",
            "merge_icon": " ",
            "rebase_icon": " ",
            "stash_count_icon": " ",
            "tag_icon": "笠 "
          },
          "style": "powerline",
          "type": "git"
        }
      ],
      "type": "prompt",
      "vertical_offset": 0
    }
  ],
  "console_title": false,
  "final_space": true
}
```
</details>

I did switch to iTerm2, so I can probably try a few more things out if needed.

**Comment by tillig** [comment]
<img width="1093" alt="With right-aligned time" src="https://user-images.githubusercontent.com/1156571/95906965-b8446680-0d4f-11eb-9539-e398503ccb22.png">

On a whim I added a second block with a right-aligned time and it doesn't result in clearing the line. (I've been updating the segments with new commands and things, too, so... yeah. It's not the same as the text segment above but it still illustrates the issue.)

Should I add a separate/new issue to the v3 repo?

**Comment by JanDeDobbeleer** [comment]
Yes pls. I'll have a look ASAP!

**Comment by tillig** [comment]
Added JanDeDobbeleer/oh-my-posh3#65

**Comment by JanDeDobbeleer** [comment]
That'll be something for tomorrow 👍🏻
