### ISSUE TITLE
Allow disabling of Title setting

### ISSUE THREAD

**Issue by Dave-EMIS** [JanDeDobbeleer/oh-my-posh2#179]
I know you have only just implemented #162  to set the title in the new Windows Terminal, but this is something I'm not keen on.
I usually have many tabs open, and like to set their titles manually so I know what each one is.

I have `$GitPromptSettings.WindowTitle = $null` set in my Profile to stop posh-git changing the title, but since installing oh-my-posh I can't find a way to do this.

Would it be possible to have an option to disable title setting like posh-git does, or to use the same setting, I don't mind? :)

**Comment by JanDeDobbeleer** [comment]
We sure can. Allow me to add a setting for that 👍

**Comment by Dave-EMIS** [comment]
Perfect, thanks @JanDeDobbeleer 

```
$ThemeSettings.Options.ConsoleTitle = $false
```

Does the trick :)
