### ISSUE TITLE
Windows Terminal font for bash

### ISSUE THREAD

**Issue by OlekRia** [JanDeDobbeleer/oh-my-posh2#183]
I have changed Theme in windows Terminal for "Sorin". Set-Theme Sorin. Everything is OK. But when I use WSl bash I still have always Paradox theme. How to change it?

**Comment by JanDeDobbeleer** [comment]
Wait, you create a new window with the WSL bash right? Are you running pwsh in that environment? They aren't linked in any way so you'll get whatever's configured in each of those.
