### ISSUE TITLE
Monokai Theme

### ISSUE THREAD

**Issue by Schwitzd** [JanDeDobbeleer/oh-my-posh2#184]
Dear Jan,

can you please add the Monokai theme?
https://github.com/seven-two-eight/ps-monokai-theme

Thanks a lot
Schwitzd

**Comment by JanDeDobbeleer** [comment]
Hey @Schwitzd , themes are created by the "user", as in you need to adjust your Terninal's color scheme. Oh-my-posh can't alter every color in the environment, only made to "comply". So, you need to add the Monokai theme to your terminal, then adjust `$ThemeSettings` to play nice with these, but the available colors will be the ones you set in your terminal.
