### ISSUE TITLE
Unreadable Mark

### ISSUE THREAD

**Issue by yxie80** [JanDeDobbeleer/oh-my-posh2#186]
I am not sure why this happens. Is there anyone facing the same problem?
![2019-11-28](https://user-images.githubusercontent.com/21286241/69726230-3158c080-1174-11ea-97d7-fbd920727c75.png)

**Comment by lewisakura** [comment]
Install a [Powerline font](https://github.com/powerline/fonts).

**Comment by salmanfarisvp** [comment]
how to install Powerline Font on windows?

**Comment by lewisakura** [comment]
Go to the repository I linked, find a font you like, and download the TTF. Open it, and install it like any other font.

In your terminal emulator of choice (conhost, Windows Terminal, etc.) change the font in the settings to the one you just picked.
