### ISSUE TITLE
Please verify against posh-git master before posh-git 1.0.0-beta4 is published

### ISSUE THREAD

**Issue by rkeithhill** [JanDeDobbeleer/oh-my-posh2#189]
We made a change to how `$GitPromptSettings.BeforeIndex` is used.  From the changelog:

- `$GitPromptSettings.BeforeIndex` is always displayed even if there is nothing in the index.  The intent of this separator setting is to provide a separator between the branch name / branch status and the following section of index/working/summary/stash indicators.

**Comment by JanDeDobbeleer** [comment]
I just validated the latest master branch and that seems to work without any issues. Thanks for the heads-up, I made sure to take this into account in my testing setup as well.

**Comment by rkeithhill** [comment]
Thanks!
