### ISSUE TITLE
Add support for UNC path as current working directory

### ISSUE THREAD

**Issue by sba923** [JanDeDobbeleer/oh-my-posh2#190]
If I change the current working directory to a UNC location, say:

````
cd //pnjnas/sto
````

I get the following prompt:

![image](https://user-images.githubusercontent.com/12860484/72209189-05876500-34ac-11ea-9528-0c931ee4ae4b.png)

whereas I expect the `Microsoft.PowerShell.Core\FileSystem::` part to be omitted.

IOW, if the current location is set to a filesystem location, I expect the prompt to include `(pwd).ProviderPath`, not `(pwd).Path`

**Comment by JanDeDobbeleer** [comment]
This test should actually handle that case. Unless this doesn't identify as FileSystem:

        It "is in 'Microsoft.PowerShell.Core\FileSystem::\\Test\Hello' with provider X:" {
            $path = @{Drive = @{Name = 'X:'}; Path = 'Microsoft.PowerShell.Core\FileSystem::\\Test\Hello'}
            Get-Drive $path | Should Be "Test$($ThemeSettings.PromptSymbols.PathSeparator)Hello$($ThemeSettings.PromptSymbols.PathSeparator)"
        }

I'm running everything on my MAC right now, so validating a Windows machine is going to be a little challenge. Can you help me out and provide the output of `(Get-Item . -Force).PSProvider.Name` in that location?

**Comment by sba923** [comment]
Sure, it's (as expected) `FileSystem`.

**Comment by JanDeDobbeleer** [comment]
Ok. Need to see what exactly is wrong in that case. Been a while since I touched that part of the code.

**Comment by sba923** [comment]
👌

Just tell me if there's anything I can do to help. Haven't yet bitten the bullet of writing modules, or debugging modules written by others, but there's always a start 😜

**Comment by JanDeDobbeleer** [comment]
I found the tests to be working against me, I'm fixing that first to then add the use-case.

**Comment by sba923** [comment]
Great! How will I be notified of the availability of a new release including that fix?

**Comment by sba923** [comment]
I just discovered the fix was done in `Get-ShortPath`, but not in `Get-FullPath`.

Why is that?

My theme uses `Get-FullPath` for the prompt...

**Comment by sba923** [comment]
Next discovery: the prompt I get if I switch to using `Get-ShortPath` is not what I'd expect:

![image](https://user-images.githubusercontent.com/12860484/76989601-e9d68a00-6946-11ea-8d35-36e37bc3a260.png)

Apparently more is done than just removing `Microsoft.PowerShell.Core\FileSystem::`...

**Comment by JanDeDobbeleer** [comment]
That is according to scope. I added a symbol called `UNCSymbol` that defaults to `'§'`. If you adjust that one you can be aware you're in a UNV path just like if you were in home for example.
