### ISSUE TITLE
Show full path

### ISSUE THREAD

**Issue by privacyguy123** [JanDeDobbeleer/oh-my-posh2#191]
Is it possible to edit the themes to show the full path instead of the shortened version with ~ appended?

**Comment by JanDeDobbeleer** [comment]
Everything is possible, BUT if you want that I would opt for creating a custom theme by copying the one you like and adjusting it to your needs. For example, Agnoster uses the `Get-ShortPath` function which creates the neat output (I'm biased). You can easily change that with `$PWD.Path` and you're done.

**Comment by privacyguy123** [comment]
Cheers!
