### ISSUE TITLE
Set-Prompt not found

### ISSUE THREAD

**Issue by rayzorben** [JanDeDobbeleer/oh-my-posh2#194]
Running in Windows Terminal. Other commands seem to work, but not `Set-Prompt`. As you can see I am running 2.0.342 which is the latest release. See screenshot.

![image](https://user-images.githubusercontent.com/7737834/73366775-5dbbb680-4263-11ea-99d5-065228a79e56.png)

**Comment by JanDeDobbeleer** [comment]
aha. Let me check.

**Comment by JanDeDobbeleer** [comment]
Resolved in the latest version.
