### ISSUE TITLE
Virtualenv character in defaults.ps1 incorrect?

### ISSUE THREAD

**Issue by matthewbegun** [JanDeDobbeleer/oh-my-posh2#196]
Hi, thanks for the module its fantastic.

I've just started using conda environments and noticed that the little gear icon doesn't seem to work in any of the profiles on powershell.

I've had a look in `defaults.ps1` and the `PromptSymbols.VirtualEnvSymbol` is set to `[char]::ConvertFromUtf32(0xE606)` which is a "PRIVATE USE CODEPOINT" whatever that means. But not the gear on agnoster's repo.

Changing the value to `[char]::ConvertFromUtf32(0x2699)` makes the gear work correctly.

Thanks again!

**Comment by JanDeDobbeleer** [comment]
Hi @matthewbegun, it depends on your font. I added these and used Mezlo LG M at the time, the idea is that you can change them to play with whatever font you are using. As such, this is expected behavior ;-)

**Comment by matthewbegun** [comment]
Ok no worries. Thanks!

**Comment by davidstadem** [comment]
I had the same issue using Powershell 7 on Windows 10 with Meslo LG M for Powerline font. Thanks to both of you for clarifying the problem.

For posterity, you can set the VirtualEnvSymbol in your Powershell profile:
```
Import-Module oh-my-posh
$ThemeSettings.PromptSymbols.VirtualEnvSymbol = [char]0x2699
Set-Theme Paradox

```
![image](https://user-images.githubusercontent.com/16998037/81843266-fe806a00-9512-11ea-86dd-4dc51a7ea9d2.png)
