### ISSUE TITLE
Console title contains repeated path name element

### ISSUE THREAD

**Issue by kariudo** [JanDeDobbeleer/oh-my-posh2#198]
Set-theme causes the Console Title to contain repeated name of the path element, rather than the complete path. 

Probably introduced by 885d474cf2cbb71c173dd21d7632247228e65d62

![image](https://user-images.githubusercontent.com/1364939/73669029-cb594f80-4674-11ea-810e-ba8af3409e2f.png)

**Comment by JanDeDobbeleer** [comment]
You are absolutely right. For some reason that didn't come through on my setup 😢
