### ISSUE TITLE
Strange coloring issue with DefaultUser

### ISSUE THREAD

**Issue by Ergamon** [JanDeDobbeleer/oh-my-posh2#201]
Seems a somewhat tricky bug. I try my best to desribe the fastest way to reproduce.

I am using cmder with Powershell Core.

So what I did on a fresh PC:
1. Installed PowerShell Core (6.2.4, but version does not matter)
2. Unzipped latest cmder version to a folder (1.3.14.982, should also not matter much)
3. I started cmder and set up a new task by copying the PowerShell::PowerShell task and changing powershell with pwsh in the commands textbox
4. After starting I installed the modules posh-git and oh-my-powsh as described here

That is basically everything need to get it up and running.

So when I type this:
```
$DefaultUser = "me"
Import-Module posh-git
Import-Module oh-my-posh
Set-Theme Paradox
```
Everthing works and runs fine.

Of course I dont want to do this everytime, so I added these 4 lines to the end of the config/user_profile.ps1file.
But now the colors are messed up. You clearly see it when you produce some output.
It must be some weird timing problem.
Cause everything looks allright when I comment out the line setting the default user or the line setting the theme.
Of course then I have to type the commented out command everytime after starting cmder, but it works.
So something must be working different if the 2 things of setting the default user and setting the theme are done while starting up (during the phase executing the user_profile.ps1) or doing the same thing later when already in the interactive mode.

Would be great if you could take a look on this.

Greetings 
  Gerald

**Comment by JanDeDobbeleer** [comment]
What happens when you add those lines to your `$PROFILE`? I've noticed quite some issues with Cmder in the past, as it adds stuff you don't really need anymore (it was a great idea 5 years ago). I wonder if you have the same issues when adding these commands to your `$PROFILE` and use ConEmu.

**Comment by JanDeDobbeleer** [comment]
This shouldn't happen anymore in V3, can you confirm? https://ohmyposh.dev

**Comment by Ergamon** [comment]
First of all thanks for your great work and support, but sadly I cannot confirm with the latest version.

The relavant part of my profile is still:
```
#$DefaultUser = "Gerald"

Import-Module posh-git
Import-Module oh-my-posh

Set-Theme Paradox
```

The latest beta version does not change anything.

I have attached 3 screenshots. 

#1 and #3 show everything working correctly as I don´t set the DefaultUser variable in the profile. In #1 I don´t set it at all and in #3 I set it manually **after** everything is up and running.

In #2 colors go mad as I have set the variable in the profile (basically removing the # from my posted code)

![DefaultUserNotSet](https://user-images.githubusercontent.com/48294299/95673387-3a922680-0ba8-11eb-9a82-ffec3664d8c9.jpg)
![DefaultUserSet](https://user-images.githubusercontent.com/48294299/95673389-3e25ad80-0ba8-11eb-91f7-2df283082ee4.jpg)
![DefaultUserSetManually](https://user-images.githubusercontent.com/48294299/95673390-40880780-0ba8-11eb-8387-7cdf6bfe5674.png)

**Comment by JanDeDobbeleer** [comment]
@Ergamon you're not using V3 :-) `Set-Theme` is a V2 function, V3 uses `Set-PoshPrompt paradox` (see [here](https://ohmyposh.dev/docs/upgrading))
I tried this on V3 and can't reproduce this anymore (MacOS and WIndows).
