### ISSUE TITLE
Incorrect platform name check for Windows in Get-VirtualEnvName

### ISSUE THREAD

**Issue by gledi** [JanDeDobbeleer/oh-my-posh2#202]
When we are inside a virtualenv and we are building the prompt we call `Get-VirtualEnvName` from [Helpers/Prompt.ps1](https://github.com/JanDeDobbeleer/oh-my-posh/blob/master/Helpers/Prompt.ps1#L170) as shown below:

`} elseif ($PSVersionTable.Platform -eq 'Windows') {`

However if you check from a PowerShell prompt (tried from PowerShell Core **6.2.4** & **7.0.0-rc.2**) you get `Win32NT`:

```powershell
PS> Write-Host $PSVersionTable.Platform
Win32NT
``` 

In PowerShell 5 the `Platform` key does not exist at all since that is Windows only.

We should change the check as below:

`$PSVersionTable.Platform -eq 'Win32NT'`

or if there exists some situation where the platform can be **Windows** we could change it as follow:

`$PSVersionTable.Platform -eq 'Windows' -or $PSVersionTable.Platform -eq 'Win32NT'`

Also if we want this to run on PowerShell 5 we can also add a check that `$PSVersionTable.PSVersion.Major` is less than or equal to 5:

`$PSVersionTable.Platform -eq 'Win32NT' -or $PSVersionTable.PSVersion.Major -le 5`

Unrelated to this issue is something else I noticed.
When we create virtualenvs we can override the prompt so that it is different from the directory name.
Newer virtualenv versions include a function `Get-PyVenvConfig` that reads the file `pyvenv.cfg` and returns an object that contains a `prompt` property that stores the user's desired prompt value. I think we should take this into consideration as well.

If you agree I can try to send a pull request with a fix.

**Comment by JanDeDobbeleer** [comment]
Resolved in #205
