### ISSUE TITLE
error during installation

### ISSUE THREAD

**Issue by jagjordi** [JanDeDobbeleer/oh-my-posh2#203]
I get this error in the last step
```
PS C:\Users\Jordi> Set-Prompt
Set-Prompt : The 'Set-Prompt' command was found in the module 'oh-my-posh', but the module could not be loaded. For
more information, run 'Import-Module oh-my-posh'.
At line:1 char:1
+ Set-Prompt
+ ~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Set-Prompt:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CouldNotAutoloadMatchingModule
```

Running Windows 10

**Comment by yuyoux** [comment]
same here

**Comment by sagarrchauhan** [comment]
> 
> 
> I get this error in the last step
> 
> ```
> PS C:\Users\Jordi> Set-Prompt
> Set-Prompt : The 'Set-Prompt' command was found in the module 'oh-my-posh', but the module could not be loaded. For
> more information, run 'Import-Module oh-my-posh'.
> At line:1 char:1
> + Set-Prompt
> + ~~~~~~~~~~
>     + CategoryInfo          : ObjectNotFound: (Set-Prompt:String) [], CommandNotFoundException
>     + FullyQualifiedErrorId : CouldNotAutoloadMatchingModule
> ```
> 
> Running Windows 10

Same here

**Comment by daretodave** [comment]
I'm assuming these are typical installs of the `oh-my-posh` with the `-Scope CurrentUser` flag? 
Try running this in your powershell - 
```powershell
Import-Module ~/Documents/WindowsPowerShell/Modules/oh-my-posh
```

**Comment by qxdn** [comment]
try this
`Set-ExecutionPolicy Bypass`
![image](https://user-images.githubusercontent.com/42409827/74931860-7b6fdc00-541b-11ea-8f6e-3f05d90fd78b.png)

**Comment by JanDeDobbeleer** [comment]
The reason this doesn't seem to work is because oh-my-posh is not, or not properly, imported. The comment by @qxdn should resolve the issue, but importing it should work out of the box when everything is correctly scoped.

**Comment by mvanderlee** [comment]
In my case the installed module was never loaded.

```shell
PS C:\Users\tonystark> $env:PSModulePath.split(';')

C:\Users\tonystark\AppData\Local\Google\Cloud SDK\google-cloud-sdk\platform\PowerShell
C:\Program Files\WindowsPowerShell\Modules
C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules
```

Once I added the correct path to the environment variable it worked as expected:
```shell
C:\Users\tonystark\OneDrive\Documents\WindowsPowerShell\Modules
```
