### ISSUE TITLE
Themes have issues

### ISSUE THREAD

**Issue by GentelmanBastard** [JanDeDobbeleer/oh-my-posh2#204]
Hey,

I seem to have a problem with themes, I installed posh-git and oh-my-posh, however when I change theme it looks like this.

![image](https://user-images.githubusercontent.com/21159891/74241204-d26b0800-4cdb-11ea-8003-6e7f003d1c00.png)

What am I missing?

**Comment by nwykes** [comment]
Looks like you're missing the font prerequisites listed in the Readme.

**Comment by JanDeDobbeleer** [comment]
Yes, the font isn't available. You can have a look at the one you like in https://www.nerdfonts.com/
