### ISSUE TITLE
Possible to set transparency on first part of colored prompt

### ISSUE THREAD

**Issue by emilast** [JanDeDobbeleer/oh-my-posh2#214]
Is it possible to have the first part of a colored prompt to be transparent?

This is what my prompt looks like in in Windows Terminal:

![image](https://user-images.githubusercontent.com/2369639/76146557-0dbae580-6094-11ea-9cbf-1818b6fc14f2.png)
 
I have enabled "acrylic" to make the background semi-transparent and blurred and it would be great if the first minimal dark-grey part of the prompt to be transparent as well. Is it possible?

**Comment by JanDeDobbeleer** [comment]
I've seen this go wrong a few times already, yet I have no idea why. It takes transparent but doesn't work. Maybe we should resort to writing ANSI all the time, but that a large refactor.

**Comment by emilast** [comment]
No problem! Thanks for this great project! 👏

**Comment by NeilCross** [comment]
I was looking at this one, The difference between the user prompt and the separator is that the user prompt is being written with a black background,  however the circled separator here is written with a black foreground, I suppose in WT the background may be be to be rendered transparent, however the foreground doesn't seem to.

**Comment by NeilCross** [comment]
Ohh, writeup below, it seems to affect other similar utilities:
https://github.com/microsoft/terminal/issues/293
