### ISSUE TITLE
broken symbols _after_ doing set-prompt

### ISSUE THREAD

**Issue by daantimmer** [JanDeDobbeleer/oh-my-posh2#217]
So, I've installed ConEmu, posh-git and oh-my-posh. I've also installed the Mononoki NF and MesloLGM NF. I've downloaded the 2.1 release of these from -> https://www.nerdfonts.com/

I've setup ConEmu to use mononoki NF as default and alternative font. Not that the latter matters.

When doing the import-module step by step and then using set-prompt some of the icons stop working. See:
![image](https://user-images.githubusercontent.com/8293597/77064766-65d0e080-69e0-11ea-89c4-31936708949e.png)

I don't have a profile setup for powershell as I've done the configuration via ConEmu like:
`powershell.exe -new_console:a -noexit -command "Import-Module posh-git, oh-my-posh; Set-Prompt; $DefaultUser = 'xyz'"` (except for the image above, where I did the steps manually)

Please advice.

**Comment by JanDeDobbeleer** [comment]
Hey @daantimmer, yes if you change a font, the glyphs can differ. This means you need to open a font book for your font (Mononoki NF) and find the correct glyph chars for the icons you want to use. Not all fonts are the same.
