### ISSUE TITLE
Custom window title

### ISSUE THREAD

**Issue by beppler** [JanDeDobbeleer/oh-my-posh2#218]
How can I configure a custom window title to something like user@host:path?

On bash I can use the following:

```bash
echo -ne "\033]0;$USER@$HOSTNAME:${PWD/#$HOME/\~}\007"
```

**Comment by JanDeDobbeleer** [comment]
You can do the same but it's based on your terminal, not PowerShell. It should know ANSI escape sequences (most of them do nowadays). You can use a function as such:

```powershell
function Set-ConsoleTitle {
    param(
        [string]
        $title
    )
    $escapeChar = [char]27
    return "$escapeChar]2;$title`a"
}
```
