### ISSUE TITLE
PowerShell with oh-my-posh shows unreadable marks at startup

### ISSUE THREAD

**Issue by yihuajack** [JanDeDobbeleer/oh-my-posh2#220]
Every time I open PowerShell or PowerShell 7, it shows unreadable marks like `]2;system32]9;9;"C:\WINDOWS\system32"` (Obviously, the paths contain no utf-8, gb2312, gbk, or other multibyte characters). However, after executing any command, the unreadable marks just dramatically does not exist anymore like this (in PowerShell):
![image](https://user-images.githubusercontent.com/23608500/77616373-6fbc8b80-6f6c-11ea-9467-4718a8472a15.png)
or in PowerShell 7:
![image](https://user-images.githubusercontent.com/23608500/77616496-c1651600-6f6c-11ea-817e-1bd907378d54.png)
This problem does exist in other terminals like Windows Terminal. In Fluent Terminal, there are not these unreadable marks but a blank space so that the right-side cursor gets pushed away from the left tab edge. I have debugged this problem by deleting each sentence in `Microsoft.PowerShell_profile.ps1` and made sure that this problem was caused by oh-my-posh.
My `Microsoft.PowerShell_profile.ps1` is:
```Import-Module DirColors
Update-DirColors ~/dircolors.256dark
Import-Module posh-git
if (!(Get-SshAgent)) {
    Start-SshAgent
}
Import-Module oh-my-posh
Set-Theme PowerLine
Screenfetch
$ChocolateyProfile = "$env:ChocolateyInstall\helpers\chocolateyProfile.psm1"
if (Test-Path($ChocolateyProfile)) {
  Import-Module "$ChocolateyProfile"
}
```
I have updated all the modules. The output of `get-module` is:
```ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     0.0                   chocolateyProfile                   {TabExpansion, Update-SessionEnvironment, refreshenv}
Script     1.1.2                 DirColors                           {ConvertFrom-LSColors, ConvertTo-LSColors, Format-ColorizedFilename, Format-ColorizedFilenameAndLinkT…
Manifest   7.0.0.0               Microsoft.PowerShell.Management     {Add-Content, Clear-Content, Clear-Item, Clear-ItemProperty…}
Manifest   7.0.0.0               Microsoft.PowerShell.Utility        {Add-Member, Add-Type, Clear-Variable, Compare-Object…}
Script     2.0.399               oh-my-posh                          {Get-ComputerName, Get-FormattedRootLocation, Get-FullPath, Get-ShortPath…}
Script     0.7.3                 posh-git                            {Add-PoshGitToProfile, Add-SshKey, Enable-GitColors, Expand-GitCommand…}
Script     2.0.0                 PSReadLine                          {Get-PSReadLineKeyHandler, Get-PSReadLineOption, Remove-PSReadLineKeyHandler, Set-PSReadLineKeyHandle…
```
The font face of the windows is `DejaVu Sans Mono for Powerline`. It seems that changing fonts or themes does not make a difference. By the way, rebooting the computer does not make a difference, either.

**Comment by yihuajack** [comment]
Oh, I found it is due to my version of posh-git is not the latest. Sorry for my carelessness.

**Comment by tcztzy** [comment]
The same problem exist in latest version 2.0.412
![image](https://user-images.githubusercontent.com/12420478/82399450-bec40000-9a87-11ea-8a6a-ded02691710a.png)
![image](https://user-images.githubusercontent.com/12420478/82399474-cc798580-9a87-11ea-8c4b-10d381969297.png)

**Comment by yihuajack** [comment]
> The same problem exist in latest version 2.0.412
> ![image](https://user-images.githubusercontent.com/12420478/82399450-bec40000-9a87-11ea-8a6a-ded02691710a.png)
> ![image](https://user-images.githubusercontent.com/12420478/82399474-cc798580-9a87-11ea-8c4b-10d381969297.png)

Actually, I think this issue is not related to the version of `oh-my-posh` but `posh-git`. It seems that you're using an old version of `posh-git 0.7.3`. Please update your `posh-git`. The latest version of `posh-git` is v1.0.0 Beta 4. Note that using default install command leads to this old version, so use `PowerShellGet\Install-Module posh-git -Scope CurrentUser -AllowPrerelease -Force` or `PowerShellGet\Update-Module posh-git` instead. See the GitHub page of `posh-git`.

**Comment by tcztzy** [comment]
> > The same problem exist in latest version 2.0.412
> > ![image](https://user-images.githubusercontent.com/12420478/82399450-bec40000-9a87-11ea-8a6a-ded02691710a.png)
> > ![image](https://user-images.githubusercontent.com/12420478/82399474-cc798580-9a87-11ea-8c4b-10d381969297.png)
> 
> Actually, I think this issue is not related to the version of `oh-my-posh` but `posh-git`. It seems that you're using an old version of `posh-git 0.7.3`. Please update your `posh-git`. The latest version of `posh-git` is v1.0.0 Beta 4. Note that using default install command leads to this old version, so use `PowerShellGet\Install-Module posh-git -Scope CurrentUser -AllowPrerelease -Force` or `PowerShellGet\Update-Module posh-git` instead. See the GitHub page of `posh-git`.

I made mistake to confuse oh-my-posh and posh-git. But it still occur.
![image](https://user-images.githubusercontent.com/12420478/83009847-f6afe200-a049-11ea-9485-97665c41403d.png)

**Comment by yihuajack** [comment]
Have you tried to change the codepage to 65001 by `chcp 65001` or other codepages such as 936?
