### ISSUE TITLE
Allow themes to get VcsInfo in pieces

### ISSUE THREAD

**Issue by davidkwoods** [JanDeDobbeleer/oh-my-posh2#223]
I've gotten into oh-my-posh, and I gotta say I really like it.  I've got my own little theme that I'm tweaking just so, though, and I found myself wishing I had a little more control over the way I display my Git status.  I like to keep my branch status separate from the status of my index and worktrees, but Get-VcsInfo groups it all together with one color and one string.

Would you be open to the idea of adding a path that splits up the status info for themes that want a little more control there?

I put together [some changes in my own fork](https://github.com/davidkwoods/oh-my-posh/commit/6a96e66e9e39df21636247a424e0d99bd3c41004) just to get it working for myself.  I wouldn't consider it production ready, but may serve as a useful reference if you find the feature interesting enough to pick up.

**Comment by JanDeDobbeleer** [comment]
I would yes. Always open to more customization.

**Comment by deoradh** [comment]
Related, I'd be interested in including upstream branch name.  Right now, I'm hacking this together, but I wonder if it shouldn't be part of the original info generator, controllable by a flag:

`    $status = Get-VCSStatus
    if ($status) {
        $vcsInfo = Get-VcsInfo -status ($status)
        $info = $vcsInfo.VcInfo

	if ($status.Upstream) ### HACK ###
        {
	    $splits = $info.Split(' ', 3)
            $splits[1] += (" => "+ $status.Upstream)
            $info = [String]::Join(" ", $splits)
        }

        # etc
    }`

**Comment by JanDeDobbeleer** [comment]
This is a feature of V3 now https://ohmyposh.dev
