### ISSUE TITLE
Incorrect prompt length after vertical split in Windows Terminal

### ISSUE THREAD

**Issue by KnapSac** [JanDeDobbeleer/oh-my-posh2#225]
I'm using oh-my-posh with posh-git in the Windows Terminal. This all works fine, but after doing a horizontal ([ | ]) split, the time gets cut off and partially displayed on the next line. Additionally, the top line disappears completely, but I suspect that maybe related to the time issue. See the screenshot included below.

Is this a known issue, or has this something to do with my configuration? If this is a bug, I'd be more than happy to look into this, but I'm curious to hear your thoughts.

Edit:
This also occurs when the window is resized horizontally. Which makes me think it probably has to do with the length calculation of the prompt when the pane/window gets resized.

Screenshot:
![oh-my-posh promt](https://user-images.githubusercontent.com/34449626/78877332-fb481900-7a50-11ea-9d01-a5807bcf41c2.png)

**Comment by JanDeDobbeleer** [comment]
Not a known bug, but a bug nonetheless. The whole right-write functionality isn't as brillienatly written as I'd like...

**Comment by Archeri2000** [comment]
![image](https://user-images.githubusercontent.com/16084793/83960371-b4449b80-a8ba-11ea-9a45-02fb03b64630.png)
Not sure if a related bug, but when resizing horizontally, the following also happens. Managed to replicate it on windows terminal as well as in powershell terminal. It appears that it happens when the line gets cut off midway and has to continue on a new line.

**Comment by sassdawe** [comment]
@JanDeDobbeleer is this really a bug?

I mean, that first line of the prompt is `n` character long, where `n` is the vertical size of the window. 

Without a vertical scroll bar, this is just the standard "Wrap text output on resize".

When you turn it off:
![image](https://user-images.githubusercontent.com/10754765/87246364-3ccfd200-c44d-11ea-8c76-e8c31320c49d.png)

The scroll bar will show up, and the timestamp will / kinda position to the size of the window:
![image](https://user-images.githubusercontent.com/10754765/87247786-32660600-c456-11ea-83cd-c915cbb8923f.png)

All text on the screen follows this behavior, I don't think that the prompt could/should be different.

**Comment by JanDeDobbeleer** [comment]
This shouldn't happen anymore in V3, can you confirm? https://ohmyposh.dev

**Comment by KnapSac** [comment]
The time is still being cut off, as far as I can tell. Since opening this issue, I've stopped using ```oh-my-posh```, and I seem to have lost the exact configuration I was using at the time of opening this issue. 

I tested this using the ```honukai``` theme, and running the latest pre-release build of Windows Terminal.

**Comment by JanDeDobbeleer** [comment]
Ah ok, I see. As the prompt isn't re-rendered on resize (that's pretty challenging and useless), when pressing enter it should have the correct rendering.

**Comment by KnapSac** [comment]
Ok. I can close this issue, unless you want to keep it open?

**Comment by JanDeDobbeleer** [comment]
Given this isn't something I can fix, I'd opt to close it.
