### ISSUE TITLE
Greater than 100% DPI scaling on Windows leads to 1 pixel vertical bar between some characters

### ISSUE THREAD

**Issue by gusper** [JanDeDobbeleer/oh-my-posh2#226]
I'm not sure what component is causing this but figured I'd start with this project. I'm using Cascadia Code PL for my prompt, posh-git, etc. However, I noticed that on 2 of my 3 monitors, I'm getting a 1px wide line between some characters. 

It only happens on the two 4K monitors I have that are using greater than 100% scaling. I have a 2K monitor running at 100% scaling that doesn't show the bars. 

Here's what it looks like on the 4K monitors (note red dots I added to highlight the lines):
![image](https://user-images.githubusercontent.com/1840164/78913971-a8fdfc80-7a3e-11ea-99a4-be3ed436bfb1.png)

Here's what it looks like on the 2K monitor after dragging the same window over to it:
![image](https://user-images.githubusercontent.com/1840164/78914416-35102400-7a3f-11ea-9997-16ea1d9fd9d3.png)

Any ideas if there's a way for me to fix this?

**Comment by sobayed** [comment]
Same issue here. On my secondary monitor (1920 x 1200, 100% scaling) the display is fine whereas on my laptop screen (1920 x 1080, 150% scaling) I also get these lines in between the characters (also using Cascadia Code PL).

**Comment by JanDeDobbeleer** [comment]
No idea tbh. As it's a string (nothing special there) it does not contain abilities to have influence on the space behavior.

**Comment by ForNeVeR** [comment]
This issue better should be filed to Windows Terminal or whatever terminal software you use.

**Comment by sobayed** [comment]
Might be related to this issue: https://github.com/microsoft/terminal/issues/455

**Comment by miniksa** [comment]
> Might be related to this issue: [microsoft/terminal#455](https://github.com/microsoft/terminal/issues/455)

It is exactly that issue. This isn't for oh-my-posh to fix. It's for me to fix in the Windows Terminal.

**Comment by gusper** [comment]
Closing out now that it's confirmed it should have been in terminal (and it's actually working for me now too so I must have gotten an update).
