### ISSUE TITLE
Agnoster Theme color looks different

### ISSUE THREAD

**Issue by dotnetshadow** [JanDeDobbeleer/oh-my-posh2#227]
Hi there, 

A great project. I was wondering why my default colours for themes look different the default screenshots I've seen of the theme

For example take the Agnoster theme, these are the colours I get:

Using Windows Terminal with powershell 7.0:
![image](https://user-images.githubusercontent.com/296247/79060690-56854000-7ccb-11ea-9849-bf84d776127a.png)

Using Powershell 7.0
![image](https://user-images.githubusercontent.com/296247/79060702-8e8c8300-7ccb-11ea-9f35-2f7a091faecd.png)

![image](https://user-images.githubusercontent.com/296247/79060637-d4951700-7cca-11ea-87ad-c8617d92cb22.png)

But when I see the theme screenshots it should be lighter blue etc
![image](https://user-images.githubusercontent.com/296247/79060661-06a67900-7ccb-11ea-9af9-da6bce0c72fc.png)

I'm using powershell 7.0
**Profile**
```
$DefaultUser = [System.Environment]::UserName
Import-Module posh-git
Import-Module oh-my-posh
Set-Theme Agnoster
```

Am I missing something? Or is it because powershell is limited to 16 colors?

Thanks for your efforts

**Comment by buster95** [comment]
In vscode looks like screenshots, I think defaults terminals doesn't have color support

**Comment by dotnetshadow** [comment]
@buster95 cheers thanks for confirming much appreciated

**Comment by JanDeDobbeleer** [comment]
The screenshots are from the prompt running in ConEMu which has the ability to change the colors. So that's my custom color scheme :-)
