### ISSUE TITLE
Theming breaks when used in conjunction with zlocation

### ISSUE THREAD

**Issue by masaeedu** [JanDeDobbeleer/oh-my-posh2#23]
I'm using vors/ZLocation alongside this, and have noticed that jumping to a different directory seems to break theming. I can reset the theme by using set-theme.

Here's what it looks like: https://1drv.ms/v/s!Al6mzY0CpY7Em17n_nmmGHro2x3d

**Comment by JanDeDobbeleer** [comment]
Thanks for reporting this! I use [z](https://www.powershellgallery.com/packages/z/1.1.3) myself but from the PowerShell gallery and experience no issues with it. Can you provide the output of $error right after the prompt breaks? In your video, it's where you type $pwd (so replace that with $error). That way I can see what went wrong. Thx!

**Comment by masaeedu** [comment]
@JanJoris Here you go:

```
The property 'ErrorCount' cannot be found on this object. Verify that the property exists and can be set.
The property 'ErrorCount' cannot be found on this object. Verify that the property exists and can be set.
At line:4 char:9
+         $sl.ErrorCount = $global:error.Count
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : PropertyNotFound

Exception calling "Noop" with "0" argument(s): "There was no endpoint listening at net.pipe://localhost/zlocation that could accept the message. This is often caused by an incorrect address
or SOAP action. See InnerException, if present, for more details."
At C:\Program Files\WindowsPowerShell\Modules\ZLocation\0.1.0\ZLocation.Storage.psm1:117 char:13
+             $service.Noop()
+             ~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : EndpointNotFoundException
```

Looks like it is zlocation that is crashing (for whatever reason). Still, oh-my-posh should probably survive whatever happens to z.

**Comment by JanDeDobbeleer** [comment]
It seems the $sl object (local in scope) does not have the errorcount property (which it has). So, 2 questions to further narrow this down:
- does it also occur when typing an invalid command?
- do you have a global object (or other object) in scope called $sl -> type $sl to display it.

**Comment by masaeedu** [comment]
Okay, so after testing:
- No, running an arbitrary non-existent command does not break it
- No, I don't have a `$sl` object in scope (`$sl` is a null valued expression)

**Comment by JanDeDobbeleer** [comment]
That's rather weird. I'll install that z module and see what the heck is going on :-)

**Comment by JanDeDobbeleer** [comment]
Ok, so I can't explain this from oh-my-posh's side. It seems that version of z is doing stuff that isn't exactly legal. Even if I change the name of the variable, it gets wonky somewhere else (it can't find functions, variables, properties, etc). I propose to switch to a proper version of [z](https://www.powershellgallery.com/packages/z/1.1.4) to resolve this. The fact that the vors/ZLocation library fails causes this error but I really don't have time to go and fix their library (as I have one that does work). It might be best to take the error to them and have them resolve that one in the first place (it throws that on every z command, no matter what I do).

```
Exception calling "Noop" with "0" argument(s): "There was no endpoint listening at net.pipe://localhost/zlocation that could accept the message. This is often caused by an incorrect address
or SOAP action. See InnerException, if present, for more details."
At C:\Program Files\WindowsPowerShell\Modules\ZLocation\0.1.0\ZLocation.Storage.psm1:117 char:13
+             $service.Noop()
+             ~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : EndpointNotFoundException
```

**Comment by masaeedu** [comment]
@JanJoris Ok, thanks for looking into it.

**Comment by JanDeDobbeleer** [comment]
@masaeedu for reference, this bug has been open for over a year: https://github.com/vors/ZLocation/issues/23

So I don't expect anyone to fix this anytime soon :-)
