### ISSUE TITLE
Strange cursor placement and shell overriding

### ISSUE THREAD

**Issue by ashutoshbsathe** [JanDeDobbeleer/oh-my-posh2#233]
![image](https://user-images.githubusercontent.com/22210756/80347155-8dda1c00-8889-11ea-9c37-d275d1311614.png)
A lot of whitespaces between the prompt start and actual cursor. Happens with both Hyperterm as well as VSCode prompt. It also seems to overwrite the console multiple times.
![image](https://user-images.githubusercontent.com/22210756/80347631-30929a80-888a-11ea-93c3-606185c46783.png)
This isn't the issue with just "Avit" theme. It happens with every theme.

Running `$PSVersionTable` gave the following:
```
Name                           Value
----                           -----
PSVersion                      5.1.18362.752
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.18362.752
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

I'm using
oh-my-posh: v2.0.399
posh-git: v0.7.3
PowerShellGet: v2.2.4.1
PSReadLine: v2.1.0

**Comment by yuusakuri** [comment]
I have a similar problem. This problem happens occasionally, not always.

**Comment by zlatanlong** [comment]
I have a similar one, only one whitespace, seems like a regular space. But the whitespace will disapper when I type a long word. if I move the cursor to the start and delete some letters, the last litter will stay on the screen

**Comment by zlatanlong** [comment]
> I have a similar one, only one whitespace, seems like a regular space. But the whitespace will disapper when I type a long word. if I move the cursor to the start and delete some letters, the last litter will stay on the screen

I change the PromptSymbols.ElevatedSymbol and this problem is solved. 
the emoji "High Voltage Sign" cause this problem.  I change this symbol and solve

**Comment by JanDeDobbeleer** [comment]
This shouldn't happen anymore in V3, can you confirm? https://ohmyposh.dev

**Comment by ashutoshbsathe** [comment]
The issue seems to have resolved
![image](https://user-images.githubusercontent.com/22210756/95673405-c9fa0280-0bc5-11eb-9b20-976b1e132e22.png)

The new version and documentation looks pretty sweet too !
Thanks for the update 👍 

Closing this issue now

**Comment by JanDeDobbeleer** [comment]
@ashutoshbsathe make sure to check the migration guide as well as `$ThemeSettings` no longer exists 😅
https://ohmyposh.dev/docs/upgrading
