### ISSUE TITLE
Installing custom theme not looking right

### ISSUE THREAD

**Issue by VjekoslavKrainovic** [JanDeDobbeleer/oh-my-posh2#239]
After following guide how to install theme, its not looking same.
This is [guide ](https://www.hanselman.com/blog/HowToMakeAPrettyPromptInWindowsTerminalWithPowerlineNerdFontsCascadiaCodeWSLAndOhmyposh.aspx)i am following and this is [image ](https://imgur.com/aUbSOnH)of my terminal after i made all steps from guide.
I tryed on 2 different PC's.

**Comment by mondash** [comment]
Looks like you're not using a font with all the required glyphs. Check the README, and I think there's a link to a font which has them all. You can also try other fonts to find one you like with all the needed glyphs.

Edit:
Was scrubbing through the code and ran across a function that might help you. Running `Show-ThemeSymbols` will list all the symbols used in your current theme.

**Comment by JanDeDobbeleer** [comment]
> Looks like you're not using a font with all the required glyphs

Correct, that's indeed the issue.
