### ISSUE TITLE
? mark in arrow head

### ISSUE THREAD

**Issue by ghost** [JanDeDobbeleer/oh-my-posh2#24]
and this is what I got

**Comment by JanDeDobbeleer** [comment]
Hi! The same issue has been reported before and this was the solution at that time:

> okay, this problem is solved by upgrading to the latest version of conemu and set the Font Charset to ansi.

Regarding the colors, it depends on what you want to do. In case you do not like the shade of the color, you have to edit it in the ConEmu settings (change the color palette). On the other hand, if you want to have a yellow background for the path for example,  you would need to tweak `$themeSettings.Colors.PromptBackgroundColor`.

![image](https://cloud.githubusercontent.com/assets/2492783/18942985/ffc5dea8-861c-11e6-9e3b-02ff277f902e.png)

**Comment by Yhubee** [comment]
I am running the latest version of conemu, downloaded yesterday following your guide. 
Windows v. 1607 Build 14393.187.

Changing font charset to ANSI did enable the "BranchAheadStatusSymbol" to show:
![branchahead](https://cloud.githubusercontent.com/assets/22277667/18953314/b852b4d2-8645-11e6-9dcf-2f473d933c55.jpg)

But the "BranchIdenticalStatusToSymbol" (I guess that's what is expected to show) still isn't showing:
![branchidentical](https://cloud.githubusercontent.com/assets/22277667/18953346/f197b5c6-8645-11e6-894f-2d0dc99c1e6b.jpg)

Your screenshot is quite different from the one in the guide, is that part of the theme selection?
Thanks.

**Comment by JanDeDobbeleer** [comment]
You can get my setup by installing this [font](https://github.com/ryanoasis/nerd-fonts/blob/master/patched-fonts/Meslo/M/complete/Meslo%20LG%20M%20Regular%20for%20Powerline%20Nerd%20Font%20Complete.otf) and overriding the following settings:

```
Set-Theme -name 'agnoster'
$ThemeSettings.GitSymbols.BranchSymbol = [char]::ConvertFromUtf32(0xF113)
$ThemeSettings.PromptSymbols.PathSeparator = " $([char]::ConvertFromUtf32(0xE0B1)) "
$ThemeSettings.PromptSymbols.TruncatedFolderSymbol = "$([char]::ConvertFromUtf32(0xF07C)) "
$ThemeSettings.Colors.GitDefaultColor = [ConsoleColor]::Cyan
```

Regarding the symbol, check if you are using the font as me ([Meslo LG M](https://github.com/powerline/fonts/blob/master/Meslo/Meslo%20LG%20M%20Regular%20for%20Powerline.otf)) and if you can print the following symbol: `[char]::ConvertFromUtf32(0x2263)`

![image](https://cloud.githubusercontent.com/assets/2492783/18954437/6e099cd4-8653-11e6-9cf9-31ed57bd9dea.png)

Here are my font settings in ConEmu, maybe something is off there.

![image](https://cloud.githubusercontent.com/assets/2492783/18954463/86fb5ba6-8653-11e6-867e-4093e9587bd7.png)

**Comment by ghost** [comment]
I had alternative font, anti-aliasing and monospace options checked in my settings. 
It's working now.

Thanks a lot.
