### ISSUE TITLE
Tab title does not update when directory has no sub-dirs

### ISSUE THREAD

**Issue by BaconTentacles** [JanDeDobbeleer/oh-my-posh2#240]
This one is weird, and it took a while for me to track down some details, but...

When switching to a directory (via cd) that does not have any subdirectories, the title does not update.  

So, if I have a dir structure that looks something like the following:

```
Dev
\---Scripts
    \---PS
```
 
* If I cd to Dev, the title will update to show "Dev"
* If I then cd to Scripts, the title will update to show "Scripts"
* If I then cd to PS, the title will revert to the powershell executable name (powershell for PS 5, pwsh for PS 7) in ConEmu, and will revert to my user name in Microsoft Terminal (yup, tested on both because while WT is my daily driver, I know it's not fully supported there).

Here's where it gets interesting.  If I create a subdir while I am in PS (via mkdir), the title will suddenly start working again. 

CD'ing into that subdir will repro the initial issue.  

Freaky, huh?

**Comment by smokeintheshell** [comment]
Its because of lines 27-39 in oh-my-posh.psm1:

<pre>
        if($sl.Options.ConsoleTitle) {
            $location = Get-Location
            $folder = (Get-ChildItem | Select-Object -First 1).Parent.FullName
            $folderSplit = $folder -split "$([IO.Path]::DirectorySeparatorChar)", 0, "SimpleMatch"
            if ($folderSplit -gt 3)
            {
                $folder = "$($folderSplit[0])", "...", "$($folderSplit[-2])", "$($folderSplit[-1])" -join "$([IO.Path]::DirectorySeparatorChar)"
			}
            $prompt += "$([char]27)]2;$($folder)$([char]7)"
            if ($location.Provider.Name -eq "FileSystem") {
                $prompt += "$([char]27)]9;9;`"$($location.Path)`"$([char]7)"
            }
        }
</pre>

when it sets `$folder` it does so by calling get-childitem but tries to select the first object. Because its an empty folder, the `$folder` object becomes a null-value object.

This can be fixed by using `(get-location).path` instead, which will always have a value, even if you're in a different PSProvider location, such as the registry. I'll try fixing it up tomorrow and submit a PR with this change

**Comment by BaconTentacles** [comment]
Nice.  I look forward to not having to create dummy subfolders as a workaround.

**Comment by smokeintheshell** [comment]
@BaconTentacles another user, @cccc7777 submitted the PR  for this fix before I could. his commit (#265) was submitted was on June 7 but hasn't been merged by @JanDeDobbeleer 
in the meantime, i recommend you pull his oh-my-posh.psm1 and drop it in your folder

**Comment by JanDeDobbeleer** [comment]
Thx for mentioning me. Due to COVID-19 and the whole situation, my spare time is devoted to my family. I merged the PR.

**Comment by smokeintheshell** [comment]
@JanDeDobbeleer no problem, completely understand. thanks for merging!

**Comment by BaconTentacles** [comment]
> Thx for mentioning me. Due to COVID-19 and the whole situation, my spare time is devoted to my family. I merged the PR.

@JanDeDobbeleer I totally respect that and appreciate that you have your priorities straight.  Will this automatically show up in a release, or do I need to manually pull the module down and install it?  Would prefer to do Update-Module, and I can wait.  I'm patient.  

EDIT - Duh.  I updated the module but forgot to re-import.  Exiting and restarting Windows Terminal did the trick.  Looks good.  Thanks again!
