### ISSUE TITLE
Spacing

### ISSUE THREAD

**Issue by privacyguy123** [JanDeDobbeleer/oh-my-posh2#242]
How to achieve "Sparse" setting from Powerlevel10k-Classic theme for Oh My Zsh (Linux) on Windows Powershell using the same theme?

**Comment by privacyguy123** [comment]
AKA: how do I get the prompt to write out a new line at the end of every input?

**Comment by JanDeDobbeleer** [comment]
You can copy the theme and end with a newline. See [creating your own theme](https://github.com/JanDeDobbeleer/oh-my-posh#creating-your-own-theme) to facilitate that.
