### ISSUE TITLE
Incorrect path or Git bar.

### ISSUE THREAD

**Issue by yuusakuri** [JanDeDobbeleer/oh-my-posh2#243]
If execute `cls` and execute as follows, the bar display becomes strange.

```powershell
cd 'C:\Program Files (x86)\WindowsPowerShell\Modules'
cd .\Microsoft.PowerShell.Operation.Validation\
cd .\1.0.1\
cd .\Diagno
cd .\Diagnostics\
cd aljdfsdldaj
```

The example is a path bar, but moving to a Git repository causes similar issues.

![issueohmyposhwinterm](https://user-images.githubusercontent.com/58417213/81694320-28e31080-949c-11ea-90f4-b728aea69238.PNG)

**Comment by RainHuih** [comment]
![image](https://user-images.githubusercontent.com/36627364/83829721-1912c100-a716-11ea-9413-43729d7afbbc.png)
I have the same problem

**Comment by rescenic** [comment]
I got the same problem too. I reinstalled my Windows 10 laptop. Then, the problem is gone. Maybe, my Windows PowerShell is broken. Try installing in PowerShell Core, check if the problem occurs or not.

**Comment by RainHuih** [comment]
> I got the same problem too. I reinstalled my Windows 10 laptop. Then, the problem is gone. Maybe, my Windows PowerShell is broken. Try installing in PowerShell Core, check if the problem occurs or not.

Thanks, I will try later.

**Comment by RainHuih** [comment]
I solved the problem by modifying the script "oh-my-posh.psm1"(C:\Users\[UserName]\Documents\PowerShell\Modules\oh-my-posh\2.0.412\oh-my-posh.psm1)
![](https://raw.githubusercontent.com/HowieHye/gallery/master/20200605131141.png)

**Comment by yuusakuri** [comment]
Some of the issues have been resolved in PowerShell 7.
However, there is a problem that the path overlaps with the time and is cut off.
![time-path](https://user-images.githubusercontent.com/58417213/84304210-22c37b00-ab93-11ea-9ffd-62b07dd93c66.PNG)

**Comment by JanDeDobbeleer** [comment]
> I solved the problem by modifying the script

@HowieHye care to clarify what you did?

**Comment by holazt** [comment]
> > I solved the problem by modifying the script
> 
> @HowieHye care to clarify what you did?

It's easy to do, modify the file `%USERPROFILE%\Documents\PowerShell\Modules\oh-my-posh\2.0.468\oh-my-posh.psm1`, comment that two lines out as following screenshot,
![image](https://user-images.githubusercontent.com/10769951/91634278-d9f8c100-ea21-11ea-92a3-98df7f72ce70.png)

**Comment by JanDeDobbeleer** [comment]
This shouldn't happen anymore in V3, can you confirm? https://ohmyposh.dev
