### ISSUE TITLE
Some characters appears as quares on windows terminal

### ISSUE THREAD

**Issue by abdellatifLabr** [JanDeDobbeleer/oh-my-posh2#246]
is there a solution for this ?
![image](https://user-images.githubusercontent.com/17796722/82120362-54584a80-977d-11ea-90be-f538d3b4e4f8.png)

**Comment by mathis-m** [comment]
@labTifo i guess your font does not support powerline glyphs.

**Comment by mathis-m** [comment]
Try to change the font:
1. In windows terminal open settings (some json file).
2. Find the powershell profile
3. Insert some font with powerline glyphs:
"commandline": "powershell.exe",
"fontFace": "JetBrainsMono NF"

As @JanDeDobbeleer states in his readme: [Nerd Fonts](https://github.com/ryanoasis/nerd-fonts) is great repository where you can find some great fonts that support powerline glyphs or are patched to do so.

**Comment by abdellatifLabr** [comment]
Thank you @mathis-m
