### ISSUE TITLE
Will this work with Fluent Terminal?

### ISSUE THREAD

**Issue by plastikfan** [JanDeDobbeleer/oh-my-posh2#248]
I find that [FluentTerminal](https://github.com/felixse/FluentTerminal) is easier to use and especially to configure than Windows Terminal. Will it work in FT and if so, please could you update README to indicate this. Thanks.

**Comment by nwykes** [comment]
I haven't tried FluentTerminal but its FAQ discusses using oh-my-posh to get the look seen in the readme.  https://github.com/felixse/FluentTerminal/wiki/FAQ

**Comment by plastikfan** [comment]
Thanks @nwykes, I have setup fluent terminal with oh my posh and it works great. It would be nice if the documentation on oh my posh would reflect that
