### ISSUE TITLE
Get-VCSStatus no longer returns RepoName property

### ISSUE THREAD

**Issue by mikesigs** [JanDeDobbeleer/oh-my-posh2#250]
The title pretty much says it all. The Get-VCSStatus helper function used to return a RepoName property, now it doesn't.

**Comment by nwykes** [comment]
Get-VCSStatus is just a wrapper around a posh-git function.  RepoName wasn't added until the 1.0.0-beta2 so you'll need to install the prerelease version of posh-git in order to get it.

**Comment by mikesigs** [comment]
I have been using Get-VCSStatus for a couple years now though and I never used the beta.

**Comment by mikesigs** [comment]
The version of oh-my-posh I was using when I posted this issue was 2.0.311. And it used `Get-Command Get-GitStatus` to retrieve its value. And my posh-git version is 1.0.0.

So you are suggesting then that I just use Get-GitStatus directly then?
