### ISSUE TITLE
Reduce startup time of Powershell profile on oh-my-posh

### ISSUE THREAD

**Issue by cardin** [JanDeDobbeleer/oh-my-posh2#251]
**Problem**
Installing oh-my-posh and post-git has increased the average Powershell startup time from negligible to 500-2000 ms. Powershell even mentions it: "_Loading personal and system profiles took 1084ms._"

Tried on an empty Powershell 7 profile and an empty Powershell 5 profile, with `Set-Theme Paradox`, on Windows 10 1909.

**Desired Outcome**
oh-my-posh's impact on Powershell startup time should be reduced.

One possible way could be to reduce the dependency on posh-git - there might be several posh-git functions in there that are unused.

**Comment by JanDeDobbeleer** [comment]
I have a new engine that removes that dependency, but it's not ready for prime time just yet.

**Comment by EvilVir** [comment]
Yes, it's way too slow for daily use, at least for me :(

**Comment by Maples7** [comment]
In addition, it's very slow for huge git codebase to show Git status indications. 
So for me, I have to abandon the Git status indications unwillingly.
😢

**Comment by Maples7** [comment]
I've tried https://github.com/cmarcusreid/git-status-cache-posh-client and it could help to **mitigate** the problem.

**Comment by PreetSangha** [comment]
I've just installed the latest versions for the first time and unfortunately it's massively slow. Are there any tweaks I can use to make my prompt appear in a usable time please?? 

![image](https://user-images.githubusercontent.com/15098094/86583637-b7c16480-bfd7-11ea-9a51-a435ee657323.png)

**Comment by PreetSangha** [comment]
> I've just installed the latest versions for the first time and unfortunately it's massively slow. Are there any tweaks I can use to make my prompt appear in a usable time please??
> 
> ![image](https://user-images.githubusercontent.com/15098094/86583637-b7c16480-bfd7-11ea-9a51-a435ee657323.png)

Never mind. I've worked out that all I needed to do was install the modules for allusers in an elevated prompt and remove them from the profile. _I've left commands commented out in my profile_, viz.:

```
# run these from an elevated prompt and make sure that they are commented out here..
#Install-Module posh-git -scope AllUsers
#Install-Module oh-my-posh -scope AllUsers


Set-Theme agnoster

```
![image](https://user-images.githubusercontent.com/15098094/86586406-f0fbd380-bfdb-11ea-9fcc-eeaf447bf21f.png)

**Comment by avezinaATastus** [comment]
Installing as admin didn't change my startup speed
@PreetSangha

**Comment by PreetSangha** [comment]
> Installing as admin didn't change my startup speed
> @PreetSangha

so you installed the modules for all users? Did you remember to take the install-module commands out of your profile now? Note that I have them commented out in the above? I've edited the comment to make it clearer.

Preet

**Comment by avezinaATastus** [comment]
Yes.
I don't have install-modules in my profile.
I did remove the comment marks

```
PS> get-module oh-my-posh,posh-git -ListAvailable

Directory: C:\Program Files\WindowsPowerShell\Modules


ModuleType Version    Name                                ExportedCommands                                             
---------- -------    ----                                ----------------                                             
Script     2.0.443    oh-my-posh                          {Write-ColorPreview, Show-Colors, Show-ThemeColors, Show-T...
Script     0.7.3      posh-git                            {Invoke-NullCoalescing, Add-PoshGitToProfile, Get-PromptPa...

```

**Comment by PreetSangha** [comment]
What else do you have in your profile? Perhaps it's that that's taking the time?

**Comment by JanDeDobbeleer** [comment]
Hey @cardin. I just published my [new engine](https://www.powershellgallery.com/packages/go-my-posh). That one has no trouble with startup/rendering times.

You can install and use it as follows

```powershell
Install-Module -Name go-my-posh -Repository PSGallery
Import-Module go-my-posh
Set-PoshPrompt paradox
```

if you want, you can also list all available themes

```powershell
Get-PoshThemes
```

Feel free to create an issue there as well to follow up in case you find problems.
I will keep an eye on `oh-my-posh`, but I'll favor `go-my-posh` going forward.

**Comment by GF-Huang** [comment]
So no solutions? I still took 800ms.

![image](https://user-images.githubusercontent.com/4510984/96747006-60b29480-13fa-11eb-8092-4fe99c0a7c76.png)

**Comment by JanDeDobbeleer** [comment]
@GF-Huang `Set-Theme` is V2, not V3.
See https://ohmyposh.dev

**Comment by GF-Huang** [comment]
> @GF-Huang `Set-Theme` is V2, not V3.
> See https://ohmyposh.dev

This? 

> [ScriptBlock]$Prompt = {
>   $realLASTEXITCODE = $global:LASTEXITCODE
>   & "C:\tools\oh-my-posh.exe" -config "~/downloadedtheme.json" -error $realLASTEXITCODE -pwd $PWD
>   $global:LASTEXITCODE = $realLASTEXITCODE
>   Remove-Variable realLASTEXITCODE -Confirm:$false
> }
> Set-Item -Path Function:prompt -Value $Prompt -Force

**Comment by JanDeDobbeleer** [comment]
You can easily update to the beta of oh-my-posh.
https://ohmyposh.dev/docs/upgrading

**Comment by nwykes** [comment]
800ms is pretty fast?  less than a second startup time seems reasonable.
