### ISSUE TITLE
Using Windows Terminal scheme colours

### ISSUE THREAD

**Issue by T-Flet** [JanDeDobbeleer/oh-my-posh2#253]
`ConsoleColor` uses a different colour naming convention from the Windows Terminal colour schemes, however, are its enumeration values not supposed to pick up those set by the scheme anyway (e.g.  `[ConsoleColor]::DarkBlue` -> `blue` and `[ConsoleColor]::Blue` -> `brightBlue`)?

(Related Terminal issue https://github.com/microsoft/terminal/issues/5670 and scheme naming issue: https://github.com/microsoft/terminal/issues/2641)

On which side is the issue occurring?

**Comment by JanDeDobbeleer** [comment]
I would have always supposed this is agnostic on my part as I use the ConsoleColor enumeration. If the Windows terminal defines something on it's own, it's either to PSCore to map it correctly, but simply coming up with your own stuff while the API is cross platform compatible is just asking for issues, no?
