### ISSUE TITLE
ZSH Completions Issue

### ISSUE THREAD

**Issue by rescenic** [JanDeDobbeleer/oh-my-posh2#258]
I've installed oh-my-posh in both Windows PowerShell & PowerShell Core.
But in Windows PowerShell it doesn't show syntax highlighting/completions from command history but in PowerShell Core, it can show it.
Can you help me?
![ps](https://i.ibb.co/fGK7K0L/30-05-2020-675-18-48-33.png)

**Comment by JanDeDobbeleer** [comment]
As of a few versions back I only added support for Core as it was getting difficult to maintain this on my own.

**Comment by rescenic** [comment]
It's working again, I've updated PSReadLine.
![psreadline](https://i.ibb.co/SdD6v61/06-06-2020-751-03-11-21.png)
