### ISSUE TITLE
the glypes of theme "robbyrussell" are too small

### ISSUE THREAD

**Issue by jaisharx** [JanDeDobbeleer/oh-my-posh2#259]
![Annotation 2020-06-03 053310](https://user-images.githubusercontent.com/55892116/83637075-da390b80-a55b-11ea-84b7-943d2b77b1cb.png)

**You can see how the arrow and the X glypes are too small, while all the other character are of normal size. Please fix this! I really like this theme, would love if this small problem gets fixed**

![Annotation 2020-06-03 053710](https://user-images.githubusercontent.com/55892116/83637321-4ae02800-a55c-11ea-8310-eea1a4a18c17.png)

**You can see how the default glyph that comes is so small compared to anything like a font ligature of dash followed by an arrow (->)**

PS: I'm using the new Windows Terminal with Cascadia Code font

**Comment by rescenic** [comment]
Glypes depend on font. Try Nerd Font like Hack NF.

**Comment by jaisharx** [comment]
**using cascadia code font**
![cascadia code pl](https://user-images.githubusercontent.com/55892116/83708233-6c631180-a639-11ea-88a9-260985ab25b0.png)

**using fira code font**
![fira code](https://user-images.githubusercontent.com/55892116/83708283-869cef80-a639-11ea-9871-60048b31321e.png)

**using nerd font**
![nerd font](https://user-images.githubusercontent.com/55892116/83708314-a207fa80-a639-11ea-91c0-e220f47e5d21.png)


As you can see, I tried using 3 different fonts, as they work as usual, but the size of ~ and -> are just as small, it's really been bugging me out. Thanks.

**Comment by rescenic** [comment]
For temporary solution, you can zoom in with Ctrl+Scroll mouse.
For permanent font size, add setting: "fontSize": 14 in Windows Terminal settings.json.

Zoomed -in PowerShell 7 Terminal:
![ps1](https://i.ibb.co/vVfNC5h/04-06-2020-711-09-44-14.png)

Zoomed-in PowerShell 7 in Windows Terminal:
![ps2](https://i.ibb.co/JmZVTfg/04-06-2020-712-09-46-54.png)

**Comment by jaisharx** [comment]
![Annotation 2020-06-04 082720](https://user-images.githubusercontent.com/55892116/83709945-39bb1800-a63d-11ea-8b52-077455cf0b87.png)

I've tried increasing the font size, but putting that to 14 makes the text really huge, while the arrow and other glyphs are still relatively small
To put that in better perspective, compare the arrow with the ligature version of arrow, in my initial screenshot I've shared.

**Comment by JanDeDobbeleer** [comment]
I'm not really in control of how the fonts are rendered. It does depends on the font size and font used.
