### ISSUE TITLE
Does not start due to wrong(?) version information in oh-my-posh.psd1

### ISSUE THREAD

**Issue by dl1ely** [JanDeDobbeleer/oh-my-posh2#26]
When doing `. $Profile` after install:

```
Import-Module : The 'ModuleVersion' member is not valid in the module manifest file
'C:\Users\pfeiffer.stefan\Documents\WindowsPowerShell\Modules\oh-my-posh\oh-my-posh.psd1': Cannot convert value "%version%" to type "System.Version". Error: "Version
string portion was too short or too long."
At C:\Users\pfeiffer.stefan\Documents\WindowsPowerShell\Microsoft.PowerShell_profile.ps1:6 char:1
+ Import-Module oh-my-posh
+ ~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (C:\Users\pfeiff...oh-my-posh.psd1:String) [Import-Module], ArgumentException
    + FullyQualifiedErrorId : Modules_InvalidManifest,Microsoft.PowerShell.Commands.ImportModuleCommand
```

Using Win7, Powershell 5.0. Any ideas?

**Comment by JanDeDobbeleer** [comment]
My guess is you installed using PSGet?
It seems I forgot to tweak PSGet to fetch a release zip instead of the zipped master branch. The quick fix is to manually alter the version number in `C:\Users\pfeiffer.stefan\Documents\WindowsPowerShell\Modules\oh-my-posh\oh-my-posh.psd1`  (%version% to 2.0.1) or install the module using the PowerShell Gallery:

```
Install-Module posh-git -Scope CurrentUser
Install-Module oh-my-posh -Scope CurrentUser
```

I'll fix PSGet in the meantime but that might take a while as I have to get them to accept a pull request too :-)

**Comment by dl1ely** [comment]
No, i used `Install-Module`, not `PSGet`. I already had posh-git installed before, so i ommitted that line. Thanks for suggesting the workaround.

**Comment by JanDeDobbeleer** [comment]
@dl1ely I'm confused as installing it using the Gallery will not have that bug. If you install using just `Install-Module oh-my-posh`, that would mean you'd have used PSGet to install it. In case you used `Install-Module oh-my-posh -Scope CurrentUser` that would mean you went to the gallery to download it (you can have both installed on your machine).

Either way, I'm writing a fix to resolve this :-)

**Comment by JanDeDobbeleer** [comment]
It seems I'm unable to still support PSGet given the change I made to automatically up the version number. I could create a rather complex workaround but that would not be a good solution. And I need the automagic numbering to not resort to asking "Please update the version number" every time a person opens a PR.

**Comment by JanDeDobbeleer** [comment]
I create a [PR](https://github.com/psget/psget/pull/226) to remove oh-my-posh from the PsGet Directory.

**Comment by dl1ely** [comment]
OK, now i am confused myself. I am working on a machine with no admin rights for me. I removed the oh-my-posh module to reproduce the error. But now i cannot reinstall oh-my-posh anymore at all.
- `Install-Module oh-my-posh` fails due to missing admin rights
- `Install-Module oh-my-posh -Scope CurrentUser` fails as i have to install NuGet, which i am not allowed to do
- `Install-Module -ModuleUrl <link to latest oh-my-posh.zip>` fails because it has no `-ModuleUrl` parameter:

```
 NAME
    Install-Module

SYNTAX
    Install-Module [-Name] <string[]> [-MinimumVersion <version>] [-MaximumVersion <version>] [-RequiredVersion <version>] [-Repository <string[]>] [-Scope <string>
    {CurrentUser | AllUsers}] [-Force] [-WhatIf] [-Confirm]  [<CommonParameters>]

    Install-Module [-InputObject] <psobject[]> [-Scope <string> {CurrentUser | AllUsers}] [-Force] [-WhatIf] [-Confirm]  [<CommonParameters>]
```

`$PSVersionTable.PSVersion` is

```
Major  Minor  Build  Revision
-----  -----  -----  --------
5      0      10586  117
```

Right now, i have no idea how i got oh-my-posh on my machine at all. :confused:

**Comment by JanDeDobbeleer** [comment]
Ok, let's fix this :-)

**Option 1: Install PsGet and install**
- In PowerShell: `(new-object Net.WebClient).DownloadString("http://psget.net/GetPsGet.ps1") | iex`
- In PowerShell: `Import-Module psget`
- In PowerShell (make sure you use the correct `Install-Module` function): `Install-Module -ModuleUrl https://github.com/JanJoris/oh-my-posh/releases/download/2.0.29/oh-my-posh.zip`
- In PowerShell: `Import-Module oh-my-posh`
- Profit

**Option 2: Manual install**
- Download `https://github.com/JanJoris/oh-my-posh/releases/download/2.0.29/oh-my-posh.zip` and unzip to `C:\Users\pfeiffer.stefan\Documents\WindowsPowerShell\Modules\oh-my-posh\` (make sure that folder has the files and no extra subfolder called `oh-my-posh`).
- In PowerShell: `Import-Module -Name C:\Users\pfeiffer.stefan\Documents\WindowsPowerShell\Modules\oh-my-posh`
- Profit

My guess is option 2 will give a higher degree of success.

**Comment by dl1ely** [comment]
I could work arount my NuGet-Problems (Proxy server settings related) and install the NuGet Package Provider, but now this for `Install-Module oh-my-posh -Scope CurrentUser`:

```
PackageManagement\Install-Package : Es wurde keine Übereinstimmung für die angegebenen Suchkriterien und den Paketnamen "oh-my-posh" gefunden.
At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:1375 char:21
+ ...          $null = PackageManagement\Install-Package @PSBoundParameters
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Microsoft.Power....InstallPackage:InstallPackage) [Install-Package], Exception
    + FullyQualifiedErrorId : NoMatchFoundForCriteria,Microsoft.PowerShell.PackageManagement.Cmdlets.InstallPackage
```

I am not sure if this is proxy related, too, but all other commands pulling stuff from the net (`update-help`) work now. This evening i can try on my Win10 installation at home with admin rights. I assume everything will work smoothly over there :-(

**Comment by dl1ely** [comment]
Oh, our last comments crossed, https://github.com/JanJoris/oh-my-posh/issues/26#issuecomment-252185809 was before i read your last comment

**Comment by dl1ely** [comment]
Option 1 worked for me :+1: Just to get that straight, there are different "flavors" of `Install-Module` commands? and i had the wrong one installed?

I am very confused right now, but anyway thank you very much for your help.

**Comment by JanDeDobbeleer** [comment]
There are two package providers, PsGet and the Powershell gallery. PsGet came first and afterwards the Gallery (which is the official package provider now) got introduced. Both of them use the same cmdlets (which makes all of this super confusing). I have no idea why he can't install the module using the Gallery other than it would not be allowed on your machine to access it. I really, really dislike policies on machines 😠 

But, I'm glad we managed to fix this!
