### ISSUE TITLE
Piping to awk in Windows 10 causes odd issue

### ISSUE THREAD

**Issue by arnabanimesh** [JanDeDobbeleer/oh-my-posh2#260]
Refer  to the below-mentioned screenshots:

![image](https://user-images.githubusercontent.com/6032584/83933495-a0b80880-a7c6-11ea-8e0a-fa2745cd1160.png)
![image](https://user-images.githubusercontent.com/6032584/83933502-b2011500-a7c6-11ea-9dcc-0df9e83be648.png)

It also has a windows chime (error sound) associated with it.

This `awk.exe (GNU Awk 5.1.0)` is located in `/usr/bin/awk.exe` of `msys64`.

I have tried it with **PS Core in Ubuntu (zsh)**, and also with **vanilla PowerShell 5**.

It does not seem to throw any error anywhere else.

**Comment by JanDeDobbeleer** [comment]
This seems to be related to #270 which also has issues with unix exectuables. No idea why though.

**Comment by JanDeDobbeleer** [comment]
@arnabanimesh can you check if this is still an issue on V3? Https://ohmyposh.dev

**Comment by arnabanimesh** [comment]
This issue has been resolved in V3.
