### ISSUE TITLE
Support for Light Theme

### ISSUE THREAD

**Issue by DivNectar** [JanDeDobbeleer/oh-my-posh2#267]
Currently, whenever I use a light theme for my terminal the prompts become un-readable:

![image](https://user-images.githubusercontent.com/62819144/85233502-e125a200-b3d4-11ea-99aa-6d843d0ee65d.png)

I think we should be able to specify in the profile is we are using a light or dark theme, and adjust the prompt colors respectively

**Comment by JanDeDobbeleer** [comment]
That's really tricky as I can't guess the colors being used. This will always require some form of tweaking (I have two configs available that myself for this use-case)
