### ISSUE TITLE
Noob help:  Customize suffix based on environment variable

### ISSUE THREAD

**Issue by drmikecrowe** [JanDeDobbeleer/oh-my-posh2#268]
Sorry if this is obvious and I'm missing it, but I'd like to add a new section to the prompt based on my current AWS_PROFILE set in the environment.

If $Env:AWS_PROFILE="dev", something like (green)[dev](/green)
If $Env:AWS_PROFILE="tst", something like (yellow)[TST](/yellow)
If $Env:AWS_PROFILE="prd", something like (red)[PRD](/red)

Is this possible?  Where would I start?

**Comment by JanDeDobbeleer** [comment]
Perfectly possible by creating your own theme. Feel free to browse through `Themes/*`, select the one you like and add it where you want. I can always help out if you tell me which theme you'd like to use and where you'd like to add that specific part.
