### ISSUE TITLE
issue with theme and git-grep

### ISSUE THREAD

**Issue by imba-tjd** [JanDeDobbeleer/oh-my-posh2#270]
I'm using a grep.exe in Win, which I think is from `git for windows` (https://git-scm.com/download/win)

![图片](https://user-images.githubusercontent.com/24759802/86333462-831f7700-bc7e-11ea-92a9-db09873ffc48.png)

**Comment by JanDeDobbeleer** [comment]
Can you elaborate on that screenshot a little bit?

**Comment by imba-tjd** [comment]
You can reproduce it by `echo 123 | grep 1`, which grep.exe is from git for windows

**Comment by JanDeDobbeleer** [comment]
This seems to be an issue on Windows only as I can't reproduce this on Mac with grep.

**Comment by Jesper-Hustad** [comment]
Win 10 Build 18363, could not reproduce.
![image](https://user-images.githubusercontent.com/17168694/95342160-674bf280-08b7-11eb-9cb5-cf6e0c3d15ea.png)

**Comment by JanDeDobbeleer** [comment]
Hey @Jesper-Hustad can you try with version 3?
See https://gomyposh.dev for more context, quite a bit has changed.

**Comment by imba-tjd** [comment]
I have tested v3 with the default theme and this issue didn't happen
