### ISSUE TITLE
Allow disabling posh-git

### ISSUE THREAD

**Issue by imba-tjd** [JanDeDobbeleer/oh-my-posh2#271]
VS Code has a Git GUI, I don't want pwsh show git message when I'm in VSC.

I have found a way to detect whether pwsh is inside VSC: https://askubuntu.com/questions/1021554/can-i-check-if-the-terminal-was-started-by-visual-studio-code

But it seems that if I used a theme, I can't get rid of posh-git.

**Comment by Bak-Jin-Hyeong** [comment]
Is this what you want?

```powershell
# Put it in your $PROFILE
if ($env:TERM_PROGRAM -ne 'vscode') {
    $GitPromptSettings.EnableFileStatus = $false
    $GitPromptSettings.EnablePromptStatus = $false
}
```

**Comment by imba-tjd** [comment]
@Bak-Jin-Hyeong Thank you! Changing the `-ne` to `-eq` is what I want, though not completely.
Ideally I think there should be a setting to not enable posh-git, so that this project would be less coupling with posh-git and the speed might be a little up.
