### ISSUE TITLE
Feature request for Paradox theme: use different color to distinguish git staging (index) and working directory status

### ISSUE THREAD

**Issue by cosmosb** [JanDeDobbeleer/oh-my-posh2#272]
Vanilla posh-git shows staging (index) and working directory information in different color which is same as color scheme used by `git status` command.

![image](https://user-images.githubusercontent.com/14336518/86493177-58d4c480-bd25-11ea-8d77-b6f7eaa3fc50.png)

When using Paradox theme, it shows everything using single color:

![image](https://user-images.githubusercontent.com/14336518/86493348-12cc3080-bd26-11ea-9d7c-65fd339c8e1f.png)

I am guessing there is a way to override all prompt colors but if this is part of theme, that would be great.

If someone knows how to change color of these info, please let me know. 

Thanks.

**Comment by Cruik** [comment]
The Paradox Theme is awesome, but this is the only thing im missing too!

Would be great if someone has a solution to this one

**Comment by JanDeDobbeleer** [comment]
This requires a bit more work as you need to tweak the `PoshGit.ps1` code to have that functionality. It should be "that" hard and we can even make it backwards compatible as it only affects colors. I'll see what I can do.

**Comment by JanDeDobbeleer** [comment]
Hey @cosmosb AND @Cruik. I just published my [new engine](https://www.powershellgallery.com/packages/go-my-posh). That's the one to [follow-up progress](https://github.com/JanDeDobbeleer/go-my-posh/issues/4) regarding this is about.

You can install and use it as follows

```powershell
Install-Module -Name go-my-posh -Repository PSGallery
Import-Module go-my-posh
Set-PoshPrompt paradox
```

if you want, you can also list all available themes

```powershell
Get-PoshThemes
```

I will keep an eye on `oh-my-posh`, but I'll favor `go-my-posh` going forward.
