### ISSUE TITLE
$LASTEXITCODE lost when themed (by Paradox)

### ISSUE THREAD

**Issue by AArnott** [JanDeDobbeleer/oh-my-posh2#273]
I have an Exit27.ps1 script with nothing but `Exit 27` as its content.
My `$PROFILE` script is:

```ps1
Import-Module posh-git
Import-Module oh-my-posh
Set-Theme Paradox
```

In PowerShell, when in a git repo directory, if I run `.\Exit27.ps1` and then immediately after `$LASTEXITCODE`, I get `0`.
If I comment out `Set-Theme Paradox` from my `$PROFILE` script, the problem goes away and I get `27` from the last command.

Is the bug in `oh-my-posh` itself or the Paradox theme?

**Comment by JanDeDobbeleer** [comment]
The thing is, the prompt function will overrule `$LASTEXITCODE` with it's execution. What we could try is to set the remembered value just before exiting (need to check if that actually works though).

**Comment by AArnott** [comment]
I've seen that technique used successfully before.

**Comment by JanDeDobbeleer** [comment]
I can't seem to find a way.

**Comment by AArnott** [comment]
@JanDeDobbeleer Doesn't this work? https://stackoverflow.com/questions/6014042/custom-powershell-prompt-is-clearing-lastexitcode

**Comment by AArnott** [comment]
I just tested the fix and it seems effective. Thanks!

**Comment by JanDeDobbeleer** [comment]
Sorry it took so long.
