### ISSUE TITLE
In Windows terminal, the special symbols on the path are displayed as garbled code

### ISSUE THREAD

**Issue by justdwang** [JanDeDobbeleer/oh-my-posh2#276]
In Windows Terminal, the special symbols on the path are displayed as garbled code.

![image](https://user-images.githubusercontent.com/17848929/87263662-73aaf400-c4f0-11ea-9935-9cb2a5146dbd.png)

How to solve this problem?

PowerShell Version: 7.0.2
Windows Terminal Version: 1.0.1811.0

**Comment by ghost** [comment]
I see the same behaviour for PowerShell 7.0.2 and 5.1 with Windows Terminal 1.0.1811.0 on Windows 10 1909.

![image](https://user-images.githubusercontent.com/21143177/87328358-46c90200-c52d-11ea-8636-e87ae8eff3fe.png)

**Comment by justdwang** [comment]
hi all, 
I solved this problem by installing the Hack font at https://github.com/source-foundry/Hack-windows-installer/releases/tag/v1.6.0.

**Comment by dima11221122** [comment]
I've installed the font but it doesn't help

**Comment by murmelbahn** [comment]
Sadly I have the same problem. Installation the font did not fix it for me.

**Comment by justdwang** [comment]
![image](https://user-images.githubusercontent.com/17848929/87544880-c0055800-c6d9-11ea-9f57-b2590f37e5f7.png)

Try setting "fontFace"

**Comment by akozlev** [comment]
This is another good resource with Fonts that support the special characters. 
https://medium.com/@slmeng/how-to-install-powerline-fonts-in-windows-b2eedecace58

You can then set the font in the settings.json per profile or as default.

Here is my settings.json for example: https://gist.github.com/akozlev/ecf40de8b142622502116a5abfcc9ade

**Comment by JanDeDobbeleer** [comment]
Assuming this is a font issue I'm closing this.
