### ISSUE TITLE
[Feature] Git aliases

### ISSUE THREAD

**Issue by VelocityRa** [JanDeDobbeleer/oh-my-posh2#278]
oh-my-zsh includes [a nice collection of git aliases](https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/git), it'd be nice to support this here too.

**Comment by AjayKMehta** [comment]
@VelocityRa, you might be interested in [this module](https://github.com/gluons/powershell-git-aliases)?

If you want to add git aliases, why not just add them to your global .gitconfig? Then you can use them anywhere, i.e. PowerShell, git bash...

**Comment by VelocityRa** [comment]
For git's aliases you still have to use `git` before them.
Thanks for linking that :) Just what I needed.

**Comment by AjayKMehta** [comment]
You're welcome.
