### ISSUE TITLE
Spaceship theme on PowerShell

### ISSUE THREAD

**Issue by Jorggyh** [JanDeDobbeleer/oh-my-posh2#283]
Hello, I am currently using the spaceship theme on my zsh and I think it is amazing, I would like to know if it is possible to use it on PowerShell too, I'm also using ow my posh, but I don't have enough knowledge to add this theme myself.

**Comment by JanDeDobbeleer** [comment]
Well, the only thing you need is to read through the docs [here](https://github.com/JanDeDobbeleer/oh-my-posh#creating-your-own-theme) and some spare time :-)
