### ISSUE TITLE
How display full path instead of relative?

### ISSUE THREAD

**Issue by rgelb** [JanDeDobbeleer/oh-my-posh2#286]
The current prompt looks like this:

![image](https://user-images.githubusercontent.com/1064250/89214456-b1dd8580-d57b-11ea-920a-54ad0cda0e0e.png)

Is there a way to show the full path, instead of relative?  Like this:

c:\users\myuser\desktop\af code\af.thermalapp > master

**Comment by JanDeDobbeleer** [comment]
You can create a [custom theme](https://github.com/JanDeDobbeleer/oh-my-posh#creating-your-own-theme) and use `$PWD` for that.
