### ISSUE TITLE
To ask some , how to use in OS X

### ISSUE THREAD

**Issue by aizigao** [JanDeDobbeleer/oh-my-posh2#29]
😄

**Comment by JanDeDobbeleer** [comment]
Never tried it but you should be able to install [PowerShell](https://github.com/PowerShell/PowerShell/blob/master/docs/installation/linux.md#macos-1011) and then use `Install-Module oh-my-posh -scope currentuser` to install it (install posh-git too). But I've never tried this before 😎

**Comment by aizigao** [comment]
I had tried ，it wrong.. XD
