### ISSUE TITLE
How can I hide user name?

### ISSUE THREAD

**Issue by rediffusion** [JanDeDobbeleer/oh-my-posh2#290]
How can I hide this?

![image](https://user-images.githubusercontent.com/30071027/90523374-78109f80-e175-11ea-9ed7-5736e939947d.png)

**Comment by JanDeDobbeleer** [comment]
Not yet ATM, unless you create a new theme. You can find out about that [here](https://github.com/JanDeDobbeleer/oh-my-posh#creating-your-own-theme). I'm about to create an alpha of V2 that has the ability to display whatever you want and don't want so check back in a little month :-)

**Comment by rediffusion** [comment]
@JanDeDobbeleer

 I'm just going here:

> C:\Users\HOME-PC\Documents\WindowsPowerShell\Modules\oh-my-posh\2.0.449\Themes\

...then in file "Paradox" comment some lines, now it looks like this:

```
    # $user = $sl.CurrentUser
    # $computer = $sl.CurrentHostname
    $path = Get-FullPath -dir $pwd
    # if (Test-NotDefaultUser($user)) {
    #     $prompt += Write-Prompt -Object "$user@$computer " -ForegroundColor $sl.Colors.SessionInfoForegroundColor -BackgroundColor $sl.Colors.SessionInfoBackgroundColor
    # }
```

 Can get where is this symbol?

![image](https://user-images.githubusercontent.com/30071027/90655000-b7102500-e249-11ea-938e-9b0d132549bf.png)

 I want it for the right prompt...

**Comment by JanDeDobbeleer** [comment]
That symbol is the Administrator symbol. Top of my head, there should be a Test-Administrator function which will print that one if so.

**Comment by rediffusion** [comment]
@JanDeDobbeleer 

Exactly❗

 Now my file looks like 🔗 [this](https://dropmefiles.com/DJZ7u):

 I made change:

> $prompt += Set-CursorForRightBlockWrite -textLength ($timestamp.Length + 1)

...to

> $prompt += Set-CursorForRightBlockWrite -textLength ($timestamp.Length + 2)

 Now, attention! I put after, this code:

>     #check for elevated prompt
>     If (Test-Administrator) {
>         $prompt += Write-Prompt -Object "$($sl.PromptSymbols.ElevatedSymbol) " -ForegroundColor $sl.Colors.AdminIconForegroundColor -BackgroundColor $sl.Colors.SessionInfoBackgroundColor
>     }

 Works like a charm. Cheers! 👍⭐
