### ISSUE TITLE
[Feature request] option for adding background color for label in Agnoster

### ISSUE THREAD

**Issue by ReinWD** [JanDeDobbeleer/oh-my-posh2#291]
![image](https://user-images.githubusercontent.com/22649596/90875182-5d3b6680-e3d3-11ea-9ff5-f744f4ad8779.png)
Here's what happend when I installed Windows-terminal.
It was resulted by different transparency implementation of PowerShell & Windows Terminal.
Maybe adding a background color can improve exprience on Windows Terminal.

Other Agnoster-like skins may also have this issue.

**Comment by ReinWD** [comment]
Windows Terminal uses "[Acrylic](https://docs.microsoft.com/en-us/windows/terminal/customize-settings/profile-settings#acrylic-settings)" to get a Acrylic-like look and feel. Text color is not affected by this effect(or they will just be blured).

![image](https://user-images.githubusercontent.com/22649596/90877587-e607d180-e3d6-11ea-84c5-ca3b81869514.png)

oh-my-fish in WSL&fish works just fine in Windows Terminal.

**Comment by ReinWD** [comment]
Seems that my clients are specially replacing Black color in background with transparent.
"Black" color in  background is regarded as transparent by Windows Terminal and IntelliJ Terminal.

Wondering how WSL display black background in Windows Terminal, but transparent in IntelliJ Terminal.

So is it possible to display "real Black" background in every client? e.g. #010101?

**Comment by JanDeDobbeleer** [comment]
I have a new engine in the works that resolves all of this for you. Color management on Windows a few years ago was a real PITA and very basic. Thankfully that's now resolved as terminals have evolved to actual terminals, so we can fix this properly. Stay tuned, I hope to have ported all the available themes somewhere by next week, at that time I consider it ready for a public release.

**Comment by ReinWD** [comment]
Nice Job!
