### ISSUE TITLE
I can't install - Access Error

### ISSUE THREAD

**Issue by carloscds** [JanDeDobbeleer/oh-my-posh2#293]
Hi,

When I try to install, I receive this error:

PackageManagement\Install-Package : Access to the cloud file is denied
At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:1809 char:21
+ ...          $null = PackageManagement\Install-Package @PSBoundParameters
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Microsoft.Power....InstallPackage:InstallPackage) [Install-Package], Exce
   ption
    + FullyQualifiedErrorId : System.ComponentModel.Win32Exception,Microsoft.PowerShell.Commands.RemoveItemCommand,Mic
   rosoft.PowerShell.PackageManagement.Cmdlets.InstallPackage

**Comment by JanDeDobbeleer** [comment]
This is not related to oh-my-posh but your machine. A quick fix, according to the internet is this one:

    [Net.ServicePointManager]::SecurityProtocol = "tls12"

See [this topic](https://stackoverflow.com/questions/54165095/powershell-wont-install-almost-any-module-using-install-module) for more information.
