### ISSUE TITLE
Feature Request: Pansies style ANSI escape sequence color support

### ISSUE THREAD

**Issue by aaronsb** [JanDeDobbeleer/oh-my-posh2#296]
Pansies style color support would be very useful for expanding the look and feel of text and symbols inside themes. Having more colors is always helpful, and the implementation of pansies when generating enhanced visuals relatively efficient and fast.

Named colors, html named pictograms, and others make it a great use fit for enhancing themes.

https://github.com/PoshCode/Pansies

![C9v9em6W0AEyuYH](https://user-images.githubusercontent.com/2738471/91586824-c870c580-e90a-11ea-8e16-4de2b0cda29a.jpg)

**Comment by JanDeDobbeleer** [comment]
Good news, I implemented ANSI colors using hex codes in the new engine which should hopefully be available soon (I do hope within this and a few weeks)

**Comment by aaronsb** [comment]
@JanDeDobbeleer Fantastic! I can't wait to try that out. :1st_place_medal:

**Comment by JanDeDobbeleer** [comment]
Hey @aaronsb. I just published my [new engine](https://www.powershellgallery.com/packages/go-my-posh). That one has support for hex color codes (actually the only way to define the colors)

You can install and use it as follows

```powershell
Install-Module -Name go-my-posh -Repository PSGallery
Import-Module go-my-posh
Set-PoshPrompt paradox
```

if you want, you can also list all available themes (or create your own by copy-pasting one and using that on `Set-PoshPrompt`)

```powershell
Get-PoshThemes
```

Feel free to create an issue there as well to follow up in case you find problems.
I will keep an eye on `oh-my-posh`, but I'll favor `go-my-posh` going forward.

**Comment by aaronsb** [comment]
Very exciting! I'll be trying this today. :)
