### ISSUE TITLE
Not picking up git information correctly

### ISSUE THREAD

**Issue by kevswims** [JanDeDobbeleer/oh-my-posh2#297]
I just installed oh-my-posh and it is not picking up the correct information from posh-git. As seen in the below screenshot posh-git works just fine in this repository but when I enable oh-my-posh the git info is blank.

# posh-git only
![image](https://user-images.githubusercontent.com/13476377/91669543-e852e580-ead2-11ea-9fb2-04f91d6bda75.png)
# oh-my-posh with posh-git
![image](https://user-images.githubusercontent.com/13476377/91669550-edb03000-ead2-11ea-818c-8c1f8a4890b0.png)

I am using the following versions:
- oh-my-posh version 2.0.468
- posh-git version 1.0.0-beta-4
- PSReadLine version 2.1.0
- Powershell Core version 7.0.3

This is my full PS profile: 

```
Import-Module posh-git
Import-Module PSReadLine
Import-Module oh-my-posh
Set-Theme Paradox

Set-PSReadlineKeyHandler -Key Tab -Function Complete
New-Alias -Name vi -Value 'C:\Program Files (x86)\vim\vim80\vim.exe'
New-Alias -Name vim -Value 'C:\Program Files (x86)\vim\vim80\vim.exe'

function get-gitstatus { git status }
function get-gitdiff { git diff }
function vim-profile { vim $PROFILE }
function notes { vim $HOME/notes.txt }
New-Alias -Name Edit-Profile -value vim-profile
New-Alias -Name which -value Get-Command
New-Alias -Name gs -value get-gitstatus
New-Alias -Name gd -value get-gitdiff

# Chocolatey profile
$ChocolateyProfile = "$env:ChocolateyInstall\helpers\chocolateyProfile.psm1"
if (Test-Path($ChocolateyProfile)) {
  Import-Module "$ChocolateyProfile"
}
```

Is there a good way for me to provide more debugging info for this issue?

**Comment by JanDeDobbeleer** [comment]
Hey @kevswims. I just published my [new engine](https://www.powershellgallery.com/packages/go-my-posh). That one works independently of posh-git.

You can install and use it as follows

```powershell
Install-Module -Name go-my-posh -Repository PSGallery
Import-Module go-my-posh
Set-PoshPrompt paradox
```

if you want, you can also list all available themes

```powershell
Get-PoshThemes
```

Feel free to create an issue there as well to follow up in case you find problems with the `git` indication or anything else.
Know that when it comes to `git`, some features aren't yet fully up-to-par with `oh-my-posh` but they will shortly follow.
I will keep an eye on `oh-my-posh`, but I'll favor `go-my-posh` going forward.
