### ISSUE TITLE
Python's venv symbol doesn't render even with Powerline-patched fonts

### ISSUE THREAD

**Issue by signed-log** [JanDeDobbeleer/oh-my-posh2#299]
I'm using the Agnoster theme, on Conemu Preview 200716 x64, with Meslo S DZ for Powerline
The Venv symbol keeps render as an empty square although the github branch symobl is rendered correctly
https://i.imgur.com/ZwIt9ro.png

**Comment by signed-log** [comment]
Nevermind, found the workaround

**Comment by tusharsadhwani** [comment]
@Stig124 what is the workaround?

**Comment by deefrawley** [comment]
I have the exact same issue with the Paradox theme - it would be good if you added the workaround to the closing comment.

**Comment by tusharsadhwani** [comment]
@deefrawley i got fira code (non-mono) windows compatible OTFs from nerd-fonts, and it worked fine
