### ISSUE TITLE
Is there a way to configure any of the available themes or PowerShell, in general, to display the node.js version?

### ISSUE THREAD

**Issue by haosmos** [JanDeDobbeleer/oh-my-posh2#304]
Thank you for the wonderful PowerShell theming engine!

I use nvm as the node version manager for node.js and I want to see on the command line which version of node is currently in use without having to enter the command in the terminal:

`node -v
`

It would be great if it is possible)

If possible, please tell me how to configure (in theme or PowerShell settings) the output of node.js on the right side of the command line? 

Something like that:  

![node version in promt](https://user-images.githubusercontent.com/30666874/93240187-7fcf5e00-f78c-11ea-995c-90faf69cd197.png)

**Comment by JanDeDobbeleer** [comment]
Hey @haosmos . I just published my [new engine](https://www.powershellgallery.com/packages/go-my-posh). And at the time of writing I'm adding support for `nvm`. That way you can create the prompt you're seeing here easily through config without having to resort to writing code.

You can install and use it as follows

```powershell
Install-Module -Name go-my-posh -Repository PSGallery
Import-Module go-my-posh
Set-PoshPrompt paradox
```

if you want, you can also list all available themes

```powershell
Get-PoshThemes
```

I will try to add support for `nvm` later today or this week, feel free to create an issue there as well to follow up.
Going forward, I will keep an eye on `oh-my-posh`, but I'll favor `go-my-posh` going forward.
