### ISSUE TITLE
Modifying prompt to indicate WSL

### ISSUE THREAD

**Issue by tig** [JanDeDobbeleer/oh-my-posh2#309]
I use PowerShell both in Windows and WSL. My host name and user is the same in both.

Can I change the prompt on Linux to show that I'm in WSL?

**Comment by JanDeDobbeleer** [comment]
There's a environment variable you can look for: `WSL_DISTRO_NAME`. If that one's set, you know you're inside of the WSL. I'll add that context for sure to [go-my-posh](https://github.com/JanDeDobbeleer/go-my-posh).

**Comment by tig** [comment]
> There's a environment variable you can look for: `WSL_DISTRO_NAME`. If that one's set, you know you're inside of the WSL. I'll add that context for sure to [go-my-posh](https://github.com/JanDeDobbeleer/go-my-posh).

Awesome. And now I know about go-my-posh. What rock have I been under?

**Comment by tig** [comment]
Does go-my-posh completely replace oh-my-posh? 

Does oh-my-posh now USE go-my-posh?

**Comment by JanDeDobbeleer** [comment]
> Does go-my-posh completely replace oh-my-posh?

Not yet, but I intend to do that once we're somewhere on feature parity (only the git segment needs a few additions) That means that it will indeed use go-my-posh underneath as the go-my-posh [powershell package](https://www.powershellgallery.com/packages/go-my-posh) already does that.

**Comment by JanDeDobbeleer** [comment]
> What rock have I been under?

To be fair, I'm only open about this for a month or so :-)

**Comment by tig** [comment]
What happens if both oh-my-posh and go-my-posh are installed?

**Comment by JanDeDobbeleer** [comment]
> What happens if both oh-my-posh and go-my-posh are installed?

You can choose which one to use. They do not conflict with each other in terms of commands.

**Comment by JanDeDobbeleer** [comment]
@tig I finally decided what direction I will go with Go my Posh, it's going to be Oh my Posh V3 from now on. I added your request [here](https://github.com/JanDeDobbeleer/oh-my-posh3/issues/28). Should be fairly straightforward. If you want to give things a go, the [docs](https://ohmyposh.dev/) are live as well.
