### ISSUE TITLE
VSCode Powershell Integrated Console issue

### ISSUE THREAD

**Issue by floh96** [JanDeDobbeleer/oh-my-posh2#312]
See screenshoots the path is displayed wrong in the Powershell Integrated Console in VSCode.
Edit: In the same powershell session sometimes it's working sometimes it's broken...
It's working in pwsh.
![1](https://user-images.githubusercontent.com/49693964/95026099-2ec9d000-068f-11eb-8dca-d60007b9b41d.PNG)
![2](https://user-images.githubusercontent.com/49693964/95026101-325d5700-068f-11eb-9e0b-55ba2752f4c1.PNG)

```
ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     0.0                   chocolateyProfile                   {TabExpansion, Update-SessionEnvironment, refreshenv}        
Manifest   7.0.0.0               Microsoft.PowerShell.Management     {Add-Content, Clear-Content, Clear-Item, Clear-ItemProperty…}
Manifest   7.0.0.0               Microsoft.PowerShell.Utility        {Add-Member, Add-Type, Clear-Variable, Compare-Object…}
Script     2.0.487               oh-my-posh                          {Get-BatteryInfo, Get-ComputerName, Get-FormattedRootLocation, Get-FullPath…}
Script     1.0.0      beta4      posh-git                            {Add-PoshGitToProfile, Expand-GitCommand, Format-GitBranchName, Get-GitBranchStatusColor…}
Script     2.0.2                 PSReadLine                          {Get-PSReadLineKeyHandler, Get-PSReadLineOption, Remove-PSReadLineKeyHandler, Set-PSReadLineKeyHand… 
```

```
$PSVersionTable.PSVersion

Major  Minor  Patch  PreReleaseLabel BuildLabel
-----  -----  -----  --------------- ----------
7      0      3
```

VSCode Version: 1.49.3
Powershell Extension Version: v2020.6.0

**Comment by JanDeDobbeleer** [comment]
Can you do me a favor and check if version 3 also has this issue? Be aware A LOT has changed under the hood, but most themes should be there already: `Install-Module oh-my-posh -Scope CurrentUser -AllowPrerelease`

See the [documentation](https://ohmyposh.dev) for more information.

**Comment by floh96** [comment]
@JanDeDobbeleer it's working in version 3 👍
