### ISSUE TITLE
Escape sequences in terminal

### ISSUE THREAD

**Issue by kwmlodozeniec** [JanDeDobbeleer/oh-my-posh2#314]
I get weird escape sequences in my terminal on Windows 10 (I am using alacritty but the issue is present in powershell terminal itself too).
![Capture](https://user-images.githubusercontent.com/1453791/95441340-f0b00300-0951-11eb-9f75-5ec54ad68333.PNG)
Here is my powershell profile:
```
$PSDefaultParameterValues["Out-File:Encoding"] = "utf8"
$MaximumHistoryCount = 1000;

Import-Module posh-git
Import-Module oh-my-posh
# Set-Theme Powerlevel10k-Lean
Set-Theme Paradox
Set-Location C:\repos
```

I am assuming there is an issue with the escape sequences as the time chunk is not pushed to the right of the terminal.
Any ideas?

**Comment by JanDeDobbeleer** [comment]
Yup, I'd look at using [V3](https://ohmyposh.dev) which is rewritten from scratch and works in that regard :-)
