### ISSUE TITLE
Not working in Powershell Core

### ISSUE THREAD

**Issue by orney21d** [JanDeDobbeleer/oh-my-posh2#315]
After following the steps to install it in powershell Core, it doesn't work:

1. Install-Module posh-git -Scope CurrentUser
2.Install-Module oh-my-posh -Scope CurrentUser
3.Install-Module -Name PSReadLine -AllowPrerelease -Scope CurrentUser -Force -SkipPublisherCheck 

![image](https://user-images.githubusercontent.com/2101874/95934446-be2a5e00-0dc8-11eb-8793-bc39dae5f8bc.png)

Then, after download my font I set the them and imported the 2 modules in the default profile :

```
Import-Module posh-git
Import-Module oh-my-posh
Set-Theme Paradox
```

Then when I opened a tab with Powershell Core in windows Terminal I got even an error for the sentence `Set-Theme Paradox` as shown below:

![image](https://user-images.githubusercontent.com/2101874/95934633-3db82d00-0dc9-11eb-8aa7-b255f39dd786.png)

PS: By the way, in WIndows Powershell it works perfectly:

![image](https://user-images.githubusercontent.com/2101874/95934740-840d8c00-0dc9-11eb-9197-7e7285ce0fa6.png)

**Comment by JanDeDobbeleer** [comment]
The default profile for core and "regular" Powershell isn't the same. You can check where you need the add the module import when you check what's in `$PROFILE`

**Comment by orney21d** [comment]
Hi, thanks for your response, I know what you say, I imported the modules in a different profile for each of them , as you can see for "Windows Powershell" the default profile is in :  
`C:\Users\XXX\Documents\**WindowsPowerShell** `

and for PowershelCore is in : 

`C:\Users\XXX\Documents\**PowerShell**`

**Comment by JanDeDobbeleer** [comment]
Did you install the modules in both shells as well?
