### ISSUE TITLE
How can i use some plugins like zsh-autosuggestions

### ISSUE THREAD

**Issue by Utopia-Zzzz** [JanDeDobbeleer/oh-my-posh2#316]
I want to use suggestions like zsh-autosuggestions.
what should i do ?

**Comment by JanDeDobbeleer** [comment]
Depending on the tool there's probably another package that implements the completions. Initially I also packaged this (but that's a REALLY long time ago) and decided together with the community to no longer do that. You can install additional packages or create your own [auto completions](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/register-argumentcompleter?view=powershell-7).

**Comment by Utopia-Zzzz** [comment]
thanks
