### ISSUE TITLE
go-my-posh themes have forced solarized-dark color

### ISSUE THREAD

**Issue by enpinzolas** [JanDeDobbeleer/oh-my-posh2#317]
There seems to be a problem with the go-my-posh themes, they assume that the background color is solarized dark.
![imagen](https://user-images.githubusercontent.com/8517355/95967028-146cc080-0e0c-11eb-8173-2daf69b7e70b.png)

This does not happen with the oh-my-posh themes:
![imagen](https://user-images.githubusercontent.com/8517355/95967288-5f86d380-0e0c-11eb-8d2a-7321fac5ec7f.png)

**Comment by JanDeDobbeleer** [comment]
@enpinzolas is that the latest `oh-my-posh` beta or still `go-my-posh`? Because I adjusted that a while back to be transparent.

**Comment by enpinzolas** [comment]
It's `go-my-posh`, I installed it with the commands you suggest in #251, specifically:
```
Install-Module -Name go-my-posh -Repository PSGallery
Import-Module go-my-posh
Set-PoshPrompt paradox
```

I installed it 2 days ago, it might be that the install module has an outdated version.

**Comment by JanDeDobbeleer** [comment]
Yes, in the meantime a lot has changed. Go my Posh got changed to Oh my Posh V3, a guide is available here: https://ohmyposh.dev/docs/upgrading
