### ISSUE TITLE
Character display error

### ISSUE THREAD

**Issue by sanfusu** [JanDeDobbeleer/oh-my-posh2#318]
https://github.com/JanDeDobbeleer/oh-my-posh/blob/a031c7f9ff3c5d8129cf0fa3f70fd6d5cf076853/Themes/Material.psm1#L63

The HomeSymbol displayed error in my system:
![image](https://user-images.githubusercontent.com/34563541/95975951-6c75e800-0e49-11eb-9c6e-29ce520f732f.png)
Using `[char]::ConvertFromUtf32(0x1F3E0)` instead of 🏠 will be ok

**Comment by JanDeDobbeleer** [comment]
@sanfusu good point, I have a task for the V3 beta to move everything from those symbols to the char representation.

**Comment by JanDeDobbeleer** [comment]
See https://github.com/JanDeDobbeleer/oh-my-posh3/pull/74
