### ISSUE TITLE
How can I fix this kind of □ display error？

### ISSUE THREAD

**Issue by P4VEMENT** [JanDeDobbeleer/oh-my-posh2#319]
For all kinds of themes like Operator, Paradox and etc. I got this kind of □ display error. 
PowerShell version is 5.1
The fontface I'm using is the latest version of Cascadia Code PL (2009.022)

![image](https://user-images.githubusercontent.com/43414705/96156078-416fbf00-0f43-11eb-8606-3b42d44afb59.png)

**Comment by JanDeDobbeleer** [comment]
The font is incorrect. You want to either use a [Nerd Font](https://www.nerdfonts.com/) which contains the icons, or create a custom theme that has the icons you want.

**Comment by P4VEMENT** [comment]
Got it！Thank you very much！
