### ISSUE TITLE
Images under Show-Colors & Show-ThemeColors has wrong colors

### ISSUE THREAD

**Issue by dhanushkac** [JanDeDobbeleer/oh-my-posh2#320]
Check magenta & white

**Comment by JanDeDobbeleer** [comment]
Hey @dhanushkac, please have a look at V3, this has been addressed there. https://ohmyposh.dev

**Comment by dhanushkac** [comment]
> Hey @dhanushkac, please have a look at V3, this has been addressed there. https://ohmyposh.dev

Thank you 🙂 This looks great. Now, this has lots of features as it seems. Unfortunately, I feel this one is slower than the old one with command executions. Have to check more. Will check later 👍

**Comment by JanDeDobbeleer** [comment]
Command isn't what you want to use if you need to communicate with the shell. Check Environment Variables and Set-PoshContext. Command will be removed (or don't use it with PowerShell as it's too slow).

**Comment by dhanushkac** [comment]
Okay. thank you. Old version works fine for me. Love using it. 👍
