### ISSUE TITLE
problem with themes in powershelll

### ISSUE THREAD

**Issue by Caeliiaa** [JanDeDobbeleer/oh-my-posh2#322]
Hello,

I have installed and followed all the steps indicated during the installation guide, but then when I run the different themes they do not look as they should, this is how the theme is shown for example: agnoster

https://prnt.sc/v85twe

I have tried with other themes, but they all display incorrectly, any idea why?

**Comment by nwykes** [comment]
It looks like you haven't set up a powerline font properly per the prerequisites in the readme.  If you're just getting started, you'll probably want to use V3 however: https://ohmyposh.dev

**Comment by arthurfrancioni** [comment]
> Olá,
> 
> Instalei e segui todos os passos indicados durante o guia de instalação, mas depois quando executo os diferentes temas eles não ficam como deveriam, é assim que o tema é mostrado, por exemplo: agnoster
> 
> https://prnt.sc/v85twe
> 
> Já tentei com outros temas, mas todos exibem incorretamente, alguma ideia do porquê?

same problem here

**Comment by JanDeDobbeleer** [comment]
@arthurfrancioni make sure to set a Powerline font. Nerd Fonts has a good collection and Cascadia Code PL work up to a certain level.
