### ISSUE TITLE
Test-Administrator Windows

### ISSUE THREAD

**Issue by hesstobi** [JanDeDobbeleer/oh-my-posh2#323]
Currently the Test-Administrator function always returns false for windows. 

A possible solution is (taken from https://hochwald.net/powershell-check-if-powershell-run-elevated-e-g-as-admin-or-not/):

```
([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole] 'Administrator')
```

**Comment by JanDeDobbeleer** [comment]
Hey @hesstobi that functionality is fully reworked (and working) in V3. https://ohmyposh.dev
