### ISSUE TITLE
Alert pop-ups with bell sound on Mac OS PowerShell Core

### ISSUE THREAD

**Issue by KaiWalter** [JanDeDobbeleer/oh-my-posh2#324]
I use oh-my-posh for quite some time on Win10 and wanted to have the same experience on MacOS.

After installing and selecting e.g `Agnoster` theme, on each new prompt an alert with a bell sound appears.

It seems to be caused by this section:

https://github.com/JanDeDobbeleer/oh-my-posh/blob/f584c18dc98054e4a99f97d4e921f89ccf1ff2cd/oh-my-posh.psm1#L37

What is the background of this? Can it be omitted?

**Comment by KaiWalter** [comment]
I took out

            if ($location.Provider.Name -eq "FileSystem") {
                $prompt += "$([char]27)]9;9;`"$($location.Path)`"$([char]7)"
            }

and had no negative impact so far.

**Comment by JanDeDobbeleer** [comment]
I you want to fix this, have a look at [V3](https://ohmyposh.dev/), this has been addressed in there and you can even use it in zsh and bash ;-)

**Comment by KaiWalter** [comment]
Thanks @JanDeDobbeleer - right, with V3 the effect is gone.
