### ISSUE TITLE
Emojis cannot show properly unless certain theme was once set/previewed in powersell

### ISSUE THREAD

**Issue by 755452800** [JanDeDobbeleer/oh-my-posh2#325]
Hi,

I ran into a problem when setting up my theme.
At first, I set my theme to "Powerlevel10k-Classic", it looks like the emojis (the traffic light like icon and the white x in a green box) **were not shown** (have already set font to Jetbrains Mono NF). But then I previewed the "Emodipt" theme and changed it back to "Powerlevel10k-Classic", the emojis were shown properly. Please see attached pic.
![20201116135051](https://user-images.githubusercontent.com/18474386/99217892-11eaf580-2814-11eb-8085-9c73dbcc2284.png)

My environment is as follow:
Windows 10 Pro version 1909 (OS Build 18363.1198)
Windows Terminal Version: 1.4.3141.0
Powershell version 5.1.18362.1171
Oh my posh version 2.0.487

Thanks for helping!

**Comment by JanDeDobbeleer** [comment]
Hey @755452800, that's because it loads those icons at the end, probably wrong. The good news is, this theme is available in V3, I would advice to have a look at [upgrading](https://ohmyposh.dev/docs/upgrading).

**Comment by 755452800** [comment]
Got it! Thanks for helping!
