### ISSUE TITLE
Python VENV isn't disabled

### ISSUE THREAD

**Issue by MythreyaK** [JanDeDobbeleer/oh-my-posh2#326]
Python's `virtualenv` prompt can be disable by using an env variable. I think I can add a pull-request by adding a line to set `$env:VIRTUAL_ENV_DISABLE_PROMPT="True"`.

Given there's the v3 going, wasn't sure if I should open a pull-request, but says repo would accept bug-fixes, so thought I'd open an issue before proceeding. 

Do let me know if I should go ahead, and where to add the line.

**Comment by MythreyaK** [comment]
I just noticed it doesn't happen with `venv` included in `python3`, but happens with `virtualenv` package.

**Comment by JanDeDobbeleer** [comment]
You can open a PR, let's see if this also happens on V3 and maybe extend that as well to keep everything in line.
