### ISSUE TITLE
Weird line appered when i start my terminal 

### ISSUE THREAD

**Issue by giansluca** [JanDeDobbeleer/oh-my-posh2#331]
Hi, I'm getting new messy string when i launch my terminal (Windows terminal).
I haven't seen it before, It suddenly appeared, and now is there every time i open the terminal.
If i press enter i got back my normal propmt, as shown in the picture attached.

Theme is robbyrussel.
If i disable "Set-Theme" in my profile, the string disapperas.

 
<img width="613" alt="Screenshot 2020-12-06 at 09 59 53" src="https://user-images.githubusercontent.com/11060553/101276057-96dd8500-37aa-11eb-8fda-9cf0afcae7a8.png">

**Comment by tushev** [comment]
Same here. In my case it looks like:
![image](https://user-images.githubusercontent.com/18406797/101276503-1e3cef80-37cf-11eb-8f87-871cbb12635e.png)

I'm running PowerShell 7.1.0. I also have Cygwin installed (in case it matters, cause some utilities like git may (or may not) be called from Cygwin).
I tried deleting everything in `%USERPROFILE%\Documents\PowerShell` and then
```powershell
Install-Module posh-git -Scope CurrentUser
Install-Module oh-my-posh -Scope CurrentUser
Set-Prompt
```
as suggested in README.md here. No effect.

The next line (once I press enter) looks OK.
<hr>

**UPD:** Tried updating to the latest version:
`Update-Module -Name oh-my-posh -AllowPrerelease -Scope CurrentUser` - no effect.

**Comment by giansluca** [comment]
now i realized, if i enter in a git folder i get a total mess

<img width="1243" alt="Screenshot 2020-12-06 at 10 58 27" src="https://user-images.githubusercontent.com/11060553/101277106-3c482700-37b2-11eb-81de-ef3f0c5ecc74.png">

**Comment by tushev** [comment]
I've just solved the problem for myself - I ran `C:\Windows\System32\rundll32.exe sysdm.cpl,EditEnvironmentVariables`.

Then I put `X:\*Git for Windows*` **above** `X:\*Cygwin*` in `PATH` environment variable (so Git for Windows goes first). 

Now everything seems to be working.

**Comment by JanDeDobbeleer** [comment]
All you need to do is import git's bin folder and you should have all you need. That's how I did it back in my Windows days. I would avoid using Cygwin altogether. Just use the WSL if you need a proper working unix environment.

**Comment by giansluca** [comment]
> I've just solved the problem for myself - I ran `C:\Windows\System32\rundll32.exe sysdm.cpl,EditEnvironmentVariables`.
> 
> Then I put `X:\*Git for Windows*` **above** `X:\*Cygwin*` in `PATH` environment variable (so Git for Windows goes first).
> 
> Now everything seems to be working.

yes it works :D
