### ISSUE TITLE
[System.Console]::ForegroundColor -eq [System.Console]::BackroundColor

### ISSUE THREAD

**Issue by B4Art** [JanDeDobbeleer/oh-my-posh2#332]
Sometimes  for instance using:
 ```
$a = (az pipelines show --project <projectname> --name * | ConvertFrom-Json)
``` 
Background AND Foreground become the same color.
$a does give output but is unreadable.
As a bugfix in a theme.psm1 file after the final $prompt you can add the following code
```
	If ([System.Console]::ForegroundColor -eq [System.Console]::BackroundColor){
		[System.Console]::BackgroundColor = [System.ConsoleColor]::Black
		[System.Console]::ForegroundColor = [System.ConsoleColor]::White
	}
```

**Comment by JanDeDobbeleer** [comment]
@B4Art have a look at [V3](https://ohmyposh.dev) as I'm not going to resolve this for V2 :-)
