### ISSUE TITLE
powerline display error on default powershell

### ISSUE THREAD

**Issue by Tim-0731-Hzt** [JanDeDobbeleer/oh-my-posh2#333]
Hello,
Following the guide, I successfuly set up the powerline on windows terminal like this
<img width="662" alt="Screenshot 2020-12-07 233001" src="https://user-images.githubusercontent.com/67449730/101420115-a3e2ab80-3945-11eb-8a0f-ee1aafaa008a.png">

But on default Powershell, it displays like this, some weird box
<img width="840" alt="Screenshot 2020-12-07 232902" src="https://user-images.githubusercontent.com/67449730/101420079-962d2600-3945-11eb-86dd-c1ba988e1ddb.png">

**Comment by B4Art** [comment]
> Hello,
> Following the guide, I successfuly set up the powerline on windows terminal like this
> <img alt="Screenshot 2020-12-07 233001" width="662" src="https://user-images.githubusercontent.com/67449730/101420115-a3e2ab80-3945-11eb-8a0f-ee1aafaa008a.png">
> 
> But on default Powershell, it displays like this, some weird box
> <img alt="Screenshot 2020-12-07 232902" width="840" src="https://user-images.githubusercontent.com/67449730/101420079-962d2600-3945-11eb-86dd-c1ba988e1ddb.png">

Possibly a different font selected

**Comment by Tim-0731-Hzt** [comment]
thanks, I got it
