### ISSUE TITLE
Theme acting glitchy and not showing correctly

### ISSUE THREAD

**Issue by ghost** [JanDeDobbeleer/oh-my-posh2#336]
Ello, I'm trying the Paradox theme, and this is what is happening 
![image](https://user-images.githubusercontent.com/75714323/101900353-58463100-3bd5-11eb-92cb-b5830a681d6f.png)

I don't think that this is supposed to happen? Please fix this 😄

**Comment by JanDeDobbeleer** [comment]
You need to configure your terminal to use a Powerline enabled font. Cascadia Code PL has this, but for full compatibility, any [Nerd Font](https://www.nerdfonts.com/) will do.
