### ISSUE TITLE
Unreadable Symbol in PowerShell Core of Linux

### ISSUE THREAD

**Issue by allenk** [JanDeDobbeleer/oh-my-posh2#340]
Unreadable Symbol in PowerShell Core of Linux. (my term is Xfec4 default term running on WSL2)
To fix it, I have to comment out this line in oh-my-posh.psm1
```powershell
$prompt += "$([char]27)]9;9;`"$($location.Path)`"$([char]7)"
```
I also try [kitty](https://github.com/kovidgoyal/kitty) 
It will try to hint me with escape symbol error messages for every line.

My default shell in WSL2 is ZSH and run with Oh-My-ZSH. Everything seems fine so that I think it's possible to fix it.
Sorry, I’m not familiar with the term escape character, so I can’t provide a solution.

**Comment by JanDeDobbeleer** [comment]
Hey @allenk. V3 should fix that issue for you. You can follow the [guide](https://ohmyposh.dev/docs/upgrading), just know it will not be compatible with any V2 custom theme, but creating your own is a lot faster than what V2 could offer.

**Comment by allenk** [comment]
Thanks for your quick reply. I will try v3 immediately.
