### ISSUE TITLE
Request: "user_info_separator_color" override

### ISSUE THREAD

**Issue by JTF195** [JanDeDobbeleer/oh-my-posh2#344]
Small request:

Currently, the only way to change the color of  `user_info_separator` is to set `foreground` to the desired color and then override `user_color` and `host_color` back to "normal"

Could we get a `"user_info_separator_color"` property?

**Comment by JanDeDobbeleer** [comment]
@JTF195 V3 has this by setting that separator and using color overrides. Have a look at https://ohmyposh.dev

**Comment by JTF195** [comment]
My apologies. This feature request is for V3. I didn't realize it's hosted in a separate repo.
