### ISSUE TITLE
Better Images for Conda Ens

### ISSUE THREAD

**Issue by theshubhagrwl** [JanDeDobbeleer/oh-my-posh2#345]
Hi, I use Conda and oh-my-posh. 
I have seen that in some themes I can't see the conda env name but in the other, I can. 
example:

Here I can clearly see the ENV name
![image](https://user-images.githubusercontent.com/37265683/105575970-a41ff480-5d95-11eb-837a-40a735f08d1f.png)

But here no name is visible
![image](https://user-images.githubusercontent.com/37265683/105575993-cd408500-5d95-11eb-8927-86d1cb359fc7.png)

I was thinking that it will be better if we can add these types of images to the ReadMe file. 

Please correct me if I am wrong somewhere.

**Comment by JanDeDobbeleer** [comment]
@theshubhagrwl V2 only accepts bugfixes, [V3](https://ohmyposh.dev/docs/upgrading) is out and supports basically whatever you want.
