### ISSUE TITLE
Three lines of text are displayed when using the avit theme.

### ISSUE THREAD

**Issue by Ryokai96** [JanDeDobbeleer/oh-my-posh2#346]
Why three lines are displayed?
<img width="143" alt="批注 2021-02-01 162140" src="https://user-images.githubusercontent.com/19326432/106432987-8136c400-64aa-11eb-9023-3df54832c2d7.png">
How can I not display the second line of text?

**Comment by JanDeDobbeleer** [comment]
@Ryokai96 when using a standard theme, it's advised to move to [V3](https://ohmyposh.dev/docs/upgrading).
