### ISSUE TITLE
OSC 9;9 sequence is not working.

### ISSUE THREAD

**Issue by saifali-dev** [JanDeDobbeleer/oh-my-posh2#349]
### When I use oh-my-posh and posh-git module then:
- **The sequence doesn't work at all when duplicating tabs. The duplicate tab always opens in the default location.**

- **Further, this sequence is emitted at the wrong time. --like when piping commands**
![image](https://user-images.githubusercontent.com/54573967/107365206-4c57ec00-6afe-11eb-94a5-f7119a17321f.png)

- **If I comment below portion of the code in file [oh-my-posh.psm1 --line 36 to 39](https://github.com/JanDeDobbeleer/oh-my-posh/blob/master/oh-my-posh.psm1), the sequence doesn't emit while piping.**  
![image](https://user-images.githubusercontent.com/54573967/107365995-680fc200-6aff-11eb-9e55-c13bd3d73c1e.png)

### After removing both oh-my-posh and posh-git modules:
- I added the prompt provided by this [skyline75489](https://gist.github.com/skyline75489/480d036db8ae9069b7009377e6eebb79#file-prompt-ps1) guy to my Powershell profile.
- The sequence was working fine and the duplicate tab always opens in the current working dir as expected.
- But like oh-my-posh it also emits the sequence while piping.

#### I'm using PowerShell Core and oh-my-posh 2.0.496.
![image](https://user-images.githubusercontent.com/54573967/107367409-12d4b000-6b01-11eb-9f7d-08efb85d805f.png)

**Comment by JanDeDobbeleer** [comment]
I'm going to add this in V3, follow up on that [here](https://github.com/JanDeDobbeleer/oh-my-posh3/issues/409).
