### ISSUE TITLE
Theme setting lost after restart PowerShell/ConEmu

### ISSUE THREAD

**Issue by nc-hyw** [JanDeDobbeleer/oh-my-posh2#35]
Hi,
could you please tell me how to config so that I don't have to set theme for PowerShell everytime I start ConEmu?

**Comment by nwykes** [comment]
You could add a `Set-Theme Paradox` or whatever theme to your $PROFILE

**Comment by JanDeDobbeleer** [comment]
Yup, what @nwykes said 🙂

**Comment by nc-hyw** [comment]
Thanks guys. Problem fixed.
