### ISSUE TITLE
unreadable readme

### ISSUE THREAD

**Issue by alirobe** [JanDeDobbeleer/oh-my-posh2#36]
README is in a non-standard format.

TOC links don't work. 

Goes against markdown [philosophy](http://daringfireball.net/projects/markdown/syntax#philosophy). 

Could you please remove non-standard collapsing HTML elements & use standard headers?

**Comment by JanDeDobbeleer** [comment]
Why exactly is that a problem?

**Comment by amedee** [comment]
@alirobe As I already wrote on [Twitter], why take the effort to submit an issue while you just as well could have submitted a pull request?
About the collapsing HTML: that is a real GitHub feature. Read more about it [here][collapsible-sections].

@JanJoris That being said, and before I submit my own pull request, could you please explain to me the function of the `<div id='foo'/>` tags in your MarkDown? [It's not like you need them for internal anchor targets][automatic-anchor-tags].

[Twitter]: https://twitter.com/amedee/status/850096791236337666
[collapsible-sections]: https://github.com/dear-github/dear-github/issues/166#issuecomment-236342209
[automatic-anchor-tags]: http://stackoverflow.com/a/16426829/766786

**Comment by JanDeDobbeleer** [comment]
@amedee indeed, that's why I need them. I had no idea you could do that. Can be replaced. Either way, I'm not rewriting the README as that's not what the repo is about (I giggled when I wrote that), so feel free to do it for me if it bothers you.

**Comment by alirobe** [comment]
created PR
