### ISSUE TITLE
Settings are lost

### ISSUE THREAD

**Issue by batousik** [JanDeDobbeleer/oh-my-posh2#39]
On restart the $ThesmeSettings becomes empty

**Comment by JanDeDobbeleer** [comment]
Edit your `$PROFILE` with your favorite editor, add the following in there (order is important)

    Import-Module oh-my-posh
    Set-Theme Agnoster #or whatever you want
    $ThemeSettings.PromptSymbols.VirtualEnvSymbol = "ENV" #or whetever you want to tweak

**Comment by impankratov** [comment]
@JanJoris shouldn't this be in the Readme? I've lost some time trying the current Readme instructions before searching through issues.

**Comment by JanDeDobbeleer** [comment]
Could be added, I consider this to be general PowerShell knowledge though.
