### ISSUE TITLE
No highlighting

### ISSUE THREAD

**Issue by batousik** [JanDeDobbeleer/oh-my-posh2#40]
![2017-04-14_15-15-21](https://cloud.githubusercontent.com/assets/7288954/25045666/467f0f06-2125-11e7-93fe-58b8b22b4b59.png)

**Comment by JanDeDobbeleer** [comment]
I fixed this, keep an eye out for build [2.0.109](https://ci.appveyor.com/project/JanJoris/oh-my-posh/build/2.0.109)
