### ISSUE TITLE
Nothing adds in the git folder

### ISSUE THREAD

**Issue by batousik** [JanDeDobbeleer/oh-my-posh2#41]
![2017-04-14_15-18-01](https://cloud.githubusercontent.com/assets/7288954/25045741/aae6d1c2-2125-11e7-8f94-c1805899c49b.png)

**Comment by JanDeDobbeleer** [comment]
I fixed this, keep an eye out for build [2.0.109](https://ci.appveyor.com/project/JanJoris/oh-my-posh/build/2.0.109). Related to #40
