### ISSUE TITLE
How to set theme everytime I open powershell? (Cmder)

### ISSUE THREAD

**Issue by KoinBanks** [JanDeDobbeleer/oh-my-posh2#44]
I am using Cmder as a host for powershell. I tried to update my profile.ps1 with `Set-Theme agnoster` but it does not work. 

How to do it properly?

**Comment by JanDeDobbeleer** [comment]
The last feedback I received from a cmder user was this:
> @JanJoris, as it stands currently, the Cmder scripts that set the prompt run after the user's profile scripts, so they always override whatever you do.  They did merge cmderdev/cmder#1280 (with the basic idea of cmderdev/cmder#1282 included), so the next release will allow the user's profile to override the Cmder prompt before it gets set.  I've manually applied that Cmder PR, and this now works in my profile:
```
Import-Module oh-my-posh
$ThemeSettings.MyThemesLocation = $PSScriptRoot
Set-Theme My-Posh-Theme
[ScriptBlock]$Prompt = $function:prompt
```

**Comment by JanDeDobbeleer** [comment]
@iFarmGolems any feedback? ⬆️
