### ISSUE TITLE
Themes not sticking:

### ISSUE THREAD

**Issue by SaintFenix** [JanDeDobbeleer/oh-my-posh2#46]
I installed according to the instructions on the main page and ran through downloading the appropriate modules, but when I type in: 

$ThemeSettings

or

$GitPromptSettings

it returns nothing, and returns to prompt.

I can also set a theme, but if I log out of the interface, it doesn't stick.

I'm not sure if I skipped something but it's bizarre. 

I am doing all of this in Conemu.

**Comment by avoidik** [comment]
It should be loaded in your PowerShell profile first, but this isn't mentioned anywhere here.

**Comment by JanDeDobbeleer** [comment]
You should add this to your $profile so that it's set on the start of every session. I'll add it to the readme (never did that as I assumed that's basic PS knowledge).

**Comment by SaintFenix** [comment]
Appreciate it. I'm new to Powershell, and an older hand in *nix, figured running the command would have done it, kinda like Oh-My-Fish. I'll follow the instructions you've put up.

Thanks alot. :)

**Comment by Liquidmantis** [comment]
It's like setting customizations in your .bashrc or .zshrc, which is what the $profile is.  Here's a [write-up on the different profiles available](http://mikefrobbins.com/2015/07/02/powershell-profile-the-six-options-and-their-precedence/)

**Comment by JanDeDobbeleer** [comment]
@SaintFenix if you consider this answered, do you mind closing the issue?

**Comment by SaintFenix** [comment]
No Problem, and thanks for the help. :)
