### ISSUE TITLE
Slow import times

### ISSUE THREAD

**Issue by Liquidmantis** [JanDeDobbeleer/oh-my-posh2#47]
I've been seeing this for a long time but oh-my-posh is very slow to import.  Anyone else seeing the same behavior?  It's taking 13 seconds to import in a new PS session.

Here's a snip from my profile loading log.  The other two modules I explicitly import are **much** faster.
[00.2775] Importing PSReadline
[00.2846] Importing oh-my-posh
[13.7760] Importing z
[14.8844] Setting theme parameters

**Comment by JanDeDobbeleer** [comment]
I don't have that issue (it would annoy the crap out of me). What's your setup/settings?

**Comment by Liquidmantis** [comment]
Nothing special.  This is just the initial import of OMP.  The delay is before I apply my theme settings, which is fast.  When I get some spare time I'll create a clean test user and see if I can track down the cause.

**Comment by JanDeDobbeleer** [comment]
K. I'm currently trying to get everything to work on Linux as I switched environment 🐧

**Comment by erichiller** [comment]
I've been having similar slowness - I ran powershell whilst importing with PSDebug 

This is the result I had... I hope this helps in identifying the bottleneck.

Time | Command
-- | --
104 | >>>> Import-Module PSColor   -ErrorAction Stop >$null
9 | >>>> @{
0 | ! CALL function '<ScriptBlock>'    (defined in file   'C:\Users\ehiller\AppData\Local\omega\system\psmodules\PSColor\1.0.0.0\PSColor.psd1')
2 | >>>> Add-Type   -assemblyname System.ServiceProcess
0 | ! CALL function '<ScriptBlock>'    (defined in file   'C:\Users\ehiller\AppData\Local\omega\system\psmodules\PSColor\1.0.0.0\PSColor.psm1')
4 | >>>> .   "$PSScriptRoot\PSColorHelper.ps1"
1 | >>>>   ##############################################################################
0 | ! CALL function '<ScriptBlock>'    (defined in file   'C:\Users\ehiller\AppData\Local\omega\system\psmodules\PSColor\1.0.0.0\PSColorHelper.ps1')
5 | >>>> .   "$PSScriptRoot\FileInfo.ps1"
1 | >>>>
0 | ! CALL function '<ScriptBlock>'    (defined in file   'C:\Users\ehiller\AppData\Local\omega\system\psmodules\PSColor\1.0.0.0\FileInfo.ps1')
6 | >>>> .   "$PSScriptRoot\ServiceController.ps1"
1 | >>>> # Outputs a line   of a ServiceController
0 | ! CALL function '<ScriptBlock>'    (defined in file   'C:\Users\ehiller\AppData\Local\omega\system\psmodules\PSColor\1.0.0.0\ServiceController.ps1')
7 | >>>> .   "$PSScriptRoot\MatchInfo.ps1"
1 | >>>> function   MatchInfo {
0 | ! CALL function '<ScriptBlock>'    (defined in file   'C:\Users\ehiller\AppData\Local\omega\system\psmodules\PSColor\1.0.0.0\MatchInfo.ps1')
8 | >>>> .   "$PSScriptRoot\ProcessInfo.ps1"
1 | >>>> function   Write-Color-Process
0 | ! CALL function '<ScriptBlock>'    (defined in file   'C:\Users\ehiller\AppData\Local\omega\system\psmodules\PSColor\1.0.0.0\ProcessInfo.ps1')
12 | >>>> $global:PSColor   = @{
0 | ! SET $PSColor = 'System.Collections.Hashtable'.
35 | >>>>   $script:showHeader=$true
0 | ! SET $showHeader = 'True'.
37 | >>>>   New-CommandWrapper Out-Default -Process {
55 | function New-CommandWrapper  >>>> {
0 | ! CALL function 'New-CommandWrapper'    (defined in file   'C:\Users\ehiller\AppData\Local\omega\system\psmodules\PSColor\1.0.0.0\PSColorHelper.ps1')
90 | >>>> Set-StrictMode   -Version Latest
93 | >>>> $target = $Name
0 | ! SET $target = 'Out-Default'.
94 | >>>> $commandType =   "Cmdlet"
0 | ! SET $commandType = 'Cmdlet'.
98 | if( >>>> Test-Path   function:\$Name)
98 | if( >>>> Test-Path   function:\$Name)
106 | >>>> $proxy = @'
0 | ! SET $proxy = '
0 | __CMDLET_BINDING_ATTRIBUTE__
0 | param(
0 | ...'.AMETERS__
244 | >>>> $originalCommand   = Get-Command $target
0 | ! SET $originalCommand = 'Out-Default'.
245 | >>>> $metaData =   New-Object System.Management.Automation.CommandMetaData `
0 | ! SET $metaData = 'System.Management.Automation.CommandMetadata'.
247 | >>>>   $proxyCommandType = [System.Management.Automation.ProxyCommand]
0 | ! SET $proxyCommandType = 'System.Management.Automation.ProxyCommand'.
251 | >>>> $proxy =   $proxy.Replace("__CMDLET_BINDING_ATTRIBUTE__",
0 | ! SET $proxy = '
0 | [CmdletBinding(HelpUri='http://go.microsoft.com/fwlin...'.
253 | >>>> $proxy =   $proxy.Replace("__COMMAND_NAME__", $target)
0 | ! SET $proxy = '
0 | [CmdletBinding(HelpUri='http://go.microsoft.com/fwlin...'.
254 | >>>> $proxy =   $proxy.Replace("__COMMAND_TYPE__", $commandType)
0 | ! SET $proxy = '
0 | [CmdletBinding(HelpUri='http://go.microsoft.com/fwlin...'.
257 | >>>>   $newParamBlockCode = ""
0 | ! SET $newParamBlockCode = ''.
261 | >>>> $beginAdditions   = ""
0 | ! SET $beginAdditions = ''.
264 | >>>>   $currentParameter = $originalCommand.Parameters.Count
0 | ! SET $currentParameter = '13'.
265 | if( >>>>   $AddParameter)
326 | >>>> $parameters =   $proxyCommandType::GetParamBlock($metaData)
0 | ! SET $parameters = '
0 | [switch]
0 | ${Transcript},
0 | 0
0 | [Paramet...'.
327 | if( >>>>   $newParamBlockCode) { $parameters
328 | >>>> $proxy =   $proxy.Replace('__PARAMETERS__', $parameters)
0 | ! SET $proxy = '
0 | [CmdletBinding(HelpUri='http://go.microsoft.com/fwlin...'.
331 | >>>> $proxy =   $proxy.Replace('__CUSTOM_BEGIN__', $Begin)
0 | ! SET $proxy = '
0 | [CmdletBinding(HelpUri='http://go.microsoft.com/fwlin...'.
332 | >>>> $proxy =   $proxy.Replace('__CUSTOM_PARAMETER_PROCESSING__', $beginAdditions)
0 | ! SET $proxy = '
0 | [CmdletBinding(HelpUri='http://go.microsoft.com/fwlin...'.
333 | >>>> $proxy =   $proxy.Replace('__CUSTOM_PROCESS__', $Process)
0 | ! SET $proxy = '
0 | [CmdletBinding(HelpUri='http://go.microsoft.com/fwlin...'.
334 | >>>> $proxy =   $proxy.Replace('__CUSTOM_END__', $End)
0 | ! SET $proxy = '
0 | [CmdletBinding(HelpUri='http://go.microsoft.com/fwlin...'.
337 | >>>> Write-Verbose   $proxy
338 | >>>> Set-Content   function:\GLOBAL:$NAME $proxy
342 | if( >>>> $commandType   -eq "Cmdlet")
344 | >>>>   $originalCommand.Visibility = "Private"
346 | >>>> }
61 | >>>>   Export-ModuleMember

**Comment by JanDeDobbeleer** [comment]
Seems to be PSColor which is no longer a dependency, I now get import times which are a lot faster on my latest branch. Let's see if that fixes everything.

**Comment by JanDeDobbeleer** [comment]
Can you validate if [2.0.162](https://www.powershellgallery.com/packages/oh-my-posh/2.0.162) resolves the issue?

**Comment by JanDeDobbeleer** [comment]
Closing due to no feedback

**Comment by erichiller** [comment]
Sorry for the delay, its been hectic to be sure. Just to be clear, while PSColor is no longer a dependency, it is still required if we want colorization of `ls` output aka `Get-ChildItem` correct? I didn't see any replacement code.

**Comment by JanDeDobbeleer** [comment]
Yes. That's correct. I have my own fork, not sure if I should keep the defaults in there. Although it doesn't break if you don't have it.
