### ISSUE TITLE
Throwing Error Message "Module oh-my-posh was not found in central repository" when execuse "Install-Module oh-my-posh"

### ISSUE THREAD

**Issue by wsd9408** [JanDeDobbeleer/oh-my-posh2#49]
Throwing Error Message "Module oh-my-posh was not found in central repository" when execuse "Install-Module oh-my-posh"

**Comment by ok-dok** [comment]
I got this error message too, and how to resolve it?

**Comment by wsd9408** [comment]
"You need to use the the PowerShell Gallery to install oh-my-posh." 
https://www.powershellgallery.com/packages/oh-my-posh/2.0.114
