### ISSUE TITLE
Remove demand for ConEmu

### ISSUE THREAD

**Issue by giggio** [JanDeDobbeleer/oh-my-posh2#51]
The current Windows 10 console is able to display powerline fonts. I just grabbed the [DejaVu Sans Mono for Powerline font](https://github.com/powerline/fonts/blob/master/DejaVuSansMono/DejaVu%20Sans%20Mono%20for%20Powerline.ttf), installed, changed it on the console properties and it worked just fine.

![image](https://user-images.githubusercontent.com/334958/31047723-35c49f1e-a5e6-11e7-973a-e8d9d48d4d7b.png)

Not every font works, even in the nerd-fonts repo. Some glyphs are not available, and some fonts don't show up on the console options menu. Actually, the only font I got to show the glyph correctly and powerline and show on options was DejaVu, but this is probably just a matter of patching the fonts correctly. The Meslo font you have on your readme does not show on console options after instalation, I guess because it is marked as a PostScript Outlines font:

![image](https://user-images.githubusercontent.com/334958/31047751-a8d7f816-a5e6-11e7-95d2-e7c51932c016.png)

Whereas dejavu shows as true type outlines:

![image](https://user-images.githubusercontent.com/334958/31047755-b49cbda8-a5e6-11e7-8c6e-a0b8c1633962.png)

But I am not sure if this is it.

I had to add the `ConEmuANSI` env var to fool oh-my-posh to believe it was in Conemu. Everything is working just fine. You could just add the instructions on how to do it, or maybe demand another env var to make sure that this is what the user wants.

Here is the end result with poweshell directly and Conemu:

![image](https://user-images.githubusercontent.com/334958/31047904-76632d94-a5e9-11e7-8d4b-899f0e33ac3e.png)

The only strange thing so far is the yellow color which is showing up white. I will try to understand what is going on and post here later.

**Comment by JanDeDobbeleer** [comment]
It would be handy if the console would have a simple env var that indicates ANSI support. That way I can easily allow the updated clients instead of opening the door to potential issues.

**Comment by Pome-ro** [comment]
This would be nice, but adding `$env:ConEmuANSI = $True` to the top of your profile is a good workaround for now.

**Comment by Librazy** [comment]
For users using Chinese or Japanese, I suggest using be5invis's [Sarasa Gothic (更纱黑体 / 更紗黑體 / 更紗ゴシック)](https://github.com/be5invis/Sarasa-Gothic) as Powerline font for PowerShell. It works like a charm for me. And you can adjust colors in last tab "Color/颜色"  in PowerShell's properties window. Change the 16 colors and select 4 defaults to find a working color profile for you. Use ```Show-ThemeColors``` and ```Show-Colors``` to check your current PowerShell color profile.

![PowerShell 属性的颜色标签页](https://user-images.githubusercontent.com/2211542/34918558-fc58b7b0-f94b-11e7-9f8b-4dc565cdd2a8.png)
