### ISSUE TITLE
Upgrade $lastCommandFailed to use exit codes as well

### ISSUE THREAD

**Issue by giggio** [JanDeDobbeleer/oh-my-posh2#52]
Right now you are using `$global:error.Count` to verify if there was an error and populate the value for `$lastCommandFailed`, but that only checks for errors on powershell things, it does not check for errors on exit codes:

https://github.com/JanJoris/oh-my-posh/blob/c0e88625a338d4a3c1fa47c73491c7809d1e1edb/oh-my-posh.psm1#L33

I suggest you use `$?` instead, which checks for both.

**Comment by JanDeDobbeleer** [comment]
That's what I used before but it didn't provide the right behaviour in every context (not sure why anymore, had to document that).

See: https://github.com/JanJoris/oh-my-posh/commit/6037b9ba11f832b25a9afc2e0f77345f05825bde

**Comment by JanDeDobbeleer** [comment]
I tried to see if I could reliably switch to either using `$?` or a combination of the current method and that one, but it fails to be correct. If you've got any suggestions I'll gladly try them, or, even better, I do accept PR's 🚀

**Comment by pavelbraginskiy** [comment]
@JanDeDobbeleer What exactly didn't work with `$?`? I'd been using it in a custom prompt for a while before disovering oh-my-posh without issues.

**Comment by JanDeDobbeleer** [comment]
Depending on the cool you used, it doesn't always indicate failure of the previous command.

**Comment by pavelbraginskiy** [comment]
You can use `$LastExitCode` to check if a non-PS command failed, provdided that the very first command in the prompt function is `$err = $LastExitCode -ne 0` or something like that so it doesn't get lost. Checking for either a powershell error or `$LastExitCode -ne 0` should cover all cases.

**Comment by chenxiaolong** [comment]
Are the issues with `$?` still present?

In my local copy of oh-my-posh, I changed https://github.com/JanDeDobbeleer/oh-my-posh/blob/a8330cc97b51d8480115dcd6360f77cb2b2bbea0/oh-my-posh.psm1#L15 to `$lastCommandFailed = -not $?` and it seems to handle both powershell (`$error`) and exe (`$LASTEXITCODE`) failures properly.

I've tested with Windows Powershell `5.1.18362.145` and pwsh `6.2.3`. I don't have many other modules installed, just oh-my-posh, posh-git, PSFzf, PSReadline, and Chocolatey.

---

EDIT: In the meantime, I've added this to my profile so I don't have to directly modify oh-my-posh in the modules directory:
```powershell
Copy-Item Function:prompt Function:promptorig
Remove-Item Function:prompt
function prompt {
    if (-not $? -and $error.Count -eq $ThemeSettings.ErrorCount) {
        try { throw } catch {}
    }

    # Also preserve $LASTEXITCODE
    $exitCodeOrig = $global:LASTEXITCODE
    promptorig
    $global:LASTEXITCODE = $exitCodeOrig
}
```
