### ISSUE TITLE
Installation issues?

### ISSUE THREAD

**Issue by iagomez** [JanDeDobbeleer/oh-my-posh2#53]
Hello @JanJoris 

First of all thank you for this! This is awesome :)

I'm having issues getting this to work and was hoping you could give me a hand. I'm very much used to working with oh-my-zh and would love to have this on Windows.

I'm using ConEmu and I've run the installation instructions:
```
Install-Module posh-git -Scope CurrentUser
Install-Module oh-my-posh -Scope CurrentUser
```
However, I'm not seeing any changes when I open powershell directly or ConEmu. `$ThemeSettings` doesn't return any output

![image](https://user-images.githubusercontent.com/2080150/31239555-7a798974-a9cb-11e7-8cf5-c632653e8015.png)

Any suggestions?

Thanks!

**Comment by iagomez** [comment]
Duh. I had to import it. I'm very much a Unix user if it wasn't obvious. Sorry for the false alarm.

Thanks!

**Comment by JanDeDobbeleer** [comment]
No worries:-)

**Comment by doggy8088** [comment]
@JanJoris I have the same issue.  How can I import it automatically?  Can you add this info to the README file? Thanks. ( `Import-Module oh-my-posh` )

**Comment by Liquidmantis** [comment]
@doggy8088 Here is information on the various [Powershell profiles](https://technet.microsoft.com/en-us/library/bb613488%28v=vs.85%29.aspx?f=255&MSPPError=-2147217396).  

You can also quickly fix it with:
```Powershell
"Import-Module oh-my-posh" | add-content $profile
. $profile
```
