### ISSUE TITLE
Add Default_User option

### ISSUE THREAD

**Issue by hugo-vrijswijk** [JanDeDobbeleer/oh-my-posh2#55]
Oh-my-zsh has the option to set a DEFAULT_USER flag. This option then hides `user@hostname` when logged in with that user. 

`# optionally set DEFAULT_USER in ~/.zshrc to your regular username to hide the “user@hostname” info when you’re logged in as yourself on your local machine.`
`DEFAULT_USER=user@hostname`

My proposal is to have something similar in oh-my-posh to hide the username. Right now, I've edited the theme I'm using to remove the text, but this means that other users would also not show

![image](https://user-images.githubusercontent.com/10114577/31776045-a670fb78-b4ea-11e7-82d5-ed957e0b56e1.png)

**Comment by hugo-vrijswijk** [comment]
I've created a pull request #56 where this is implemented. Bonus: this works on all themes where applicable, not just Agnoster like in oh-my-zsh!

**Comment by JanDeDobbeleer** [comment]
Nice!!
