### ISSUE TITLE
Most Themes not working

### ISSUE THREAD

**Issue by ielcoro** [JanDeDobbeleer/oh-my-posh2#59]
I have followed the configuration steps for oh-my-posh as stated here, however most of the themes are not working:

In Agnoster, Paradox and others I only see a error symbol and the text PS, no current directory info, no git info, and no beatiful colors:

![agnoster](https://user-images.githubusercontent.com/587365/32312817-0a448f60-bfa0-11e7-9c74-4b0cfaa171c5.png)

![paradox](https://user-images.githubusercontent.com/587365/32312836-1f6e8e72-bfa0-11e7-9951-1acf53330a95.png)

However Darkblood, Avit and others are working:

![darkblood](https://user-images.githubusercontent.com/587365/32312856-37364400-bfa0-11e7-9528-228df7591f57.png)

![Avit](https://user-images.githubusercontent.com/587365/32312879-4e164828-bfa0-11e7-915a-44d672d7a1d0.png)

I don't know if it has nothing to do with it, but the themes not working are only those with background colors on path.

**Comment by KochiyaOcean** [comment]
Seems this bug occurs on Windows 10 1709 (Fall Creators Update)
Windows 10 1703 has no problem on my PC.

**Comment by ielcoro** [comment]
Yes, I´m running on Fall Creators Update.

**Comment by avoidik** [comment]
The problem is linked to PR which is in stash right now https://github.com/JanJoris/oh-my-posh/pull/57

**Comment by xardael** [comment]
Hello, same issue here. Windows version: 1607 OS Build 14393.1770, so I assume this could be Powershell version issue? I have 5.1 Build 14393 Revision 1770.

![ohmyposh](https://user-images.githubusercontent.com/1083252/32325059-bc9f5488-bfcd-11e7-8fbe-d687dd1dd1d0.png)

**Comment by avoidik** [comment]
@xardael check the PR #57, add one line manually and you are done

**Comment by JanDeDobbeleer** [comment]
Merged it, so this can be closed.
