### ISSUE TITLE
What do the icons mean

### ISSUE THREAD

**Issue by sguergachi** [JanDeDobbeleer/oh-my-posh2#61]
I installed this because it looked cool, but I don't understand what the icons/indicators mean (the lighting bolt and the git related indicators), is there somewhere you guys can point me to to figure this out?

Thanks!

**Comment by nwykes** [comment]
$ThemeSettings.GitSymbols will show you the symbols definitions.  Info you're looking might be gleaned from that possibly.  Even more details can be found in $GitPromptSettings.  Reference posh-git which this uses.  The colors of the prompt can be seen with Show-ThemeColors. 

Lightning bolt means running at elevated privileges, like "Run as Administrator".

**Comment by sguergachi** [comment]
Sounds good, thanks!

Sammy Guergachi
