### ISSUE TITLE
Tab options staying highlighted

### ISSUE THREAD

**Issue by gruffled** [JanDeDobbeleer/oh-my-posh2#64]
PS Version : Core 6.0 rc

When tabbing through options all previously highlighted options stay highlighted as below. 

![image](https://user-images.githubusercontent.com/4375084/33882312-97585b44-df2f-11e7-9adf-b8edb39adcaf.png)

This happens in both ConEmu and Hyper.

**Comment by ForNeVeR** [comment]
That's actually an issue with PSReadline and PowerShell Core: https://github.com/lzybkr/PSReadLine/issues/555#issuecomment-356845616 (and it was fixed in PSReadline 2.0).

**Comment by gruffled** [comment]
So it is! Thanks.
