### ISSUE TITLE
Set-Theme not working

### ISSUE THREAD

**Issue by ZhiyuanChen** [JanDeDobbeleer/oh-my-posh2#66]
Set-Theme : 无法将“Set-Theme”项识别为 cmdlet、函数、脚本文件或可运行程序的名称。请检查名称的拼写，如果包括路径，请确保路径正确，然后再试一次。
(Can't recognize “Set-Theme” as a name of cmdlet, function, script, or executable program. Please check the spell, if a path is included, make sure the path is correct and try again.)
所在位置 C:\Users\zc\Documents\WindowsPowerShell\Microsoft.PowerShell_profile.ps1:3 字符: 1
+ Set-Theme Honukai
+ ~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Set-Theme:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by ZhiyuanChen** [comment]
I'd suspect it has some issues in regard to the characters, as there is such a warning:
> Import-Module oh-my-posh
Warning: Some imported command names contain one or more of the following restricted characters: #, () {{}} [] & - / \ $ ^;: '' <> |? @ `*% + =

(PS: this warning only appear in the on-my-posh, while posh-git works perfectly fine

**Comment by JanDeDobbeleer** [comment]
There are no commands with those characters, maybe it has to do with the encoding of your system?
