### ISSUE TITLE
Can't get any themes to show properly

### ISSUE THREAD

**Issue by cobrabr** [JanDeDobbeleer/oh-my-posh2#69]
Using Powershell 5.0.10586.117 on Windows 7 x64.

I can't get any of the themes to show properly. Setting the them _does_ seem to work (in the sense that some things change and I can't see any errors being shown), but they all look super-wonky:

![image](https://user-images.githubusercontent.com/724969/35402604-1aec4674-01cb-11e8-9cb2-55cbad1191ba.png)

Here's a list of my installed modules, for reference:

![image](https://user-images.githubusercontent.com/724969/35402698-5f312c6e-01cb-11e8-8fa2-9f20ac0c2304.png)

**Comment by cobrabr** [comment]
Replacing the beta versions of [posh-git](https://github.com/dahlbyk/posh-git) and [PSReadLine](https://github.com/lzybkr/PSReadLine) with their latest stable versions (0.7.1 and 1.2, respectively), the themes now work.

**Comment by JanDeDobbeleer** [comment]
Yes, the beta version is meant to provide support for PS Core, there's a parameter which causes issues for now. I'm writing a Core compatible version as we speak to mitigate against that.
