### ISSUE TITLE
z complains about .cdHistory on new install

### ISSUE THREAD

**Issue by nwykes** [JanDeDobbeleer/oh-my-posh2#7]
If Z wasn't previously installed, on a fresh install of oh-my-posh the following error appears when launching a new shell.

Get-Content : Cannot find path 'C:\Users\nwykes.cdHistory' because it does not exist.
At C:\Users\nwykes\Documents\WindowsPowerShell\Modules\z\z.psm1:619 char:20

invoking z (like with a cd) will create the file and the complaint will go away.

**Comment by JanDeDobbeleer** [comment]
I've seen that too. He does that on install which means there's an issue on their side. I'll see if I can create a PR with a proposed fix there.

**Comment by JanJoris** [comment]
Pull request with proposed fix created: https://github.com/vincpa/z/pull/23

**Comment by JanJoris** [comment]
It

**Comment by JanDeDobbeleer** [comment]
My PR has been merged so this issue can be closed :beers:
