### ISSUE TITLE
Set-Theme doesn't work on Powershell

### ISSUE THREAD

**Issue by ghost** [JanDeDobbeleer/oh-my-posh2#70]
I've installed oh-my-posh.
When I use cmd.exe to open powershell, it works right:
![image](https://user-images.githubusercontent.com/18572062/35726339-912646e4-083f-11e8-85cd-1e1d879daabc.png)
But when I use run to open powershell, the Set-Theme doesn't work:
![image](https://user-images.githubusercontent.com/18572062/35726278-4ed2a422-083f-11e8-85c1-76cca18cd0a6.png)
If I run cmd in powershell and then run powershell in cmd, it works:
![image](https://user-images.githubusercontent.com/18572062/35726320-7b460292-083f-11e8-87d6-167eb3927312.png)
Why this happens?

**Comment by JanDeDobbeleer** [comment]
That's a cool one. If you add [this](https://github.com/JanJoris/oh-my-posh/blob/master/Helpers/Prompt.ps1#L1) function to your `$PROFILE` can you provide me with the output?

**Comment by ghost** [comment]
| Environment | Output | Display |
| -------------- | ------- | ------- |
| Use Win+R>cmd>powershell | False | OK |
| Use Win+R>powershell | False | OK |
| Use powershell in explorer menu | False | OK |
| Use powershell(admin) in explorer menu | True | ![image](https://user-images.githubusercontent.com/18572062/35763271-722bc3a0-08e3-11e8-9941-40f57ce8ca10.png) |
| Use shift+rightclick in explorer background | False | OK |

**Comment by excpt** [comment]
I just installed posh-git and oh-my-posh and can validate that behavior.

My profile content:

```powershell
function Test-IsVanillaWindow {
    if($env:PROMPT -or $env:ConEmuANSI) {
        # Console
        return $false
    }
    elseif ($env:TERM_PROGRAM -eq "Hyper") {
        # Hyper.is
        return $false
    }
    elseif ($env:TERM_PROGRAM -eq "vscode") {
        # Visual Studio Code 
        return $false
    }
    else {
        # Powershell
        return $true
    }
}

$v = Test-IsVanillaWindow

Write-Output $v

Set-PSReadlineOption -BellStyle None

Write-Output 'Loading Choco Profile'

$ChocolateyProfile = "$env:ChocolateyInstall\helpers\chocolateyProfile.psm1"

if (Test-Path($ChocolateyProfile)) {
  Import-Module "$ChocolateyProfile"
}

Write-Output 'Loading Posh Git'
Import-Module posh-git

Write-Output 'Loading Oh My Posh'
Import-Module oh-my-posh

Write-Output 'Setting Theme'
Set-Theme Honukai
```

**Comment by JanDeDobbeleer** [comment]
I can't reproduce this anymore on my current dev setup, here's to assuming it will be fixed with that release 🍾

**Comment by JanDeDobbeleer** [comment]
Can you validate if [2.0.162](https://www.powershellgallery.com/packages/oh-my-posh/2.0.162) resolves the issue?

**Comment by felixse** [comment]
I had the same issue and 2.0.162 resolved this for me 👍

**Comment by mcroach** [comment]
EDIT: I'm running Win10 1809 (build 17763.195) and oh-my-posh v2.0.230

I'm experiencing a similar issue with Set-Theme not taking effect except it only seems to be impacting consoles launched under Cmder.

The following launch scenarios all work and result in the theme being set to Paradox:
- windows run -> cmd.exe -> powershell
- windows run -> cmd.exe (as admin) -> powershell
- windows run -> powershell.exe
- windows run -> powershell (as admin)
- cmder -> cmd -> powershell
- cmder -> cmd (as admin) -> powershell

However, the following does not work (until explicitly typing set-theme on the cmd line):
- cmder -> powershell
- cmder -> powershell (as admin)

Adding "set-theme paradox" to the cmder specific user_profile.ps1 doesn't make any difference; nor does removing the -noprofile switch from the cmdline that cmder uses to launch the powershell console.

Calling set-theme with verbose output from $PROFILE provides the following and shows that it is executing the command (it's just not taking effect for some odd reason):

```
VERBOSE: Loading module from path
'C:\Users\mcroach\Documents\WindowsPowerShell\Modules\oh-my-posh\2.0.230\Themes\paradox.psm1'.
VERBOSE: Exporting function 'Write-Theme'.
VERBOSE: Importing function 'Write-Theme'.
```

Not sure what else to try here

**Comment by trekco** [comment]
@mcroach did you find a solution?

**Comment by iSeiryu** [comment]
Just upgraded from version 2.x to 3.83.0-beta and it gives me the same issue.

**Comment by iSeiryu** [comment]
Since this pops up in Google search when looking for this issue here in an explanation:
`Set-Theme` is now `Set-PoshPrompt -Theme` - https://ohmyposh.dev/docs/upgrading/
