### ISSUE TITLE
Not compaitable with posh-git 1.0 beta

### ISSUE THREAD

**Issue by nigurr** [JanDeDobbeleer/oh-my-posh2#71]
Hi,

Currently it's not compatible with posh-git v1.0 beta release - https://github.com/dahlbyk/posh-git/releases/tag/v1.0.0-beta1
I believe git set colors are broken, it would be great to support going forward.

**Comment by JanDeDobbeleer** [comment]
Working on this right now.

**Comment by JanDeDobbeleer** [comment]
Fixed in [2.0.162](https://www.powershellgallery.com/packages/oh-my-posh/2.0.162).
