### ISSUE TITLE
The term 'Get-UserName' is not recognized as the name of a cmdlet. Darkblood theme.

### ISSUE THREAD

**Issue by Tiberriver256** [JanDeDobbeleer/oh-my-posh2#74]
I'm unable to use this gloriously awesome Darkblood theme on Win 10 and get the above error.

## PowerShell Info
---
﻿<table>
<colgroup><col/><col/></colgroup>
<tr><th>Name</th><th>Value</th></tr>
<tr><td>PSVersion</td><td>5.1.16299.98</td></tr>
<tr><td>PSEdition</td><td>Desktop</td></tr>
<tr><td>PSCompatibleVersions</td><td>System.Version[]</td></tr>
<tr><td>BuildVersion</td><td>10.0.16299.98</td></tr>
<tr><td>CLRVersion</td><td>4.0.30319.42000</td></tr>
<tr><td>WSManStackVersion</td><td>3.0</td></tr>
<tr><td>PSRemotingProtocolVersion</td><td>2.3</td></tr>
<tr><td>SerializationVersion</td><td>1.1.0.1</td></tr>
</table>

## Module Info
---
﻿<table>
<colgroup><col/><col/></colgroup>
<tr><th>Name</th><th>Version</th></tr>
<tr><td>MSI</td><td>3.2.3.1024</td></tr>
<tr><td>Polaris</td><td>0.1.0</td></tr>
<tr><td>PowerBIPS</td><td>1.2.0.9</td></tr>
<tr><td>Get-ChildItemColor</td><td>1.2.2</td></tr>
<tr><td>Microsoft.PowerShell.Operation.Validation</td><td>1.0.1</td></tr>
<tr><td>oh-my-posh</td><td>2.0.167</td></tr>
<tr><td>PackageManagement</td><td>1.0.0.1</td></tr>
<tr><td>Pester</td><td>3.4.0</td></tr>
<tr><td>posh-git</td><td>0.7.1</td></tr>
<tr><td>PowerShellGet</td><td>1.0.0.1</td></tr>
<tr><td>PSReadline</td><td>1.2</td></tr>
<tr><td>TabExpansionPlusPlus</td><td>1.2</td></tr>
<tr><td>AppBackgroundTask</td><td>1.0.0.0</td></tr>
<tr><td>AppLocker</td><td>2.0.0.0</td></tr>
<tr><td>AppvClient</td><td>1.0.0.0</td></tr>
<tr><td>Appx</td><td>2.0.0.0</td></tr>
<tr><td>AssignedAccess</td><td>1.0.0.0</td></tr>
<tr><td>BitLocker</td><td>1.0.0.0</td></tr>
<tr><td>BitsTransfer</td><td>2.0.0.0</td></tr>
<tr><td>BranchCache</td><td>1.0.0.0</td></tr>
<tr><td>CimCmdlets</td><td>1.0.0.0</td></tr>
<tr><td>ConfigCI</td><td>1.0</td></tr>
<tr><td>Defender</td><td>1.0</td></tr>
<tr><td>DeliveryOptimization</td><td>1.0.0.0</td></tr>
<tr><td>DirectAccessClientComponents</td><td>1.0.0.0</td></tr>
<tr><td>Dism</td><td>3.0</td></tr>
<tr><td>DnsClient</td><td>1.0.0.0</td></tr>
<tr><td>EventTracingManagement</td><td>1.0.0.0</td></tr>
<tr><td>International</td><td>2.0.0.0</td></tr>
<tr><td>iSCSI</td><td>1.0.0.0</td></tr>
<tr><td>ISE</td><td>1.0.0.0</td></tr>
<tr><td>Kds</td><td>1.0.0.0</td></tr>
<tr><td>Microsoft.PowerShell.Archive</td><td>1.0.1.0</td></tr>
<tr><td>Microsoft.PowerShell.Diagnostics</td><td>3.0.0.0</td></tr>
<tr><td>Microsoft.PowerShell.Host</td><td>3.0.0.0</td></tr>
<tr><td>Microsoft.PowerShell.LocalAccounts</td><td>1.0.0.0</td></tr>
<tr><td>Microsoft.PowerShell.Management</td><td>3.1.0.0</td></tr>
<tr><td>Microsoft.PowerShell.ODataUtils</td><td>1.0</td></tr>
<tr><td>Microsoft.PowerShell.Security</td><td>3.0.0.0</td></tr>
<tr><td>Microsoft.PowerShell.Utility</td><td>3.1.0.0</td></tr>
<tr><td>Microsoft.WSMan.Management</td><td>3.0.0.0</td></tr>
<tr><td>MMAgent</td><td>1.0</td></tr>
<tr><td>MsDtc</td><td>1.0.0.0</td></tr>
<tr><td>NetAdapter</td><td>2.0.0.0</td></tr>
<tr><td>NetConnection</td><td>1.0.0.0</td></tr>
<tr><td>NetEventPacketCapture</td><td>1.0.0.0</td></tr>
<tr><td>NetLbfo</td><td>2.0.0.0</td></tr>
<tr><td>NetNat</td><td>1.0.0.0</td></tr>
<tr><td>NetQos</td><td>2.0.0.0</td></tr>
<tr><td>NetSecurity</td><td>2.0.0.0</td></tr>
<tr><td>NetSwitchTeam</td><td>1.0.0.0</td></tr>
<tr><td>NetTCPIP</td><td>1.0.0.0</td></tr>
<tr><td>NetworkConnectivityStatus</td><td>1.0.0.0</td></tr>
<tr><td>NetworkSwitchManager</td><td>1.0.0.0</td></tr>
<tr><td>NetworkTransition</td><td>1.0.0.0</td></tr>
<tr><td>PcsvDevice</td><td>1.0.0.0</td></tr>
<tr><td>PKI</td><td>1.0.0.0</td></tr>
<tr><td>PnpDevice</td><td>1.0.0.0</td></tr>
<tr><td>PrintManagement</td><td>1.1</td></tr>
<tr><td>ProcessMitigations</td><td>1.0.11</td></tr>
<tr><td>Provisioning</td><td>3.0</td></tr>
<tr><td>PSDesiredStateConfiguration</td><td>1.1</td></tr>
<tr><td>PSDiagnostics</td><td>1.0.0.0</td></tr>
<tr><td>PSScheduledJob</td><td>1.1.0.0</td></tr>
<tr><td>PSWorkflow</td><td>2.0.0.0</td></tr>
<tr><td>PSWorkflowUtility</td><td>1.0.0.0</td></tr>
<tr><td>ScheduledTasks</td><td>1.0.0.0</td></tr>
<tr><td>SecureBoot</td><td>2.0.0.0</td></tr>
<tr><td>SmbShare</td><td>2.0.0.0</td></tr>
<tr><td>SmbWitness</td><td>2.0.0.0</td></tr>
<tr><td>StartLayout</td><td>1.0.0.0</td></tr>
<tr><td>Storage</td><td>2.0.0.0</td></tr>
<tr><td>TLS</td><td>2.0.0.0</td></tr>
<tr><td>TroubleshootingPack</td><td>1.0.0.0</td></tr>
<tr><td>TrustedPlatformModule</td><td>2.0.0.0</td></tr>
<tr><td>UEV</td><td>2.1.639.0</td></tr>
<tr><td>VpnClient</td><td>2.0.0.0</td></tr>
<tr><td>Wdac</td><td>1.0.0.0</td></tr>
<tr><td>WindowsDeveloperLicense</td><td>1.0.0.0</td></tr>
<tr><td>WindowsErrorReporting</td><td>1.0</td></tr>
<tr><td>WindowsSearch</td><td>1.0.0.0</td></tr>
<tr><td>WindowsUpdate</td><td>1.0.0.0</td></tr>
<tr><td>WindowsUpdateProvider</td><td>1.0.0.2</td></tr>
</table>

**Comment by JanDeDobbeleer** [comment]
Allow me to fix that 👍
