### ISSUE TITLE
Set-CursorForRightBlockWrite no longer working

### ISSUE THREAD

**Issue by bdukes** [JanDeDobbeleer/oh-my-posh2#77]
It seems than an update in the last few days made `Set-CursorForRightBlockWrite` stop working in Powershell 5 (it seems to be working okay in Powershell 6).

**Powershell 5**
```
 set-theme paradox
 me@DESKTOP-ULJFF6L  ~ [09:12:49 AM]❯
 set-theme agnoster
 me@DESKTOP-ULJFF6L  ~  set-theme paradox
 me@DESKTOP-ULJFF6L  ~ [09:12:59 AM]❯
```

**Powershell 6**
```
 set-theme paradox
 bdukes@DESKTOP-ULJFF6L  ~                                                                                                         [09:15:57 AM]
 ❯ set-theme agnoster
 bdukes@DESKTOP-ULJFF6L  ~  set-theme paradox
 bdukes@DESKTOP-ULJFF6L  ~                                                                                                         [09:16:02 AM]
 ❯
```

**Comment by iCrawl** [comment]
~~I'm unaware as to how you got that right on PowerShell 6?~~

![image](https://user-images.githubusercontent.com/20760160/36881821-8ebb7c02-1dd0-11e8-921b-354c60a4ba28.png)

~~The config is really simple, nothing major~~

```ps1
Import-Module Get-ChildItemColor
Set-Alias l Get-ChildItemColor -Option AllScope
Set-Alias ls Get-ChildItemColorFormatWide -Option AllScope

Import-Module posh-git

if (! (ps | ? { $_.Name -eq 'ssh-agent'})) {
    Start-SshAgent
}

Import-Module oh-my-posh
Set-Theme paradox
```

~~So I'm pretty sure I am not overwriting anything here.~~

^Fixed by installing posh-git `^1.0.0-beta1`

**Comment by JanDeDobbeleer** [comment]
I've got this running on PS5 using posh-git 1.0.0.

![image](https://user-images.githubusercontent.com/2492783/36891532-465aa55a-1e02-11e8-8cb0-d9268bcce554.png)

**Comment by octavezero** [comment]
After updating to posh git to 1.0.0, the alignment problem is solved for me, but another problem remains. Whenever the screen overflows, the cursor for the new line is on the same line as the details. And when i type a command, it overwrites the details line.

This happens after 2.0.172 and affects hyper as well as the default shell. It works only in conemu.
Single line themes like agnoster work fine everywhere.

![hyper_2018-03-06_23-22-23](https://user-images.githubusercontent.com/5926793/37048934-5328262c-2195-11e8-9076-a985373d725e.jpg)

**Comment by JanDeDobbeleer** [comment]
🤔That would imply the other shells do not properly support all ANSI escape sequences as that's what's changed. I'll see if there's a work around.

**Comment by erichiller** [comment]
Tab complete is breaks anytime the `PSReadlineKeyHandler` function of `Complete` is used. Repeatable in both PowerShell 5.1 and 6 (newest 6.1 build) -- tried in ConEmu and the native shell.

```powershell
import-module oh-my-posh
Set-PSReadLineKeyHandler tab -Function complete
ls <tab><tab>
```
and now you have a default prompt `PS>`

![image](https://user-images.githubusercontent.com/5379325/38169347-dd9eb8f8-351c-11e8-8054-2e41cf906b44.png)

**Comment by JanDeDobbeleer** [comment]
Did you install PSReadLine beta2?

`Install-Module -Name PSReadLine -AllowPrerelease -Scope CurrentUser -Force`

**Comment by erichiller** [comment]
Apologies for the delay I've been away. But yes, I just updated both to the newest `oh-my-posh` and `PSReadline` using the `-AllowPrerelease` flag (as of yesterday).

**Comment by JanDeDobbeleer** [comment]
Thx @erichiller, you are not alone though :-) I'll have more time within two weeks so expect at least an update by then.

**Comment by JanDeDobbeleer** [comment]
Can you people re-verify on the latest version?

**Comment by octavezero** [comment]
The newline behavior is working fine with hyper with the all the themes on the latest version version.

**Comment by erichiller** [comment]
@JanDeDobbeleer Thanks much! I can confirm it is working in ConEmu. Just so you have the rest of my environment:

```
ConEmu           180506
Winver             1803 17134.48
oh-my-posh     2.0.207    
PSReadline       1.2
```

Other machines are running 2 for PSReadline, I doubt they'll have issues.

**Comment by JanDeDobbeleer** [comment]
We should thank @fenneh for finding the exact issue here 🙏
