### ISSUE TITLE
Current working dir duplicated

### ISSUE THREAD

**Issue by matheusgrieger** [JanDeDobbeleer/oh-my-posh2#78]
So when I start a new PowerShell in ConEmu, I end up with the expected theme text, but also with a duplicate working directory text. Check the image below.

![image](https://user-images.githubusercontent.com/6992464/36768745-5b30dd12-1c1f-11e8-99eb-8d2453d3c3da.png)

I followed the installation instructions as the Readme says and my Profile file is as follows:

``` sh
Import-Module posh-git
Import-Module posh-docker
Import-Module oh-my-posh
Set-Theme honukai
$DefaultUser = 'Matheus Grieger'
```

No matter what theme I set, it doesn't solve the issue. What can I do?

**Update**
Changed theme to Darkblood. Apparently, ConEmu/Posh are ignoring line breaks:

![image](https://user-images.githubusercontent.com/6992464/36769609-0c2eaeb0-1c24-11e8-81e6-9ccec8edecb7.png)

The second half ([D:\Development]) should be in the second line, where the cursor is. But the inicial issue disappeared.

**Comment by akamud** [comment]
Same problem here

**Comment by JanDeDobbeleer** [comment]
Did you update to the latest version? There was an issue in `2.0.167` which has been fixed in `2.0.172`.

**Comment by JanDeDobbeleer** [comment]
Wait, I do see a bug in Honukai that I didn't notice. Darkblood renders correctly though.

**Comment by matheusgrieger** [comment]
I'll try it again when I get home. Thanks for working on this!

**Comment by JanDeDobbeleer** [comment]
No worries, about the newlines, could be that's linked to a ConEmu setting so please check that too and we'll figure out the cause if needed.

**Comment by matheusgrieger** [comment]
@JanJoris I have tried fiddling with most ConEmu settings I could think of, but none of them solved the line break issue. Do you have any suggestions?

**Comment by JanDeDobbeleer** [comment]
Yes, check what the ANSI settings say:

![image](https://user-images.githubusercontent.com/2492783/37142135-76b91470-22b7-11e8-9e62-022ce4cc3b90.png)

**Comment by BeardedWinter** [comment]
darkblood and honukai as well as all of the other themes that call the Set-Newline function do not appear to be respecting it. My output all remains on the same line as with @matheusgrieger 

I have confirmed that my ConEmu ANSI execution matches your screenshot above

I am using 2.0.176

**Comment by JanDeDobbeleer** [comment]
So strange. I have no clue what's causing the. Can someone export their ConEmu config so I can have a look at the diff with mine?

**Comment by BeardedWinter** [comment]
[ConEmu.log](https://github.com/JanJoris/oh-my-posh/files/1795184/ConEmu.log)
I changed the extension from .xml to .log so that i could upload it. You will need to change it back to .xml

![2018-03-08 19_08_23-cmder](https://user-images.githubusercontent.com/9573024/37183454-221ff1f2-2304-11e8-8320-fcb5af421ee8.png)

In the screenshot above you can see that the  `Set-NewLine` when called from the command line appears to provide the new line as expected. However you can see that the prompt itself is not respecting it.

Just for some more information. I was following this guide. I think you may be familiar with it as I saw you commented on it 2 weeks ago.
https://gist.github.com/jchandra74/5b0c94385175c7a8d1cb39bc5157365e

Let me know if you need anything else. I am also looking at it and will let you know if I make any headway or find out anything else.

**Comment by BeardedWinter** [comment]
I was curious if you were able to see anything in the diff of the conemu conf files?

**Comment by JanDeDobbeleer** [comment]
Not yet, sorry. Been way too busy at work. I'm gonna check right now :-)

**Comment by JanDeDobbeleer** [comment]
I can't seem to find something that points in the right direction and trying to import your config crashes my ConEmu (after changing the extension), can you try to import this [one](https://gist.github.com/JanJoris/eb59998ea3bafe26375562f02648b8a4)?

Also, please check if you're on the latest ConEmu version.

**Comment by BeardedWinter** [comment]
Hey so I copied and pasted your xml to my ConEmu.xml file and the issue remained. It did not honor the `Set-NewLine`

I am providing the content of my .xml  at the following [gist](https://gist.github.com/BeardedWinter/1538b1a6ac7f2f4b82a36628ee034871)

Maybe that will work better for trying on your system. Any other ideas on what to try?

What about a way to hard code a line break into the darkblood theme locally rather than calling the `Set-NewLine` function?

Thanks again for continuing to look into this.

**Comment by BeardedWinter** [comment]
![image](https://user-images.githubusercontent.com/9573024/37572318-a196c8b0-2adf-11e8-999e-1193b84aab46.png)

Also I am on the latest version 180309 of ConEmu

**Comment by JanDeDobbeleer** [comment]
I can try that one, let me mess around with it a bit and see what could work.

**Comment by BeardedWinter** [comment]
I pulled 2.0.193 and it is the same results. I tried removing oh-my-posh and installing clean and it is the same thing.

If I call Set-Newline it appears to set the new line
![image](https://user-images.githubusercontent.com/9573024/38558784-3861d854-3c9f-11e8-85f6-6d43be36f49e.png)

but as you can see the prompt itself when rendered still does not respect that function

**Comment by BeardedWinter** [comment]
![image](https://user-images.githubusercontent.com/9573024/38560510-cc66dabe-3ca3-11e8-8a70-af63764be0ee.png)

As a follow up I tried to take the posh-git prompt to 2 lines using the "`n" and it appears to work. Not sure if that helps or not just trying to provide more insight

**Comment by JanDeDobbeleer** [comment]
This is just killing me. I can't reproduce this as both fixes work on my machines.

**Comment by BeardedWinter** [comment]
What version of windows/powershell/conemu/cmder are you running?

Anything special in your powershell profile that may help?

**Comment by akamud** [comment]
@JanJoris thank you so much for your effort fixing this.

I had the same problem and tried everything. I had a co-worker with everything working fine so I came to a point where I just copied his entire ConEmu folder with no success.
I tried using Cmder too, no success.

So I decided to double check oh-my-posh's installed version and noticed there were **two** installations, one of them was a really outdated version, which caused the bug. 
I don't have my Windows machine with me anymore so I can't say exactly where they were, but one of them was inside my Powershell user folder.

So @matheusgrieger I would suggest double checking you don't have two oh-my-poshes installed. Please tell me if I can help you with any more information to help address this.

**Comment by matheusgrieger** [comment]
As it turns out, I had two installations as well. Unfortunately, this issue started happening in a freshly formatted machine, so it was not the issue. Deleted the older one, but to no avail...

Thanks for your help, @akamud!

And also, thanks a lot,  @JanJoris, your support is being great! I changed my theme to a single line one, so this issue is not bothering me anymore, though I'd really like to go back to a double line theme.

**Comment by BeardedWinter** [comment]
I checked both my local module installs as well as the system module installs. I have only the most current version. : (

**Comment by BeardedWinter** [comment]
Any new ideas or ways to make the newline work?

**Comment by JanDeDobbeleer** [comment]
I'm sorry, been extremely busy at work. Will have more time within two weeks.

**Comment by BeardedWinter** [comment]
Not a problem. We appreciate you continuing to look at this. :)
