### ISSUE TITLE
Slow prompt writing

### ISSUE THREAD

**Issue by Liquidmantis** [JanDeDobbeleer/oh-my-posh2#8]
This is from dot sourcing the theme in the prompt function.

**Comment by JanDeDobbeleer** [comment]
Hi, I made a new branch so I could easily test what you wrote. I also made some fixes (show-themes did not work anymore, he did not set the theme after install) and adjustments (cleanup, mandatory variable). Let me know what you think. All the changes were added to your commit for context preservation. [branch](https://github.com/JanJoris/oh-my-posh/tree/feature/faster_prompt)

**Comment by Liquidmantis** [comment]
Looks good to me!
