### ISSUE TITLE
We're stuck on SVN here...

### ISSUE THREAD

**Issue by franktopel** [JanDeDobbeleer/oh-my-posh2#86]
... how to get support for SVN?

**Comment by fenneh** [comment]
What kind of support are you expecting?

**Comment by franktopel** [comment]
I'm not expecting anything, I'm hoping for something to exist. Making the current branch etc visible in the prompt just like with GIT. Is that possible?

**Comment by fenneh** [comment]
Heh, maybe expecting was a bad choice of words. 

From a quick look and test - https://github.com/imobile3/posh-svn may be worth looking at. It seems to follow a similar method as posh-git for feeding back to the prompt.

**Comment by JanDeDobbeleer** [comment]
Yeah, I didn't really add support for anything other than git given that I rely on posh-git. But feel free to add a PR!
