### ISSUE TITLE
Set-Newline not working as expected

### ISSUE THREAD

**Issue by wattengard** [JanDeDobbeleer/oh-my-posh2#87]
I'm currently using the Honukai prompt and it's supposed to end with a newline, and then an arrow. However, it seems that the newline gets demoted to the end of the prompt, so the arrow ends the previous line, and my input starts at column 1 on the new line.

![image](https://user-images.githubusercontent.com/46117/39812993-0512e6e4-538f-11e8-977a-c2bdd1348bd0.png)

I have tried using a single width character as the "input prompt" character but that doesn't help. I have also tried to use the prompt in a "normal" console windows, but that does not help either...

Replacing the `Set-Newline` in the themes code with a ``Write-Prompt -Object "`n"`` makes the newline come in the right place, but the double-width arrow gets sliced in half and the "PS>" suffix gets added...

![image](https://user-images.githubusercontent.com/46117/39813260-fdb271ca-538f-11e8-8bb4-b2579ad0ad2b.png)

Any suggestions?

**Comment by fenneh** [comment]
That's an interesting one, I use the same theme in Hyper 2.0 and noticed this. I'm going to push my fix and we'll see what comes of it :) 

![image](https://user-images.githubusercontent.com/1257820/40206254-1cb2242e-5a27-11e8-90e2-015841f47e73.png)
