### ISSUE TITLE
Prepare for new posh-git

### ISSUE THREAD

**Issue by giggio** [JanDeDobbeleer/oh-my-posh2#88]
I was trying posh-git 1.0 which is now in beta, and it seems that it is not working with oh-my-posh. I was not yet able to pinpoint the problem, so this is just a heads up that that update might breaks things around here. If/when I found out more I will post here.

**Comment by JanDeDobbeleer** [comment]
I'll check!

**Comment by JanDeDobbeleer** [comment]
Ok, I checked and was already on beta1 for that matter. Now, I updated to beta2 and everything still works. I do remember you also have to add the pre-release of PSReadline when using all of this:

    Install-Module -Name PSReadLine -AllowPrerelease -Scope CurrentUser -Force

Can you install that one and check if everything works as expected?

**Comment by ezpuzz** [comment]
with latest PSReadLine and latest Posh-Git beta2 I cannot see the branch name.

**Comment by JanDeDobbeleer** [comment]
@ezpuzz I've got the same settings, can your provide an image about what you get?

> with latest PSReadLine and latest Posh-Git beta2 I cannot see the branch name.

**Comment by giggio** [comment]
I just tried the latest from oh-my-posh with latest from posh-git, and it still fails.
To reproduce, check my environment at: https://github.com/giggio/poshfiles
All you have to do is clone that recursively at `~\Documents\WindowsPowerShell`. When you open posh, it will work, now cd into .\Modules\posh-git and checkout master, and open posh again. Oh-my-posh will not work anymore.

**Comment by JanDeDobbeleer** [comment]
What does the $error object say?

**Comment by giggio** [comment]
When I load up a new powershell instance `$error` is null.

**Comment by giggio** [comment]
I just tried the latest posh-git. I installed psreadline and [posh-sshell](https://github.com/dahlbyk/posh-sshell) (they moved some ssh stuff away from posh-git). It is still breaking oh-my-posh, but I believe that there are issues on posh-git that may make it unusable at this moment. Beta2 gives me an error on `Get-GitStatus` (`You cannot call a method on a null-valued expression`), and also the HEAD on their master branch. So, the best course of action right now probably is to wait until they stabilize it.

**Comment by giggio** [comment]
I just tested oh-my-posh with the latest posh-git, which is 1.0.0-beta3 and it is still breaking. Can we reopen this issue?

**Comment by giggio** [comment]
I just tested oh-my-posh with the latest posh-git, which is 1.0.0-beta4 and it is still breaking. Can we reopen this issue?

**Comment by giggio** [comment]
I changed some things around and it seems that it now works.
