### ISSUE TITLE
Prompt cursor too far to the right

### ISSUE THREAD

**Issue by killertilapia** [JanDeDobbeleer/oh-my-posh2#93]
The prompt cursor isn't placed next to the prompt symbol. It's placed too far to the right. I'm using the paradox theme. This misalignment is can also be seen in other themes like Avit. 

See image: https://www.dropbox.com/s/aoar1wsfqle5h1w/posh-paradox-misalignment.png?dl=0

Notice the '''cd .\djangodemo''' command.

I'm running Windows 10.0.16299.431.
I have a 4k screen with 250% scale.

Also when I do $ThemeSetting, the ErrorCount is 6.

**Comment by JanDeDobbeleer** [comment]
That's strange, I can't reproduce this one. Which version of oh-my-posh are you on?

**Comment by killertilapia** [comment]
Output of Get-InstalledModule

1.2.3 Get-ChildItemColor                  
2.0.207 oh-my-posh                          
0.7.3 posh-git

I have also installed the Powerline font.

**Comment by igogrek** [comment]
Same issue here, thought it may be related to PSReadline but it seems it isn't - even removing it doesn't change anything.

**Comment by lkuich** [comment]
Same issue here, on Windows 10

**Comment by JanDeDobbeleer** [comment]
Can you update posh-git to the latest version 1 beta, including PSReadline?

**Comment by igogrek** [comment]
@JanDeDobbeleer 
Thanks! It's actually working now and looks great. 
Version 1.0.0 of posh-git fixed the issue.

I've had to update PowershellGet with 
`Install-Module PowerShellGet -Scope CurrentUser -Force -AllowClobber` to get it -AllowPrerelease working.

**Comment by JanDeDobbeleer** [comment]
Nice! I didn't realize how much impact there would be when not running the latest versions, due to breaking changes and PS Core compatibility, I had to adjust the code. I'll make sure to add a section to the README.
