### ISSUE TITLE
Paths appear broken on Unix

### ISSUE THREAD

**Issue by pavelbraginskiy** [JanDeDobbeleer/oh-my-posh2#96]
The directory `/` appears like `/:` in the prompt.

`/usr` appears as `/\usr`

`/usr/local` appears as `/\..\local`

Any path not prefixed by `$HOME` (`~`) appears broken. Also, `/` should be used instead of `\`.

**Comment by pavelbraginskiy** [comment]
An easy fix would be to just use `(pwd) -replace $HOME, "~"` as the path.

**Comment by JanDeDobbeleer** [comment]
Can you validate to see if this is still an issue?

**Comment by pavelbraginskiy** [comment]
@JanDeDobbeleer I realize it's been over a year now, but I just tried the Agnoster theme again and remembered about it. Get-ShortPath still broken, I got around the problem by putting `function Get-ShortPath { Get-FullPath @ARGS }` in my `$PROFILE`, which works fine.

**Comment by JanDeDobbeleer** [comment]
No worries, I wasn't waiting per se :-) I'll check.

**Comment by JanDeDobbeleer** [comment]
@pavelbraginskiy `Get-ShortPath` should be fixed in the latest version for UNIX systems. I'm actually on MacOS myself now.
