### ISSUE TITLE
When in a python virtual env the $DefaultUser setting is ignored

### ISSUE THREAD

**Issue by ztolley** [JanDeDobbeleer/oh-my-posh2#98]
Expected behaviour

Given I have set the $DefaultUser in my profile
When I open a Powershell window
Then the prompt should not show my username@hostname
When I change to a folder for a Python project
And the project has a virtual environment created with `python -m venv .venv`
And I run `.\.venv\Scripts\Activate.ps1`
Then the prompt should indicate the name of the selected virtual environment
Then the prompt should not show my username@hostname

The issue is when the virtual environment is activated with Active.ps1 then the prompt puts the user@hostname back in at the start of the prompt.

**Comment by sohnryang** [comment]
Same behavior here, too.

**Comment by sohnryang** [comment]
[This line](https://github.com/JanDeDobbeleer/oh-my-posh/blob/5080d386536550cd34e4e743f883fea48641d574/Helpers/Prompt.ps1#L166) seems to be the problem.

No idea why the developers coded the `Test-NotDefaultUser` returns false when virtualenv is activated.

**Comment by sohnryang** [comment]
Maybe I should file a pull request about this.
