### ISSUE TITLE
Initial Text After Prompt is colored incorrectly (PS 5.1)

### ISSUE THREAD

**Issue by JustinGrote** [JanDeDobbeleer/oh-my-posh2#99]
Hello,

On PS5.1, the initial text after a prompt gets colored incorrectly, it should be white but it seems to be the color of the last color used in the prompt.

I suspect it's related to the new VT100 handling in PS5.1

### Reproduction (Powershell.exe -noprofile) using v2.0.207
Performed on two separate systems.

![ohmyzsh-promptissue](https://user-images.githubusercontent.com/15258962/41755400-057ef270-758c-11e8-9f6d-f1c0cbef9d68.gif)

**Comment by pavelbraginskiy** [comment]
Here's something you can do: Use PSReadLine: https://github.com/lzybkr/PSReadLine

This will probably fix your issue, and will provide a better line-editing experience in general with syntax highlighting and whatnot.

**Comment by pavelbraginskiy** [comment]
Are you using the PSReadLine module?

**Comment by JustinGrote** [comment]
If you look at my issue submission, PSReadline is right there in the module
list (it's built into 5.1). I've tried it both with 1.2 and with the newer
2.0 of psreadline, same result.

See how my cursor goes red when I mistyped something? THat's PSReadline at
work :)
